### ISSUE TITLE
Auto Mode displaying instead of real mode.

### ISSUE THREAD

**Issue by mbhforum** [tonesto7/nest-manager#10]
I have my Nest set to Heat mode, (not Auto) but the device is showing me Auto.

**Comment by mbhforum** [comment]
[https://cdn.discourse.org/smartthings/uploads/default/optimized/3X/f/2/f29cc926712d9a39ef479140fb8bf8a37c83b671_1_281x499.png](url)

**Comment by mbhforum** [comment]
[https://cdn.discourse.org/smartthings/uploads/default/optimized/3X/0/5/0523c8f5724e0aee56e209d065b1795be133aa8e_1_281x499.png](url)

**Comment by mbhforum** [comment]
[https://cdn.discourse.org/smartthings/uploads/default/original/3X/f/2/f29cc926712d9a39ef479140fb8bf8a37c83b671.png](url)

**Comment by mbhforum** [comment]
Working as designed.

**Comment by tonesto7** [comment]
I'm going to leave this open.  
I can see how this could get confusing.  I will look into adding some indicator that it's in Auto because the location is Away.

**Comment by tonesto7** [comment]
Closing this as it was fixed in last release
