### ISSUE TITLE
Protects triggered event immediately after install

### ISSUE THREAD

**Issue by tonesto7** [tonesto7/nest-manager#11]
When I installed it, Smartthings popped alerts on all my family's phones saying smoke detected on every protect. Had I did this at home I could of warned them, but since I am slacking off at work today, and they were all at work and school, it turned into quite a scare.

https://community.smartthings.com/t/release-nest-manager/42353/15

**Comment by desertblade** [comment]
Made changes to logic, did a full uninstall and reinstall no false positives.

**Comment by tonesto7** [comment]
I would say this was a remote issue.  Closing this issue out
