### ISSUE TITLE
Feature Enhancement - Home & Away based on Presence Sensor

### ISSUE THREAD

**Issue by markPHL** [tonesto7/nest-manager#112]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 2
- How many Protects? 0
- Are you Using the Nest Presence Device? Y
- iOS or Android?: iOS
- Mobile App Version: 2.1.0
## Expected Behavior

Requesting a feature enhancement to set Nest's presence (Home/Away) devices based on the status of a Presence Sensor device.
## Current Behavior

Currently, it appears that Nest presence automations can be set based on SmartThings modes. This suggestion is to add an additional option to set it based on status of Presence Sensor devices.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by tonesto7** [comment]
This is now present in the automations app. Please update your code to the latest version. 
Let me know if you have any issues

**Comment by markPHL** [comment]
Thanks, this is awesome! Would it be possible to set Home and Away based on multiple presence devices? 

For example: 1) Set Nest to Away when both my roommate and I become not present. 2) Return to Home when either one of us become present.

If this makes more sense a new feature request, I can add!

**Comment by desertblade** [comment]
@mconnolly05 

You can do this in Smartthings. Just run the "GoodBye" routine when everyone leaves change mode to Away.  IF you set up Nest-Manager Automations to make ST Away = Nest Away, this will trigger Nest-Manager to set the Nest to Away.

**Comment by tonesto7** [comment]
If I change the presence sensor input to allow multiple.  That would allow you to do what you want.  I'm working a quick update for something else so I will throw that in there.

**Comment by markPHL** [comment]
@desertblade true, but my set up is based on ST Modes for Day, Evening, and Night. If I introduce Home and Away, I'd have to change a lot of my configuration. This option would be more straightforward for me, if it's not too much trouble. Previously I was using a separate smart app by samwang to handle this, but was thinking it would be great to be a core feature to Nest Manager.

**Comment by tonesto7** [comment]
This feature is ready and will be pushed out shortly with some other updates/

**Comment by tonesto7** [comment]
this has been integrated in the last commit

**Comment by markPHL** [comment]
Thanks for the hard work! Just tested out the latest version of the SmartApp. When I select both of my presence sensors and select "Next" the app returns a white page with just a heading that says "Mode - Nest Home/Away Automation". At this moment, this error appears in the log: 

error groovy.lang.MissingMethodException: No signature of method: script14618850459731353383742.paragraph() is applicable for argument types: (java.lang.String, org.codehaus.groovy.runtime.GStringImpl) values: [Nest will be set 'Away' when all Presence sensors leave and will return to 'Home' arrive, ...]
Possible solutions: paragraph(java.lang.String), paragraph(java.util.Map, java.lang.String) @ line 1181

If I hit "Done" on this page, a red banner appears saying "Error saving unnamed page....." Nothing shows in the log when I do this.

Appreciate the work!

**Comment by tonesto7** [comment]
This is how line 1181 so look: `paragraph "Nest will be set 'Away' when all Presence sensors leave and will return to 'Home' arrive", image: getAppImg("instruct_icon.png")`

**Comment by tonesto7** [comment]
I've updated the code and will roll it out after I wrap up another bug.

**Comment by markPHL** [comment]
So close! Now I can get past selecting the two presence sensors and choosing the other settings. When I hit "Done" though, a red banner pops up "You are not authorized to perform the requested operation."

The log shows this:

4:21:56 PM EDT: error groovy.lang.MissingPropertyException: No such property: key for class: java.lang.String @ line 1596

**Comment by tonesto7** [comment]
I've been working on an update to this today.  I'm moving the app to a single automation per child app.

The fix for your issue will be included.  I've been testing the last 2 hours.  Expect a release tonight

**Comment by markPHL** [comment]
You rock!
