### ISSUE TITLE
Automations Not Saving

### ISSUE THREAD

**Issue by mbhforum** [tonesto7/nest-manager#113]
## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ X] The SmartApp and Device are using the latest version.
- [ X] You have reviewed the Readme for potential fixes.
- [ X] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 7
- How many Protects? 4
- Are you Using the Nest Presence Device? No
- iOS or Android?: iOS
- Mobile App Version: 2.1.0
## Expected Behavior

. When Saving an automation, clicking Done, should close screen out.  
 N.A
## Current Behavior

. Get "failedtosavepage:NamePage" error and IDE logs show:  error java.lang.NullPointerException: Cannot get property 'value' on null object @ line 1055

## Steps to Reproduce (for bugs)

1.  Go through automation wizard, use a rule that turns off thermostat based on current temperature. 
   2.
   3.
   4.
## Context

 Build automation.

**Comment by tonesto7** [comment]
This was fixed in recent commit
