### ISSUE TITLE
Nest Weather Zip Code - Pull from Nest and/or ST Hub

### ISSUE THREAD

**Issue by RndmGlitch** [tonesto7/nest-manager#114]
## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X ] The SmartApp and Device are using the latest version.
- [X ] You have reviewed the Readme for potential fixes.
- [X ] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects? 0
- Are you Using the Nest Presence Device? Y
- iOS or Android?: Android
- Mobile App Version: 
## Expected Behavior

Nest Weather to use the Zip that is registered with Nest
## Current Behavior

Nest Weather uses the Zip in the ST Hub. This may or may not be correct based on an issue with gelocation when the hub is setup.
## Context

Offer the ability to change the Zip for Nest Weather, or choose which source is the definitive source (Nest or ST).

**Comment by imnotbob** [comment]
Tony

There is a variable to override the location - it is not exposed thru the UI currently

atomicState.locstr

**Comment by tonesto7** [comment]
Hopefully we fixed this is the last update.
