### ISSUE TITLE
Contact sensor delay before turning thermostat off

### ISSUE THREAD

**Issue by nclpl** [tonesto7/nest-manager#119]
Feature request: It would be great if I could define the amount of time a contact sensor has to be open before Nest Manager turns a thermostat off.
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [ x] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 2
- How many Protects? 4
- Are you Using the Nest Presence Device? nope
- iOS or Android?: iOS
- Mobile App Version: latest
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

  I currently use a SmartApp that turns off my thermostat if I leave the back door open for 2 minutes.  If I'm just shuttling garbage out to the back porch, I don't want the thermostat to turn off.  But if I leave the door open for a long time, I definitely do want it to turn off.  Thanks!

**Comment by tonesto7** [comment]
It already has those options

**Comment by nclpl** [comment]
Hmm… I see that now.  The first time I tried it, I selected contact sensors and a thermostat, but the extra options didn’t populate.  When I tried it just now, it all worked flawlessly.  Possible iOS app strangeness…  but thanks anyway!  This smartapp/device types combo is really spectacular.  Well done.

**Comment by tonesto7** [comment]
Glad you are enjoying it.
