### ISSUE TITLE
Nest Automation - Off when Sensor Not working

### ISSUE THREAD

**Issue by mbhforum** [tonesto7/nest-manager#120]
## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X ] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X ] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 7
- How many Protects? 4
- Are you Using the Nest Presence Device? No
- iOS or Android?:  iOS
- Mobile App Version: 2.1
## Expected Behavior

Nest Automation configured to turn thermostat off when my contact sensor is open and it's not turning it off.   It's been happening to multiple users and in Heating and Heat-Cool mode. 

Thermostat should turn off when contact sensor is detected open. 
## Current Behavior

. Thermostat doesn't turn off.  

Thermostat should turn off 
## Steps to Reproduce (for bugs)

1.  Created Nest Automation that turns thermostat off when in Home mode and contact sensor is set to Open. 
2.  Confirmed mode is set to home, opened my door, confirmed it's reporting open.  
3.  Thermostat does not shut off.  Waited full 5 minutes and also re-initialized automation app. 
   4.
## Context

. Save energy!

This is what would make Nest Manager complete :)

**Comment by tonesto7** [comment]
Thanks for reporting this. I will investigate
