### ISSUE TITLE
Nest External Weather not updating

### ISSUE THREAD

**Issue by prfclark** [tonesto7/nest-manager#130]
## Verify the following before opening an issue:

- [ yes] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ yes] The SmartApp and Device are using the latest version.
- [ yes] You have reviewed the Readme for potential fixes.
- [ yes] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?: 0
- How many Protects? 1
- Are you Using the Nest Presence Device? The Nest Protect has a presence sensor for the nightlight - I assumed it was this
- iOS or Android?: iOS
- Mobile App Version: Latest - installed 3 days ago
## Expected Behavior

 I've assumed the Weather should update according to the current 'Weather', as depicted by the Nest App. 
 I'm not sure exactly, other than that it would update itself upon opening the sensor, and definitely update to current information upon pressing of the 'Refresh' button.
## Current Behavior

 It's not updating or refreshing the external weather data, has not done since installation - the information it's displaying is exactly the same as when I installed the device handler yesterday (it was correct at the instant of installing it) and has not changed in the many times I've checked it during the evening/night yesterday, or this morning. Pressing the 'Refresh' button many times over the last 20 hours does not change the information or force an update.
 Update of the weather data every 15-20 mins or, at least, upon opening the 'device' for detailed viewing. And definitely upon pressing 'Refresh'. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
Just so i'm clear.  This is the actual nest weather device and not the automation app with external weather?

Have you tried watching the logs while refresh is pressed?

**Comment by prfclark** [comment]
Hi - It's not a weather device specifically, I assumed it'd be a 'feed' from the same source as the Nest app itself, since that always shows the outside weather. Does that make sense? It definitely updated to the correct location, temperature etc at the time of install - so it got the data from somewhere.. This seemed to confirm my previous assumption that it's not actually a physical device, simply a 'weather feed' from somewhere. 

I've tried to include a screenshot, to show you what it already says. Also, when I try to add an automation, it then gives an error. 

Based on your question, I'm now thinking that it should actually be a physical device - but where did it get the original information from at install?

![weather_device_1](https://cloud.githubusercontent.com/assets/18661619/14895066/b3cb1292-0d6e-11e6-9a44-16c9029ae609.png)
![weather_device_2](https://cloud.githubusercontent.com/assets/18661619/14895065/b3c9ec6e-0d6e-11e6-808d-a89cc1643e71.png)

**Comment by tonesto7** [comment]
Yea the weather device receives it's data from the Manager app which gets it from ST using the Wunderground Weather.  I will look into this further

The error in the last image will be resolved today

**Comment by prfclark** [comment]
Thanks. For your information, this is what's going on in the Notifications Messages. Looks a bit screwy, too. Don't know if it's related.

I'm not doing anything to the app or in the IDE during the period this is happening - it's related to something it's doing itself. 

One thing to note is that my install of Nest Manager, Automations and Handlers is via copy & paste. The GitHub integration isn't offered via the EU (UK) SmartThings server, according to the ST Support desk. 

I set up my original account via the app BEFORE I received my ST Hub and starter kit - added Nest (via GitHub integration method) and Hive (Copy and Paste). However, the ST Hub wouldn't connect to this account - 'Welcome Code not valid' message - so I contacted ST support. They said my original account was set up on the USA server, which would not recognise UK kit, so I needed to set up an entirely new account and start over, beginning with the ST setup - did this and GitHub integration disappeared. ST support said it's not offered (yet) from the EU server, but may be in the future. 

So, the question in that long story is - by using 'cut & paste' instead of GitHub integration, have I broken something in the SmartApp or Handlers?

![nest_automations_1](https://cloud.githubusercontent.com/assets/18661619/14895446/8af476cc-0d70-11e6-910f-27459dbf0752.png)
![nest_automations_2](https://cloud.githubusercontent.com/assets/18661619/14895447/8afc1eb8-0d70-11e6-946e-ae1cde2a4b55.png)

**Comment by prfclark** [comment]
Finally, I watched the Live Logs on the IDE whilst polling the weather (pressing 'Refresh') and this is what it shows:

 18:48:08: debug Polling parent... **(Not sure why this appeared, I didn't press the button a third time..)**
 18:48:08: info No Device or Structure poll - Devices Last Updated: 75 seconds ago... | Structures Last Updated 76 seconds ago... 
 18:48:06: debug Polling parent... **(Same again)**
 18:47:58: debug Polling parent... **(This when I did a button press)**
 18:47:53: info Waiting on events...
 18:47:53: info For past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.
 18:47:53: info This console provides live logging of your SmartThings.

I took out the OAuth reference for the device - didn't think they needed to be included, but they were there.. If you need it I can include it.

**Comment by prfclark** [comment]
One more thing. I checked the 'Recently' tab on the Weather device and it seemed to update for a while after it was installed, and then it stopped. It hasn't done anything since yesterday at the time shown on the last activity log. I didn't change anything yesterday at all - but updated to Nest Manager 2.0.4 this morning, so no changes that would have been significant. 

Hope this helps

![weather_device_3](https://cloud.githubusercontent.com/assets/18661619/14895928/28289020-0d73-11e6-8bce-49e4a4d3a5db.png)

**Comment by prfclark** [comment]
Implemented the update to Nest Manager v2.0.4 this morning (UK time) and tried out the Nest Manager > Automations > Create New Automation > Use External Temps > Use Local Weather as External Sensor - I still get the 'Error saving unnamed page' message. 

Also, the Weather page is now showing more information, but not updated from its original state - so next few days of weather (shows Weds, Thu, Fri etc), but also showing weather 'from' the date of install (not from today). 

Live logging on 'Refresh' shows:
14:08:48: error java.lang.NullPointerException: Cannot get property 'sunrise' on null object @ line 566
14:08:34: debug Polling parent...

**Comment by tonesto7** [comment]
i'll need some logs in order to help.. I have been watching mine and it's been working flawlessly.  I'm not sure if this is being caused by the servers

**Comment by prfclark** [comment]
Yep, no problem. Can you let me know what action you want me to take and I'll do it, then send you the Live Logs. 

I assume you want me to cut and paste the Live Logs from the IDE, once the device is updated and I press 'Refresh' - correct? Like the one I inserted above.
