### ISSUE TITLE
Hey installed the nest app and the automation app and it says that my location is null, cant get to "done" when I put in my nest password and login ....  

### ISSUE THREAD

**Issue by deacondeleon12** [tonesto7/nest-manager#132]
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?:
- How many Protects?
- Are you Using the Nest Presence Device?
- iOS or Android?:
- Mobile App Version:
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by deacondeleon12** [comment]
I have three nest thermostats in the house.

**Comment by tonesto7** [comment]
Where are you located geographically?

**Comment by deacondeleon12** [comment]
In Richmond, Virginia

**Comment by tonesto7** [comment]
This is an issue with your SmartThings Account.  Every account should have a location assigned to it.  We've had a few users with this issue.  You will need to got into the mobile app and edit the location so it will add it to your account.  If that doesn't work you will likely need to ask SmartThings support to assist you.

**Comment by deacondeleon12** [comment]
Ok thanks.  I want to use your app with the Keen Home app.  I ahve three
NESTS one on each floor.  Will this work?

**Comment by tonesto7** [comment]
I don't have any keen vents yet.  But it should work with them

**Comment by deacondeleon12** [comment]
any propblems with having three nests?

**Comment by tonesto7** [comment]
nope it was designed to handle multiple nests and protects.  Sending commands at the same time to more than one will be delayed a few seconds for each device after the first

**Comment by imnotbob** [comment]
I have 3 nest thermostats in one of my locations…works fine.  It also works fine with multiple protects.

Eric

On May 11, 2016, at 1:56 PM, Tonesto7 <notifications@github.com<mailto:notifications@github.com>> wrote:

nope it was designed to handle multiple nests and protects. Sending commands at the same time to more than one will be delayed a few seconds for each device after the first

**Comment by tonesto7** [comment]
This issue should be resolved with the latest code
