### ISSUE TITLE
Cool Setpoint Change Not Saving

### ISSUE THREAD

**Issue by dylancopeland** [tonesto7/nest-manager#144]
Hello,

I've just installed Nest Manager and got everything setup. I was able to add my location and thermostat just fine but it seems that any change I make isn't saving back to Nest. I also noticed that the "Nest Check-In" and the "Data Last Received" is an old timestamp of when I setup Nest Manager. It doesn't seem to be updating either. 

Perhaps I'm doing something wrong. Any help would be greatly appreciated. Thanks!
## About Your Setup:
- How many Thermostats?: 1
- How many Protects?: 0
- Are you Using the Nest Presence Device?: No
- iOS or Android?: iOS
- Mobile App Version: 2.1.3 (1265)
## Expected Behavior

I'm expecting the temperature cool setpoint change to commit the value that I enter.
## Current Behavior

The temperature cool setpoint gets reset to whatever was set in the Nest app or website.
## Steps to Reproduce (for bugs)
1. Tap the thermostat in SmartThings. 
2. Tap the down arrow a few times.
3. Verify that the changes are not saving either via the Nest app or website.
4. Tap the "Recently" tab in SmartThings and notice that the cool setpoint gets reverted to what it originally was.

**Comment by imnotbob** [comment]
I suggest we start a private PM in the ST community.

We will want to see your IDE logs for a few mins while nest-manager is running, and state settings from the IDE (My locations -> your location -> List SmartApps -> Nest Manager)

Was this a new install or an upgrade?

**Comment by dylancopeland** [comment]
Sure thing. What's your ST forum username? I'll send you a message there.

In the meantime, I found some interesting output in the logs. Perhaps it will help.

> 313d8909-d959-4f26-9738-a0666b7bc722`  3:10:16 PM: error workQueue Exception Error: java.lang.SecurityException: Getting properties on class java.lang.NullPointerException is not allowed
> 
> 313d8909-d959-4f26-9738-a0666b7bc722  3:10:15 PM: trace procNestApiCmd Url: https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/[REDACTED] | params: [uri:https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/[REDACTED], path:, contentType:application/json, query:[auth:[REDACTED]], body:{"target_temperature_f":80}]
> 
> 313d8909-d959-4f26-9738-a0666b7bc722  3:10:15 PM: trace procNestApiCmd Url: https://developer-api.nest.com | params: [uri:https://developer-api.nest.com, path:/devices/thermostats/[REDACTED], contentType:application/json, query:[auth:[REDACTED]], body:{"target_temperature_f":80}]
> 
> 313d8909-d959-4f26-9738-a0666b7bc722  3:10:15 PM: info No Device or Structure poll - Devices Last Updated: 60 seconds ago... | Structures Last Updated 120 seconds ago...

**Comment by imnotbob** [comment]
E_Sch

Also include tonesto on the thread.

On May 23, 2016, at 3:28 PM, Dylan Copeland <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure thing. What's your ST forum username? I'll send you a message there.

In the meantime, I found some interesting output in the logs. Perhaps it will help.

313d8909-d959-4f26-9738-a0666b7bc722` 3:10:16 PM: error workQueue Exception Error: java.lang.SecurityException: Getting properties on class java.lang.NullPointerException is not allowed

313d8909-d959-4f26-9738-a0666b7bc722 3:10:15 PM: trace procNestApiCmd Url: https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/[REDACTED]https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/%5BREDACTED%5D | params: [uri:https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/[REDACTED]https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/%5BREDACTED%5D, path:, contentType:application/json, query:[auth:[REDACTED]], body:{"target_temperature_f":80}]

313d8909-d959-4f26-9738-a0666b7bc722 3:10:15 PM: trace procNestApiCmd Url: https://developer-api.nest.comhttps://developer-api.nest.com/ | params: [uri:https://developer-api.nest.comhttps://developer-api.nest.com/, path:/devices/thermostats/[REDACTED], contentType:application/json, query:[auth:[REDACTED]], body:{"target_temperature_f":80}]

313d8909-d959-4f26-9738-a0666b7bc722 3:10:15 PM: info No Device or Structure poll - Devices Last Updated: 60 seconds ago... | Structures Last Updated 120 seconds ago...

**Comment by imnotbob** [comment]
that is tonesto7

On May 23, 2016, at 6:47 PM, Imnot Bob <Imnot_bob@hotmail.com<mailto:Imnot_bob@hotmail.com>> wrote:

E_Sch

Also include tonesto on the thread.

On May 23, 2016, at 3:28 PM, Dylan Copeland <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure thing. What's your ST forum username? I'll send you a message there.

In the meantime, I found some interesting output in the logs. Perhaps it will help.

313d8909-d959-4f26-9738-a0666b7bc722` 3:10:16 PM: error workQueue Exception Error: java.lang.SecurityException: Getting properties on class java.lang.NullPointerException is not allowed

313d8909-d959-4f26-9738-a0666b7bc722 3:10:15 PM: trace procNestApiCmd Url: https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/[REDACTED]https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/%5BREDACTED%5D | params: [uri:https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/[REDACTED]https://firebase-apiserver02-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/%5BREDACTED%5D, path:, contentType:application/json, query:[auth:[REDACTED]], body:{"target_temperature_f":80}]

313d8909-d959-4f26-9738-a0666b7bc722 3:10:15 PM: trace procNestApiCmd Url: https://developer-api.nest.comhttps://developer-api.nest.com/ | params: [uri:https://developer-api.nest.comhttps://developer-api.nest.com/, path:/devices/thermostats/[REDACTED], contentType:application/json, query:[auth:[REDACTED]], body:{"target_temperature_f":80}]

313d8909-d959-4f26-9738-a0666b7bc722 3:10:15 PM: info No Device or Structure poll - Devices Last Updated: 60 seconds ago... | Structures Last Updated 120 seconds ago...

**Comment by dylancopeland** [comment]
Great, let's continue the conversation over there. I'll go ahead and close this issue. If there is a resolution I'll follow up with the solution.

Thank you!
