### ISSUE TITLE
The nest "Delayed" state fails to be reported in the Nest Manger app.

### ISSUE THREAD

**Issue by horse3109** [tonesto7/nest-manager#167]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects? 4
- Are you Using the Nest Presence Device? 1
- iOS or Android?: IOS
- Mobile App Version:9.3.2
## Expected Behavior

 When the nest thermostat is in the "Delayed" mode, this state should be reported in the Nest Manager app.

## Current Behavior

 The Nest Manager App shows the "cooling" or "heating" state that the thermostat is set to.

## Steps to Reproduce (for bugs)

 Turn the thermostat up and down in succession to get the thermostat to go into delayed mode. View the state in the app.

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
This issue shouldn't be present in the latest releases
