### ISSUE TITLE
Inconsistent formatting in device types

### ISSUE THREAD

**Issue by ahndee** [tonesto7/nest-manager#17]
## About Your Setup:
- How many Thermostats? 1
- How many Protects? 5
- Are you Using the Nest Presence Device? No
- iOS or Android? iOS
- Mobile App Version? 2.1.0 (1247)
## Expected Behavior

Formatting of text in device types should be consistent
## Current Behavior

It is not ;-)
## Steps to Reproduce (for bugs)

1. For Nest Protect, compare lines [216](https://github.com/tonesto7/nest-manager/blob/master/devicetypes/tonesto7/nest-protect.src/nest-protect.groovy#L216) and [228](https://github.com/tonesto7/nest-manager/blob/master/devicetypes/tonesto7/nest-protect.src/nest-protect.groovy#L228) - there is no space after the comma in line [228](https://github.com/tonesto7/nest-manager/blob/master/devicetypes/tonesto7/nest-protect.src/nest-protect.groovy#L228)
2. Compare line [210](https://github.com/tonesto7/nest-manager/blob/master/devicetypes/tonesto7/nest-protect.src/nest-protect.groovy#L210) for Protect with line [340](https://github.com/tonesto7/nest-manager/blob/master/devicetypes/tonesto7/nest-thermostat.src/nest-thermostat.groovy#L340) for Thermostat - the Protect is missing the two newlines before the display of the current version
3. Additionally it would also be nice to be able to use 24h time format (`H:mm:ss`) instead of the current (`h:mm:ss a`) - maybe an additional preference setting?
## Context

(no functional issues here other than purely visual)

**Comment by tonesto7** [comment]
Item 1 is now fixed.
Item 2 is all @desertblade :) - Part of the Issue with that is that it looks slightly different on Android
Item 3 is a fantastic idea.  I will create a separate enhancement issue.

**Comment by desertblade** [comment]
For item 2 its unreadable on android. I plan on changing the Thermostat at some time, but was fixing another issue in Protect so I cleaned that up.

**Comment by desertblade** [comment]
PR for item 2 in.  Once fully stabilized we will make a pass. Clean up formatting some and make sure we are using similar functions. To be fair github and ST really jacks up tabs, ruining nice looking code.

Probably should also look for dead code to yank out.

**Comment by tonesto7** [comment]
There is not much left that can be removed in DH,  Closing Issue
