### ISSUE TITLE
nest cam with nest manager 2.5

### ISSUE THREAD

**Issue by peeties40** [tonesto7/nest-manager#172]
I see on the GitHub page it says it doesn't work with nest cams yet but I also see people talking about getting them to work. I added everything correctly but when it asks me to login to nest cam it says nest locations you currently cant add this. Is there a way to bypass this? 
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?:0
- How many Protects?0
- Are you Using the Nest Presence Device?yes
- iOS or Android?:both
- Mobile App Version:2.1.5 build 204791
## Expected Behavior

Should be able to add home. 

## Current Behavior

It says you cant currently add this under select your location. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
I don't currently have any nest cams so It the application doesn't support it currently.  The error you are seeing is cause by bugs in the latest android client.  If you have iOS i suggest you use that to get throught the initial config

**Comment by peeties40** [comment]
awesome!!! thank you so much for the advice and the prompt response! And
putting these two things together!
