### ISSUE TITLE
oAuth Not Working

### ISSUE THREAD

**Issue by mbriney** [tonesto7/nest-manager#174]
On version 2.5.4.  The "Login to Nest" item properly brings up the oAuth screen, but when I log in using the proper credentials it does a blue loading circle for a few seconds and then leaves me with a white screen.  Clicking done then takes me back to the Nest Manger screen and asks me to select a location but none are available.

**Comment by tjscales** [comment]
I'm not finding any locations either. I can't finish the installations without them

**Comment by tonesto7** [comment]
You both are using android?

If yes then that is why.  The latest client broke something.  There is a request in with ST to get it fixed.  It seems to be random and only affects new installs.  It works 100% on iOS

**Comment by mbriney** [comment]
I was using iOS

**Comment by tonesto7** [comment]
Well I just tested and it working so I'm not sure what issue you are having.

**Comment by desertblade** [comment]
There was some issues yesterday around the time of the ticket.  Nest-Manager was not loading for at least me and @E_sch.  

Are you using the parent account (main) to login to Nest?

**Comment by tjscales** [comment]
I don't have an iPhone that I can use. Not sure what to do. 
On Jun 26, 2016 12:48 PM, Tonesto7 notifications@github.com wrote:You both are using android?

If yes then that is why.  The latest client broke something.  There is a request in with ST to get it fixed.  It seems to be random and only affects new installs.  It works 100% on iOS

**Comment by myrtillerose** [comment]
I'm having the same problem... Any leads on a fix?

**Comment by mbriney** [comment]
@desertblade I am using the main account.  

Here's a screenshot of each screen that I'm seeing.  In the second to last screen that's all white, I am clicking the done button at the top.

![img_0907](https://cloud.githubusercontent.com/assets/253367/16368195/83920fb8-3bf9-11e6-8ef1-656261d61119.jpg)
![img_0908](https://cloud.githubusercontent.com/assets/253367/16368198/83c330ac-3bf9-11e6-8303-bd4e65e32b54.jpg)
![img_0909](https://cloud.githubusercontent.com/assets/253367/16368200/83c5fa3a-3bf9-11e6-9217-425e724a42fd.jpg)
![img_0910](https://cloud.githubusercontent.com/assets/253367/16368199/83c3cd00-3bf9-11e6-91b1-5008bd2ae5d5.jpg)
![img_0911](https://cloud.githubusercontent.com/assets/253367/16368197/83c2f420-3bf9-11e6-8c45-2f7e9d30635f.jpg)
![img_0912](https://cloud.githubusercontent.com/assets/253367/16368201/83cc9926-3bf9-11e6-80a4-54be4a8d842e.jpg)
![img_0913](https://cloud.githubusercontent.com/assets/253367/16368196/83adf16a-3bf9-11e6-8283-f39de1997294.jpg)

**Comment by tonesto7** [comment]
I have tested the app by performing a reinstall 4 times.  Everytime it has installed properly and is working great.  
I hate to say it but without some logs showing errors i'm not sure how to help you.

**Comment by tonesto7** [comment]
Try again with v2.5.6 and let me know if the issue still occurs

**Comment by mlyndaker2014** [comment]
I am having the exact same issue.

**Comment by tonesto7** [comment]
I have another update coming out within the hour.  I hope will fix your issues if it doesn't then this is an issue with your nest account :)

**Comment by tonesto7** [comment]
v2.5.7 is out and I really hope it resolves your issues

**Comment by mbriney** [comment]
I updated the app and device handlers from the repo.  I even went into the Nest account and removed the previously paired oAuth request.  Went into the SmartThings app, verified that it had the 2.5.7 version, re-authed and am getting the same thing.  One other piece of information is the oAuth request is registered in the Nest account but it shows last accessed as null.

![nest-permission](https://cloud.githubusercontent.com/assets/253367/16506511/d9f13f38-3ef0-11e6-9ebf-c157482986fd.jpg)

**Comment by mbriney** [comment]
Here's the results of the live log.

![live-log](https://cloud.githubusercontent.com/assets/253367/16506586/7aa26768-3ef1-11e6-99b4-83fc9b9fb8dd.jpg)

**Comment by tjscales** [comment]
Does it fix the Android problem?
On Jun 30, 2016 4:31 PM, Tonesto7 notifications@github.com wrote:v2.5.7 is out and I really hope it resolves your issues

**Comment by mlyndaker2014** [comment]
Still not working :( this is what I am getting,

**Comment by tonesto7** [comment]
@mbriney I'm seriously scratching my head on this one... it's almost like that whole instance is corrupted..  It should be impossible for all of those to fail simultaneously.

Have you tried deleting the app completely in the IDE and starting over?

**Comment by tonesto7** [comment]
@tjscales 

> Does it fix the Android problem?

The latest version does resolve install issue on Android

**Comment by tonesto7** [comment]
@mbriney 

> I updated the app and device handlers from the repo.  I even went into the Nest account and removed the previously paired oAuth request.  Went into the SmartThings app, verified that it had the 2.5.7 version, re-authed and am getting the same thing.  One other piece of information is the oAuth request is registered in the Nest account but it shows last accessed as null.
> 
> ![nest-permission](https://cloud.githubusercontent.com/assets/253367/16506511/d9f13f38-3ef0-11e6-9ebf-c157482986fd.jpg)

The Last Accessed null is common.   I notice that on a lot of the integrations that I have installed.

**Comment by mbriney** [comment]
Just removed the app and the device handlers.  Then re-installed.  Logged into Nest and removed the oAuth and then tried to re-connect.  Same issues.  

In the live log this line seemed to be of note.  Should there be anything we manually edit in the app?  A setting perhaps?

`SmartThings Location is not returning (TimeZone: null) or (ZipCode: null) Please edit these settings under the IDE...`

**Comment by tonesto7** [comment]
@mbriney Are located outside of the US?

When you say that you removed the app and devices you actually removed them and re-added and enabled Oauth?

**Comment by mbriney** [comment]
Hi @tonesto7 I am based in the US.

And yes when I removed the app and then re-added it I followed the instructions and enabled the oAuth.

**Comment by tonesto7** [comment]
Can you open up the mobile app and tap the settings icon in slide out menu.  Basically I need you to re-select your location on the map and press save.

**Comment by mbriney** [comment]
Ok I did that and tried again and am getting the same error.

**Comment by tonesto7** [comment]
ugh... Is this your first time installing the software? 

Either way i'm going to have you try installing the app and devices from v2.0 they were rock solid for over a couple months so if you have issues with those then it's definitely your ST account and you will need to reach out to support.

https://github.com/tonesto7/nest-manager/tree/v2.0
Remember to install the devices along with the manager app

**Comment by mbriney** [comment]
Ok just pulled 2.0 and when I log in using the oAuth it actually gets further and shows me the icon link between SmartThings and Nest.  However when I click done it still says no Nest locations can be found.

![img_0921](https://cloud.githubusercontent.com/assets/253367/16510236/560b9a02-3f12-11e6-86b8-aee74417b310.jpg)

On the live logging it seems to be throwing this error:

```
00a003bd-6a3c-4ceb-a891-024fa3db6ca3  10:31:19 PM EDT: debug atomicState.structData is: null
00a003bd-6a3c-4ceb-a891-024fa3db6ca3  10:31:19 PM EDT: error getApiData (type: str) Exception: java.lang.NullPointerException: Cannot get property 'null' on null object
```

**Comment by tonesto7** [comment]
can you do me a favor…. Since it generated the token for you I would like to see what data is being returned on your account.   When in the IDE click on My Locations > Installed SmartApps > Nest Manager and send me the authToken?  Once I pull the data you can revoke the token

**Comment by mbriney** [comment]
Sure here's the auth token: 

c.WeUB6Na4dZHviVzeMo6Ax0EHjFIFlTTKPGzqVvCE56PSTX8FzqX164rWZTVFjIgPLA358kZ7NNe8Bsd7FPICgz968E21jVaEOiJq89mtgNIlpnr7UJ0oaJcdw4x4bHeXTYmIN4s3fhznS5nw

**Comment by tonesto7** [comment]
Thanks you can go ahead a remove the app so it revokes the token.  I'm off to bed tonight but i'm going to review the data in the morning.

**Comment by myrtillerose** [comment]
Hey Matt, I was having the same exact issue as you for several days. I removed the location within the ST app and added it back, and went through the motions of setting up the hub again. When I did that, I was finally able to login to nest and it found my location. I'm not sure if you tried that but I would give it a shot. Hope that helps.

**Comment by mbriney** [comment]
Thanks @myrtillerose I haven't tried that but given that I have about 30 devices on ST I'm not to eager to rebuild everything.  Perhaps it's an issue with the IDE then, maybe I should try Smartthings support.

**Comment by mlyndaker2014** [comment]
I was having the same problem, and after doing what myrtillerose said above it worked :) When I had setup the Smartthing App I did not set my location. After I added my location it worked as advertised.

**Comment by tonesto7** [comment]
Closing this issue as it's related to the users ST account location settings
