### ISSUE TITLE
Error Following Update

### ISSUE THREAD

**Issue by azchipka** [tonesto7/nest-manager#179]
iOS Version

Following installation of the most recent update when I go to the manage devices it doesn't load. 

Logs show the following Error:
 java.lang.NullPointerException: Cannot get property 'L8DMEK_BN0Y60fzChu75MUAHe-wLYsX_5dP5ZmVjgp0cGyC-ytfzYA' on null object

**Comment by azchipka** [comment]
Attempted to reinstall completely and when I attempted to authorize the app it works fine with the nest login but when it returns to config screen it says not allowed and the logs show the following error:

java.lang.RuntimeException: Metadata Error: Missing required page parameter 'name'

**Comment by tonesto7** [comment]
I'm not in front of a computer currently but will look at it in a couple hours

**Comment by azchipka** [comment]
Rolled back to 2.5.4 and all works fine there so its something in the most recent change to address the android issue.

**Comment by tonesto7** [comment]
This should be resolved in v2.5.7

**Comment by tonesto7** [comment]
Closing issue
