### ISSUE TITLE
Add 12H or 24H preference

### ISSUE THREAD

**Issue by tonesto7** [tonesto7/nest-manager#18]
It would also be nice to be able to use 24h time format (H:mm:ss) instead of the current (h:mm:ss a) - maybe an additional preference setting?

**Comment by ahndee** [comment]
What would be even better (though I don't think currently possible with what the app allows) is to use the device preferences - when using 24h system-wide, the app correctly shows correctly formatted times in the activity feeds.

**Comment by tonesto7** [comment]
The changes will occur under the devices themselves based on the setting in the app.  That way if someone has 7 protects they won't need to modify all 7 devices.

The app is updated and i'm just about done with the devices.

**Comment by tonesto7** [comment]
Well ST broke the scheduler so now I can't test.

**Comment by ahndee** [comment]
I feel you - trying to get some debugging done myself and things are blowing up all over the place…

Out of curiosity - does the `tileSelect()` in the `metadata` work? Is it supposed to switch layout when changing modes between auto and non-auto? It doesn't for me but I can't tell whether this is a current platform issue. This would be a great way to have dynamic tile coloring work which currently is not possible…

**Comment by tonesto7** [comment]
I got it to work the first time.  I'm confident I can get it going with some cleverness but I haven't played with it much recently

**Comment by tonesto7** [comment]
I just pushed the updates for app and device out with this feature

**Comment by ahndee** [comment]
I did open a ticket with ST (Request #199800 [ENHANCEMENT REQUEST] add ability to specify date/time format based on user's device settings) and received the following answer:

> I went ahead and passed this along to our developers and if enough people request this they will begin developing something like this.

So - maybe you guys could go ahead and ask something similar as well ;-) While the current setup works great, it shouldn't be required for every single app/device type to add a preference for the time format…
