### ISSUE TITLE
Weather alerts are showing "\n"

### ISSUE THREAD

**Issue by ahndee** [tonesto7/nest-manager#180]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects? 2
- Are you Using the Nest Presence Device? NO
- iOS or Android?: iOS
- Mobile App Version: 2.1.4
## Expected Behavior

Newlines in weather alerts should be displayed as newlines (e.g., "\n" should be replaced with "`<br />`")
## Current Behavior

Newlines show up as "\n" instead
## Steps to Reproduce (for bugs)

1. Open the Weather DTH
2. Tap on an active weather notice/alert
3. Read the text and see "\n"

![img_2576](https://cloud.githubusercontent.com/assets/66345/16476459/85abc196-3e3c-11e6-90d6-6b26d32f6db6.jpg)

**Comment by tonesto7** [comment]
I don't have any weather alerts currently but I believe Eric corrected the issue

**Comment by ahndee** [comment]
Yep - seems to be OK with the latest version.
