### ISSUE TITLE
HTML tiles should not be scalable

### ISSUE THREAD

**Issue by ahndee** [tonesto7/nest-manager#228]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects? 5
- Are you Using the Nest Presence Device? No
- iOS or Android?: iOS
- Mobile App Version: 2.1.4 (1271)
## Expected Behavior

Double-tapping a table cell in any of the device handler htmlTiles should do nothing
## Current Behavior

It zooms the htmlTile, cutting off parts of the information
## Steps to Reproduce (for bugs)

1. Open one of the devices
2. Double-tap a table cell in the htmlTile
## Context

This can be solved by adding `"user-scalable=no"` to the `content` of the `viewport meta` tag.

**Comment by tonesto7** [comment]
Thanks This has been merged into v3.0
