### ISSUE TITLE
Add Support for Contact Sensors

### ISSUE THREAD

**Issue by ghost** [tonesto7/nest-manager#25]
Add support for contact sensors to turn off Nest Thermostat.
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects?: 2
- Are you Using the Nest Presence Device?: Y
- iOS or Android?: iOS
- Mobile App Version: 2.1.0
## Expected Behavior

When one of the selected contact sensors has been open for X number of minutes, turn Nest Thermostat Off.  Once all selected contact sensors are closed again set Nest Thermostat back to previous mode (heat/cool/auto).
## Current Behavior

Currently I have an other SmartApp that does this but when I switched to Nest Manager it stopped being able to put the Nest back into operation.  Opening any of my windows for more that 2 minutes will trigger the SmartApp to tell Nest Manager to set the Thermostat to Off but it does not do go back when I close all the windows.  I figured this is something that can just be included in the Nest Manager and I can eliminate the other SmartApp. 
## Context

My house has 14 windows, when I open one or all of them for more than 2 minutes I would like the Nest Thermostat to turn off automatically.  Once all my windows are closed I want the Nest to return to normal operation.

**Comment by tonesto7** [comment]
Do you have any idea what your other app is looking for?  Maybe we can add in the function to get it working...

**Comment by ghost** [comment]
It's a smartapp from the market place called "Thermostat Auto Off."

Here is the source code, it is a very simple app.

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/smartapps/dianoga/thermostat-auto-off.src/thermostat-auto-off.groovy

**Comment by imnotbob** [comment]
It fails because the device handler is missing several required capbilities.

Pretty easy fix

Eric

On Mar 20, 2016, at 8:53 PM, k6usy <notifications@github.com<mailto:notifications@github.com>> wrote:

It's a smartapp from the market place called "Thermostat Auto Off."

Here is the source code, it is a very simple app.

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/smartapps/dianoga/thermostat-auto-off.src/thermostat-auto-off.groovy

**Comment by tonesto7** [comment]
They are by no means required.  It also has every thermostat capability available the problem is the command the app uses to set the thermostat mode is missing.

**Comment by tonesto7** [comment]
I will the required commands to the latest update that will be pushed out tonight or in the morning.

**Comment by ghost** [comment]
Ok cool, once the code is updated I can test it out when I get home.

**Comment by tonesto7** [comment]
it's already update.  
I also added some more test for other things causing issues I hope to have that pushed out tonight.

**Comment by ghost** [comment]
It is working now, thanks! closing the ticket.
