### ISSUE TITLE
Remote Sensor Automation - Only use the remote temperature.

### ISSUE THREAD

**Issue by rno310** [tonesto7/nest-manager#261]
Great job on this app!

This is not really an issue, just  a quick question/comment.

I see the following code in the remote sensor automation...

`else if (reqSenCoolSetPoint - curSenTemp > threshold && **curTstatTemp - curCoolSetpoint > threshold**)`

....
`if(**curCoolSetpoint != reqSenCoolSetPoint**)`

If I understand correctly, the remote sensor temp controls the nest in addition to the nest sensor, not instead=> The nest will stop cooling only when both locations are at the set temperature.

I my particular case, the temperature at the nest location is irrelevant and I only want to use the remote sensor. To do so, I have commented out the curCoolSetpoint conditions in the above code to achieve this. Does that make sense to you? Would it make sense to add it as an option?

**Comment by tonesto7** [comment]
The remote sensor logic basically does exactly what you are asking for

**Comment by rno310** [comment]
Thank you for your answer. The updated code makes much more sense (At least to me ;) ). Great work and thanks for  the hard work!
