### ISSUE TITLE
Ability to silence nest protect from app

### ISSUE THREAD

**Issue by apsmith12** [tonesto7/nest-manager#30]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?:
- How many Protects?
- Are you Using the Nest Presence Device?
- iOS or Android?:
- Mobile App Version:
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by tonesto7** [comment]
I wish I could add this. It's not exposed through the API.  I'm sure it has to-do with liability reasons.
