### ISSUE TITLE
Nest Weather Not Accessible from SmartTiles

### ISSUE THREAD

**Issue by dbhjed** [tonesto7/nest-manager#302]
When attempting to add Nest Weather as a weather tile in SmartTiles it does not show.

SmartTiles is able to access the Nest Weather Device as it can be used as a Luminance tile

**Comment by imnotbob** [comment]
Have you let the SmartTiles folks know?   I expect they may have something hard coded somewhere that they don't try to use us?

**Comment by tonesto7** [comment]
Closing this out
