### ISSUE TITLE
When creating rules (Rule Machine) with the DTH, dth names is so long it is hard to distinguish in other apps

### ISSUE THREAD

**Issue by imnotbob** [tonesto7/nest-manager#31]
Creating rules when you have multiple thermostats, it is hard to pick the correct device, as their names are long, and the Beginning is the same "Nest Thermostat xxxxxxxxx"
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?:2
- How many Protects?0
- Are you Using the Nest Presence Device? sometimes there is only one of these in a location
- iOS or Android?:ios
- Mobile App Version: latest
## Expected Behavior

Names are more unique in beginning rather than end

## Steps to Reproduce (for bugs)

1. setup multiple nests
2. use rule machine to create rules only using some of them
   3.
   4.

**Comment by ghost** [comment]
You can just edit each device and rename it.

**Comment by tonesto7** [comment]
v2.0 Allows setting custom names
