### ISSUE TITLE
NestCams show blank except for two buttons, Streaming and refresh

### ISSUE THREAD

**Issue by TruAsset** [tonesto7/nest-manager#325]
## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ X] The SmartApp and Device are using the latest version.
- [X ] You have reviewed the Readme for potential fixes.
- [X ] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?:2
- How many Protects?0
- Are you Using the Nest Presence Device?No
- iOS or Android?:IOS
- Mobile App Version:2.1.5
## Expected Behavior

Should see my camera streaming
## Current Behavior

Its blank
## Steps to Reproduce (for bugs)

Not sure how toresolve without deleting everything and starting over. I updated today with the latest version to attempt to get it to work. Still nothing. The streaming button works and will turn the camera on and off. I just have to be in the nest app to see it. It is not working through nest-manager. 
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by djpinoy** [comment]
I have the same issue, but to add a few more data points:
- As mentioned in the SmartThings thread, I have made sure to "publish" my camera and protect it with a password
- However, when I go into the Nest Manager SmartApp on my phone, and go into Diagnostics/Info -> Next Camera(s) Info, I see "is_public_share_enabled" set to (false)
- I am using a Dropcam Pro (not original Dropcam nor NestCam)
- I do _not_ have a Nest Aware subscription

So my questions:
- Is "is_public_share_enabled: (true)" still a requirement for Nest Camera DTH v1.1.1?
- If so, any other tips on how to get this to report "true"?  (Do I need to update anything on the mobile app?  Already tried uninstalling / reinstalling the DTH).

Thanks!

**Comment by tonesto7** [comment]
The camera device does not work with streams secured with a password...

**Comment by tonesto7** [comment]
I'm not it.will ever be possible to enable the use of password...Nest doesn't support streaming outside of its own apps.  The streaming is working now based a workaround hack.

**Comment by djpinoy** [comment]
Ahh - thanks @tonesto7 for the quikc reply!

After reading back over the links in the thread, looks like I misunderstood the mechanics.  Thanks for clarifying the intended usage!!

**Comment by TruAsset** [comment]
I got it to load but only if I share publicly, that's not what I want. Do I have to share the stream in order for camera to work?

**Comment by djpinoy** [comment]
@BenightedOne Yes - that's what is implied in the SmartThings thread and the response above.  You must share the stream _publicly_ (no password) if you want it to show up in Nest Manager.

**Comment by TruAsset** [comment]
Guess I missed that in the instructions! Great job tonesto, it's an incredible achievement.
