### ISSUE TITLE
Errors in Contact Automation 

### ISSUE THREAD

**Issue by tmleafs** [tonesto7/nest-manager#336]
Im getting the following errors
a56e4166-8431-4f55-8ca1-476ec17ffb95  23:42:05: error groovy.lang.Missi  ngMethodException: No signature of method: physicalgraph.sandbox.TruncatingLoggingListener.error() is applicable for argument types: (java.lang.String, java.lang.String, java.lang.SecurityException) values: [conWatCheck Exception:, error, java.lang.SecurityException: Getting properties on class java.lang.NullPointerException is not allowed]
Possible solutions: error(java.lang.Object), error(java.lang.Object, java.lang.Throwable), getLog(), every(), iterator(), grep() @ line 7595
a56e4166-8431-4f55-8ca1-476ec17ffb95  23:42:05: error voiceNotifString Exception: java.lang.NullPointerException: Cannot invoke method toLowerCase() on null object @ line 8758
## Verify the following before opening an issue:

- [Y ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [Y ] The SmartApp and Device are using the latest version.
- [Y] You have reviewed the Readme for potential fixes.
- [Y ] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects? 2
- Are you Using the Nest Presence Device? No
- iOS or Android?: Android
- Mobile App Version: 2.1.6 B207055
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
This issue has been resolved
