### ISSUE TITLE
Heating icon green 

### ISSUE THREAD

**Issue by mbhforum** [tonesto7/nest-manager#35]
Heating icon is green in "recently" activity feed.
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ X] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 4
- How many Protects? 7
- Are you Using the Nest Presence Device? Yes
- iOS or Android?: iOS
- Mobile App Version:2.21
## Expected Behavior

 icon should be red with heating gif
 see above
## Current Behavior

  see above 
see above
## Steps to Reproduce (for bugs)

 raise heat on thermostat in device or in Nest app and review activity feed

1.
2.
3.
4.
## Context

 graphical issue. Or functional issues

**Comment by tonesto7** [comment]
This issue should be fixed with Code that will likely be released today.

**Comment by desertblade** [comment]
Verified Fixed
