### ISSUE TITLE
Some Icons are giant on Windows 10 Mobile

### ISSUE THREAD

**Issue by JimSt24** [tonesto7/nest-manager#352]
In most of the Nest Manager app on Windows 10 Mobile, the icons are giant and push the real content off the screen, making it unusable.
I'm using a Lumia 950.
As a reference, the Ask Alexa app has correctly sized icons, so I think it is something specific to Nest Manager's icons.
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?: 1
- How many Protects? 3
- Are you Using the Nest Presence Device? YES
- iOS or Android?:  Windows Mobile.
- Mobile App Version: Nest Manager 3.1.3, ST app 1.61.1921
## Expected Behavior

Icons should be normal size.
## Current Behavior

Icons are too big and make parts of the screen inaccessible.
## Steps to Reproduce (for bugs)

One example is the main logo on the Help, Info and Instructions screen.  Another is on the Create New Automation screen.
## Context

Can't do any configuration on my phone.  I have to use my child's old Android gaming phone to configure Nest Manager.

**Comment by JimSt24** [comment]
Here are some screenshots:
https://1drv.ms/f/s!AhMd-7L76d3cyoktFZ8sx4JEcRldzA

**Comment by tonesto7** [comment]
It only does that on the windows phone client.  They are high res icons but the client doesn't scale them properly. 

There is a setting under preferences to turn the icons off

**Comment by JimSt24** [comment]
Ok.  Thanks for all your great work!
