### ISSUE TITLE
camera's partially work - 6 cameras total

### ISSUE THREAD

**Issue by josserman** [tonesto7/nest-manager#354]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?:6
- How many Protects? 12
- Are you Using the Nest Presence Device? 1
- iOS or Android?: ios
  **Nest Camera's : 6
- Mobile App Version:3.1.3
## Current Behavior

 I can turn cameras on and off, but when I try to see them I get an error message, error logging below
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

Clear
8995cb3e-eae6-4af5-b307-4e6acb86aeb4  12:11:26 PM: error groovy.lang.MissingMethodException: No signature of method: physicalgraph.device.DeviceTypeExecutorBase$_closure5.doCall() is applicable for argument types: (java.lang.String, groovy.lang.MissingMethodException) values: [getCamHtml Exception:, groovy.lang.MissingMethodException: No signature of method: physicalgraph.device.DeviceTypeExecutorBase$_closure5.doCall() is applicable for argument types: (java.lang.String, groovy.lang.MissingMethodException) values: [getCamUUID Exception:, groovy.lang.MissingMethodException: No signature of method: script147421473818346036911.LogAction() is applicable for argument types: (java.lang.String, java.lang.String, java.lang.Boolean) values: [getCamUUID PublicVideoId is missing...., ...]
Possible solutions: section()]
Possible solutions: doCall(), doCall(java.lang.Object), call(), call([Ljava.lang.Object;), call(java.lang.Object), findAll()]
Possible solutions: doCall(), doCall(java.lang.Object), call(), call([Ljava.lang.Object;), call(java.lang.Object), findAll() @ line 927

**Comment by tonesto7** [comment]
Did you enable them for public streaming in the nest app?

**Comment by josserman** [comment]
I realize I missed that step and I did do it last night, but perhaps I need to reinstall the app now...?

**Comment by josserman** [comment]
Ok reinstalled camera and all good sorry about that

**Comment by josserman** [comment]
Ok reinstalled camera and all good sorry about that
