### ISSUE TITLE
Unable to view video with my Nest Cam

### ISSUE THREAD

**Issue by snijjar** [tonesto7/nest-manager#371]
I am unable to view the video feed from the nest cam through smartthings I have double checked and I have enabled public sharing but unable to see through smartthings I get the following error:

"Unable to Display Video Stream!!!"
Please make sure that public streaming is enabled for this camera under
https://home.nest.com

I have am running 4.0.2

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats?:
- How many Protects?
- Are you Using the Nest Presence Device?
- iOS or Android?:
- Mobile App Version:
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
can you provide IDE logs?

**Comment by snijjar** [comment]
How do I do this?

**Comment by imnotbob** [comment]
When you get into the IDE, go to the "Live Logging",

then try what you were doing with the camera in the mobile app, and then cut and paste out the log entries that came out during your test.

**Comment by snijjar** [comment]
So what I to test now was to downgrade the code to 3.1 for both the device handler and smart app and try to upgrade from the repo but now I am unable to see an aviliable update but I am able to see my camera again with the 3.1 code

**Comment by snijjar** [comment]
Here is the log from the nest cam:

1a27ac3d-8587-4f93-a470-f844bf8c7532  9:15:09 AM: error physicalgraph.exception.DataCharacterLimitExceededException: Handler data length (3894) cannot be greater than 2500 characters. @ line 194

Here is the log from the Nest Manager

15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:18:07 AM: debug getChildDevices(true), children=8
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:18:07 AM: info updateChildData()
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:18:06 AM: debug API Device Data HAS Changed... Updating State data...
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:18:06 AM: info Updating Device Data...(Last Updated: 179 seconds ago) (async)
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:18:06 AM: info Updating Structure Data...(Last Updated: 179 seconds ago) (async)
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:15:08 AM: debug getChildDevices(true), children=8
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:15:08 AM: info updateChildData()
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:15:07 AM: debug API Device Data HAS Changed... Updating State data...
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:15:06 AM: info Updating Device Data...(Last Updated: 180 seconds ago) (async)
15371016-24b2-42bb-b6a5-3b88a12f2bb4  9:15:06 AM: info Updating Structure Data...(Last Updated: 180 seconds ago) (async)

**Comment by imnotbob** [comment]
Thanks I found the issue and sent Tony a PR that should fix it

My bug - sorry.

**Comment by snijjar** [comment]
Not a problem I glad you found the bug I just bought by nest cam and thought I did something wrong when updating to v4

Will you let me know when this has been updated or will you be releasing 4.0.3?

**Comment by imnotbob** [comment]
Tony pushed the fix, so if you update your camera dth, you should be all set.  Let me know.

Sorry for the issue.

**Comment by snijjar** [comment]
Thanks again everything is working now! sorry for the noob questions from before :)

**Comment by tonesto7** [comment]
Glad it's working. Closing Issue
