### ISSUE TITLE
Devices no longer responsive

### ISSUE THREAD

**Issue by zwrose** [tonesto7/nest-manager#375]
## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.
## About Your Setup:
- How many Thermostats? 2
- How many Cameras? 2
- How many Protects? 0
- Are you Using the Nest Presence Device? No
- iOS or Android?: Android
- Mobile App Version: 2.2.1
## Expected Behavior

Bug: Take any action on nest devices available in the SmartThings app -- for example, turn a camera on. Expected behavior is when changing a Camera from Off to Streaming, the camera turns on.
## Current Behavior

Actual behavior: SmartThings UI updates, but Nest change does not actually happen
## Steps to Reproduce (for bugs)

1. Go to things
2. touch Camera toggle to change from Off to Streaming
3. Go to Nest app or look at camera
4. see that camera does not turn on (having waited minuted)
## Context

Nest Manager is unworkable in this state :( Note: This was working fine for some time, but then suddenly stopped working. No clear driver as to what changed.

Please include a copy of your log under the IDE if possible>>>
Logs:

Clear
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:58:59 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390762 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:58:59 AM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 304139 seconds ago... | Structures Last Updated 304200 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:58:07 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:58:07 AM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:57:59 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390702 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:57:59 AM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 304079 seconds ago... | Structures Last Updated 304140 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:57:07 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:57:07 AM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:56:59 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390642 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:56:59 AM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 304019 seconds ago... | Structures Last Updated 304080 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:56:07 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:56:07 AM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:55:59 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390582 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:55:59 AM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 303959 seconds ago... | Structures Last Updated 304020 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:55:07 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:55:07 AM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:54:59 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390522 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:54:59 AM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 303899 seconds ago... | Structures Last Updated 303960 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:54:07 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:54:07 AM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:59 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390462 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:59 AM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 303839 seconds ago... | Structures Last Updated 303900 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:44 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:44 AM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:37 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 390440 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:36 AM: warn Nest Manager | Command Exists in queue... Skipping...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  10:53:36 AM: debug Nest Manager | Nest Manager(setCamStreaming) - Setting Camera 6M_yNIWNzZJtoH9F1F9CfQHkTP4dTYfuVq1BtrhJARdKiemv--o8mQ Streaming to: (On)

**Comment by tonesto7** [comment]
Thanks for the detailed info. I've seen this happen with the camera before.  It doesn't always respond very quickly (I've had it delay almost 5 min).  Does your thermostat change temperature if you change it under st?

**Comment by zwrose** [comment]
Unfortunately no. Thermostats are all out of sync (showing incorrect temperatures). Cannot change temps and have it reflect on the device. Here are the logs of me trying to change temp:

`e2e7acfe-9a7c-43b4-a0d7-b8152011bb67  11:05:23 AM: info External Thermostat Compensation | Remote Sensor: Too Soon to Evaluate Actions...Scheduling Re-Evaluation in (30 seconds)
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  11:05:22 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  11:05:22 AM: trace Nest Manager | workQueue Run queue: 0 async
72c35784-f10d-4e39-b394-354a3c780f47  11:05:15 AM: debug Downstairs Thermostat: UPDATED | Pause Updates is: (false) | Original State: (true)
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  11:05:15 AM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 391138 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  11:05:14 AM: debug Nest Manager | setTargetTempLow: gUpeEUao25_0zAlu9wKaRUqJ6a_76jyZ | (68)F | virtual false
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  11:05:07 AM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  11:05:07 AM: trace Nest Manager | workQueue Run queue: 0 async
e2e7acfe-9a7c-43b4-a0d7-b8152011bb67  11:05:03 AM: trace External Thermostat Compensation | Event | Thermostat Heating Setpoint: Downstairs Thermostat - Heating Setpoint is (68)
72c35784-f10d-4e39-b394-354a3c780f47  11:05:03 AM: debug Downstairs Thermostat: UPDATED | HeatingSetpoint is (68) | Original Temp: (67)
72c35784-f10d-4e39-b394-354a3c780f47  11:05:03 AM: debug Downstairs Thermostat: Sending changeSetpoint(Temp: 68.0)
e2e7acfe-9a7c-43b4-a0d7-b8152011bb67  11:05:03 AM: trace External Thermostat Compensation | Event | Thermostat Heating Setpoint: Downstairs Thermostat - Heating Setpoint is (67)
72c35784-f10d-4e39-b394-354a3c780f47  11:05:02 AM: debug Downstairs Thermostat: UPDATED | HeatingSetpoint is (67) | Original Temp: (66)
72c35784-f10d-4e39-b394-354a3c780f47  11:05:02 AM: debug Downstairs Thermostat: Sending changeSetpoint(Temp: 67.0)
e2e7acfe-9a7c-43b4-a0d7-b8152011bb67  11:05:02 AM: trace External Thermostat Compensation | Event | Thermostat Heating Setpoint: Downstairs Thermostat - Heating Setpoint is (66)
72c35784-f10d-4e39-b394-354a3c780f47  11:05:02 AM: debug Downstairs Thermostat: UPDATED | HeatingSetpoint is (66) | Original Temp: (65)
72c35784-f10d-4e39-b394-354a3c780f47  11:05:02 AM: debug Downstairs Thermostat: Sending changeSetpoint(Temp: 66.0)`

Nothing actually changes with the thermostat.

**Comment by tonesto7** [comment]
Can you change the temp one degree manually from the thermostat/ nest mobile app?

I'm curious if it will pull in the changes from the API on its next data poll or if it's only the commands that are not working

**Comment by zwrose** [comment]
I changed it in the nest app, but no update. Logs (i made the change in the Nest app around 2:27pm):

22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:30:07 PM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:30:07 PM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:29:59 PM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 403422 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:29:59 PM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 316799 seconds ago... | Structures Last Updated 316860 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:29:07 PM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:29:07 PM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:28:59 PM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 403362 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:28:59 PM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 316739 seconds ago... | Structures Last Updated 316800 seconds ago...
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:28:07 PM: warn Nest Manager | workQueue: command is processing already
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:28:07 PM: trace Nest Manager | workQueue Run queue: 0 async
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:27:59 PM: info Nest Manager | schedNextWorkQ queue: 0 | recentSendCmd: 2 | last seconds: 403302 | cmdDelay: 4
22fbc5bd-c2fa-49c3-b0b9-c0e80228197c  2:27:59 PM: info Nest Manager | No Device or Structure poll - Devices Last Updated: 316679 seconds ago... | Structures Last Updated 316740 seconds ago...

Also, the reported current temps in the ST app have been the same for the last few days, and they are quite incorrect.

**Comment by imnotbob** [comment]
It looks like it has not been working for quite some time (300,000+ seconds).

I suggest you check everything is installed correctly and re-authorize.

**Comment by zwrose** [comment]
Everything is in sync with the latest from GitHub.

I reauthorized with nest; this gave me one good sync of data (for example, current temperature updated), but now controls/refreshes are unresponsive again.

**Comment by tonesto7** [comment]
Yea I never even noticed that.  Yeah open the manager app > preferences > nest login

**Comment by tonesto7** [comment]
Can you send me your installationId found under help info section

**Comment by zwrose** [comment]
I have a screenshot of it, what's the best way to send to you?

**Comment by zwrose** [comment]
Everything is in sync with the latest from GitHub.

I reauthorized with nest; this have Mr one good sync of data (for example,
current temperature updated), but now controls/refreshes are unresponsive
again.

**Comment by zwrose** [comment]
With nothing heard, I tried the nuclear option and uninstalled everything/reinstalled everything. Things are working again. Will close this for now, but will re-open if it begins to fail again.
