### ISSUE TITLE
Update Bug / Uninstall Bug / Misspelling

### ISSUE THREAD

**Issue by imseandavis** [tonesto7/nest-manager#376]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 1
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: iOS
* Mobile App Version: 3.14

## Expected Behavior
After update form repo the app should update in the phone. The phone should also allow for uninstall of the SmartApp. Latest version is spelled wrong (spelled as lastest)

## Current Behavior
After update form repo the app should update in the phone but doesn't. Also the phone reports an unexpected error has occurred when trying to uninstall the smart app from the phone.

## Steps to Reproduce (for bugs)
1. Update form repo all device handlers and smartapp on smartthings
2.Check phone smartapp, phone smart app still report 3.14 and as says lastest version is 4.0.0
3.Also clicking uninstall this app in SmartThings on iOS results in an error.
4.

## Context
Trying to upgrade smartapp

**Comment by tonesto7** [comment]
This seems to be an issue more and more.  It's not a Nest Manager problem it's a platform issue. 

Please start here and read down 

https://community.smartthings.com/t/release-nest-manager-4-0/60052/70?u=tonesto7

**Comment by tonesto7** [comment]
Oops I closed by mistake

**Comment by imseandavis** [comment]
You were correct, I connected to NA02 and completed the same steps and life has been well ever since. Thanks!

**Comment by duyano1** [comment]
I want to first of all start by saying thanks for the hard work. I did copy and past the code manually - everything was successful except that it put out an error saying "Device Handlers are likely missing or not published. Please verify all Device handlers are present before continuing."

**Comment by imnotbob** [comment]
I submitted a fix for the spelling error.  Also in V4.1 there are cleanups that improve uninstall.

**Comment by tonesto7** [comment]
This issue should be resolved.  Closing
