### ISSUE TITLE
Unable to turn Nest Cam on

### ISSUE THREAD

**Issue by itsdave** [tonesto7/nest-manager#378]
Firstly, thanks for all your work on this.

While trying to turn on my Nest Cam, i get the following error:
```
groovy.lang.MissingMethodException: No signature of method: script14801953001771717367776.latestValue() is applicable for argument types: (java.lang.String) values: [isStreaming]
Possible solutions: getDataValue(java.lang.String) @ line 519
```

Any ideas on how to resolve this?

Regards,

Dave.

**Comment by imnotbob** [comment]
make sure you are using the latest camera device
change that line in the IDE to be:

OLD    def cur = latestValue("isStreaming").toString()

New    def cur = device.latestValue("isStreaming").toString()

**Comment by itsdave** [comment]
Ok - I think i've managed to fix this, or at least for me.

I implemented the fix you mentioned above, but after looking at lots of logs, it was trying to switch off the camera when it was off, and turn on a camera that was already on.

```
def chgStreaming() {
	def cur = device.latestValue("isStreaming").toString()
	if(cur == "on" || cur == "unavailable" || !cur) {
		streamingOff(true)
	} else {
    	        streamingOn(true)	
	}
}
```

Is what I ended out with. The video feed doesn't load - but that doesn't bother me - just being able to switch it on and off!

Do you know if there is any way to link it to the Smart Home Monitor?

**Comment by tonesto7** [comment]
This issue should have been resolved in the last pull request
