### ISSUE TITLE
Missing NEST Thermostat mode ECO using Rule Machine to set mode

### ISSUE THREAD

**Issue by cmeans** [tonesto7/nest-manager#379]
Using Rule Machine, unable to set NEST Thermostat Mode to ECO.  ECO mode isn't a selectable option...seems like an accidental omission, but maybe represents a misunderstanding on my part.

## Verify the following before opening an issue:
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 1
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: Android
* Mobile App Version:

## Expected Behavior
ECO should be a selectable option.

## Current Behavior
Only available options are:  auto, heat, cool, off and "emergency heat".

## Steps to Reproduce (for bugs)
[Skipped]

## Context
I have a routine that uses a custom feed to track my electricity costs...when the rate is "too high", I want to set the NEST into ECO mode, so heating/cooling will only kick in if the temp gets way too low or too high (using the settings that the NEST Thermostat is already configured with)

![2016-11-27 16 37 33](https://cloud.githubusercontent.com/assets/5384091/20649841/b05b0074-b48d-11e6-9810-e104153fce14.png)

**Comment by tonesto7** [comment]
yeah... Rule machine supports the native commands you see above.  You may need to switch to CoRE which will allow you to directly run the custom Eco() command.

**Comment by cmeans** [comment]
OK.  I've not been as happy with CoRE in comparison to Rule Machine (somethings that worked fine in Rule Machine don't work right in CoRE), but I'll try substituting it in this case.  I also note that Rule Machine is only showing present() and away() commands to be available.

**Comment by imnotbob** [comment]
rule machine can work, you do need to enable a custom command as “eco” is not part of the standard smarththings capabilities.  CoRE or Rule allow creation of custom commands.

**Comment by cmeans** [comment]
Thanks.  I've just setup a Basic Piston, I'll have to wait to see if it works.

**Comment by cmeans** [comment]
Functionality confirmed.  Thanks.
