### ISSUE TITLE
Cameras problematic with Routines

### ISSUE THREAD

**Issue by zwrose** [tonesto7/nest-manager#381]
## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
            ---yes, and I've made changes to the latest camera device as suggested in #378 
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 0
* How many Cameras? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: Android
* Mobile App Version: 2.2.3

## Expected Behavior
I have a number of routines that turn on and off both of my nest cams (for example, Good Night turns them both on; Good Morning turns them both off).

Expected behavior (which worked until I recently updated): both devices turn on or off when the routine runs.

## Current Behavior
Only one camera turns on (if they are both off), or off (if they are both on). It is always the same camera that does not turn on/off. However, I can successfully turn on/off each individually, regardless of whether the other one is on or off. I had to make the changes described in #378 to get this to work.

When they are both OFF, and a routine tries to turn them both ON, this error is logged:

`groovy.lang.MissingMethodException: No signature of method: physicalgraph.device.CommandService.executeAction() is applicable for argument types: (physicalgraph.device.cache.DeviceDTO, java.lang.Integer) values: [Entryway Camera, 14]
Possible solutions: executeAction(physicalgraph.device.IDevice, java.lang.String), executeAction(physicalgraph.device.IDevice, java.util.List), executeAction(physicalgraph.device.IDevice, physicalgraph.device.HubAction), executeAction(physicalgraph.device.IDevice, physicalgraph.device.HubMultiAction), executeAction(physicalgraph.device.IDevice, physicalgraph.device.ParallelAction), executeAction(physicalgraph.device.IDevice, physicalgraph.device.RestAction) @ line 556`

Interesting note, "Entryway Camera" is listed here, but that is the cam that SUCCESSFULLY turns on. My other cam, "Mudroom Camera", stays off.

When they are both ON, and a routine tries to turn them both OFF, this error is logged:

`groovy.lang.MissingMethodException: No signature of method: physicalgraph.device.CommandService.executeAction() is applicable for argument types: (physicalgraph.device.cache.DeviceDTO, java.lang.Integer) values: [Entryway Camera, 15]
Possible solutions: executeAction(physicalgraph.device.IDevice, java.lang.String), executeAction(physicalgraph.device.IDevice, java.util.List), executeAction(physicalgraph.device.IDevice, physicalgraph.device.HubAction), executeAction(physicalgraph.device.IDevice, physicalgraph.device.HubMultiAction), executeAction(physicalgraph.device.IDevice, physicalgraph.device.ParallelAction), executeAction(physicalgraph.device.IDevice, physicalgraph.device.RestAction) @ line 580`

Similar to above, "Entryway Camera" is listed here, but that is the cam that SUCCESSFULLY turns off. My other cam, "Mudroom Camera", stays on.

## Steps to Reproduce (for bugs)
1. Add two Nest Cams to Nest Manager
2. Create a routine
3. Add both cams to "turn off these lights or switches" (or "turn on these lights or switches")
4. run the routine

## Context
I need to turn both of my cameras on to monitor different parts of my house! For when my SmartThings Mode can also equate to a Nest Away mode, I can let Nest handle this (as I also use Nest Manager's mode sync), but for SmartThings Night Mode, where the Nest Mode remains Home, I must rely on routines to turn on both cameras.

**Comment by zwrose** [comment]
Additional information: it looks like this might be an issue with just Cams and Routines in general, and it's affecting more than just the Cams.

With both Cams in the routine as described above, alongside other items (for example, 2 lights), ONLY the one cam turns on/off. Both lights AND the other Cam stay incorrectly on/off. It's like the command kicks off one cam but then crashes, and as a result all other things in the routine fail to run.

When I remove one of the Cams, this STILL happens. The one Cam turns on/off, but the other items (such as lights) also fail.

Errors in the logs are the same as the ones above.

**Comment by tonesto7** [comment]
closing this issue out
