### ISSUE TITLE
Can not setup Thermostat Automation that include "Turn Off if Water Leak is detected" option.

### ISSUE THREAD

**Issue by polzovotel** [tonesto7/nest-manager#386]
## Verify the following before opening an issue:

- [Yes ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ Yes] The SmartApp and Device are using the latest version.
- [ Yes] You have reviewed the Readme for potential fixes.
- [ ?] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects?: 1
* Are you Using the Nest Presence Device?: No
* iOS or Android?: Android
* Mobile App Version: Net Manager 4.1.0

## Expected Behavior

When you setup a new Thermostat Automation (or change the existing one) to turn on " Turn Off if Water Leak is detected" option, you should be able to successfully save the automation.

## Current Behavior

I attach the screenshots step by step showing what I did.
https://postimg.org/gallery/2zf46to8o/

## Steps to Reproduce (for bugs)

1. Open SHM.  Goto Automation -> SmartApps -> Nest Manager
2. Click on Automations -> Tap to Modify -> Create New Automation -> Thermostat Austomations
3. Select the thermostat, scroll down and click on "Turn off if Water Leak is detected".
4. Select the water leak sensor , click on Done. You will get a error.

## Context

Please include a copy of your log under the IDE if possible>>>

920eee08-4232-4895-a442-7001bfdd64a5  10:49:15 AM: debug Creating battery event for voltage=2.7V: Naomi Arrival Sensor battery is 100%
920eee08-4232-4895-a442-7001bfdd64a5  10:49:15 AM: debug Creating presence event: Naomi Arrival Sensor presence is present
**a584cbc0-816f-4cd3-a2a9-24cfd17d693c  10:49:12 AM: error java.lang.NullPointerException: Cannot invoke method capitalize() on null object @ line 8079**
920eee08-4232-4895-a442-7001bfdd64a5  10:49:00 AM: debug Sensor checked in 5.258 seconds ago
920eee08-4232-4895-a442-7001bfdd64a5  10:48:55 AM: debug Creating battery event for voltage=2.7V: Naomi Arrival Sensor battery is 100%
920eee08-4232-4895-a442-7001bfdd64a5  10:48:55 AM: debug Creating presence event: Naomi Arrival Sensor presence is present

**Comment by tonesto7** [comment]
Thanks for posting all of the details.  I'm investigating the error right now.

**Comment by tonesto7** [comment]
Can you tell me the type of water sensor you are using?  Is it a custom device handler?

The error is being generated when trying to query the water sensors "water" attribute which doesn't seem to be set by the device.  Can you send me a screen shot of the the device's attributes in the IDE > My Devices > the device you are selecting?

**Comment by polzovotel** [comment]
It is a Samsung water leak sensor:
http://www.samsung.com/us/smart-home/smartthings/sensors/f-wtr-us-2-f-wtr-us-2/

I will send you the ide screen short shortly.




On Dec 5, 2016 11:22 AM, "Tonesto7" <notifications@github.com> wrote:

Can you tell me the type of water sensor you are using? Is it a custom
device handler?

The error is being generated when trying to query the water sensors "water"
attribute which doesn't seem to be set by the device. Can you send me a
screen shot of the the device's attributes in the IDE > My Devices > the
device you are selecting?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonesto7/nest-manager/issues/386#issuecomment-264917098>,
or mute the thread

**Comment by polzovotel** [comment]
Hello,

Here is the device info :

**Comment by polzovotel** [comment]
Btw, I see that I have ide at

https://graph-na02-useast1.api.smartthings.com/ide.
And not
at https://graph.api.smartthings.com.

Not sure if this make any difference.

**Comment by tonesto7** [comment]
I've updated the manager code.  If you pull in the latest it should resolve your issues

**Comment by polzovotel** [comment]
Thank you - working great now !

**Comment by tonesto7** [comment]
glad to hear it.  You might need to bridge the points on that water sensor once to make sure it's updated it's state in SmartThings.  All I did was add in code to handle the missing attribute info.  The device still doesn't have all of the correct values.
