### ISSUE TITLE
Event History for Nest Thermostat scale is off on graph

### ISSUE THREAD

**Issue by seanchilds** [tonesto7/nest-manager#387]
There seems to be an offset being applied because all my graphs are showing lower then they should be. A 73 deg F set point appears to be 43 deg F all other data is off respectfully.
Graph for Nest Weather is showing fine however.

Also the graph for both the Thermostat and Weather will not update after being opened once with out closing the app first.
I believe you were aware of this one already.

## Verify the following before opening an issue:

- [* ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ *] The SmartApp and Device are using the latest version.
- [* ] You have reviewed the Readme for potential fixes.
- [ *] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* Are you Using the Nest Presence Device? yes
* iOS or Android?: Android 
* Mobile App Version: 2.2.2

## Current Behavior
<A 73 deg F set point appears to be 43 deg F all other data is off respectfully.
Graph for Nest Weather is showing fine however.
![screenshot_20161205-143403](https://cloud.githubusercontent.com/assets/18430391/20907955/992ad640-bb0e-11e6-9f69-d7e2daeb7612.png)

## Steps to Reproduce (for bugs)

1. Just open Nest Thermostat for offset issue.
2. then switch to Nest Weather 
3. wait for data to update 
4. switch back to Nest Thermostat
 data will no longer update now unless force the app to close or reboot.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
Thanks for opening the issue.  I will look into this a soon as I can

**Comment by seanchilds** [comment]
I have also noticed that I can no longer view additional info when I click
on the graph or pie chart.
This is also still working on weather

On Dec 5, 2016 7:14 PM, "Tonesto7" <notifications@github.com> wrote:

Thanks for opening the issue. I will look into this a soon as I can

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonesto7/nest-manager/issues/387#issuecomment-265040701>,
or mute the thread

**Comment by Xtropy74** [comment]
An update to the Groovy code for the DH has been posted which has resolved this issue for me

**Comment by seanchilds** [comment]
The graphs a working now.
Thank you!

however the other problem with the refreshing still requires a force close
of the app before data will refresh.
I'm not sure if you can resolve this one but wanted you to know.
