### ISSUE TITLE
Alternate temp sensor "You are not authorized to perform the requested operation" when saving

### ISSUE THREAD

**Issue by whasf** [tonesto7/nest-manager#390]
[adding_remote_temp_sensor.txt](https://github.com/tonesto7/nest-manager/files/644126/adding_remote_temp_sensor.txt)

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.
*I don't know what this is

## About Your Setup:
* How many Thermostats?:1
* How many Protects?1
* Are you Using the Nest Presence Device? yes
* iOS or Android?: iOS
* Mobile App Version: 2.2.3

## Expected Behavior

I should be able to add a thermostat automation to use alternate temp sensor (in my case it is a motion detector) to control the zone temp

## Current Behavior

It looks like it is adding then comes up with a red bar "You are not authorized to perform the requested operation"
It looks like it has been added but it doesn't seem to affect the operation of my thermostat

## Steps to Reproduce (for bugs)

1. Create new automation
2. Thermostat Automations
3. Select my thermostat
4. Use Alternate Temp Sensors Control Zone Temperature
5. Remote Sensor Config
6. (Rule) Action Type
7. Tap "Auto"
8. Default Temp Sensor(s)
9. Tap "Motion Sensor"
10. Default heat is 69, set default cool to 74
11. Leave everything else alone, tap "done"

## Context

My house gets pretty hot since the Nest thermostat is in a bad place. I am trying to utilize the SmartThings devices I have around the house to get better readings and regulate it.

Please include a copy of your log under the IDE if possible>>>

**Comment by whasf** [comment]
Added log to original report

**Comment by imnotbob** [comment]
you are running the latest code for nest Manager - V4.1.0 dated 11/19/2016?

If so, at line 9323, can you make the following change?

Original line:
dayModeDesc += "\n ├ ${t?.label}: ${(t?.label.length() > 10) ? "\n │ └ " : ""}(${getDeviceTemp(t)}${tempScaleStr})"

New line:
dayModeDesc += "\n ├ ${t?.label}: ${(t?.label?.length() > 10) ? "\n │ └ " : ""}(${getDeviceTemp(t)}${tempScaleStr})"

(new line adds a ? after the 2nd label word)

Also, save in IDE, publish for me

Then delete that automation completely and re-create.   There is something about the virtual thermostat that is not correct.

**Comment by whasf** [comment]
Yes I am on 4.1.0, I made that change on the line and I didn't get the error when creating the automation.

**Comment by imnotbob** [comment]
ok, I have provided a fix for the next release.  I think Tony wants to put it out this week sometime.

**Comment by whasf** [comment]
The virtual nest thermostat worked! It got to the target temp I set on it. Thank you for the quick help.
