### ISSUE TITLE
Projects help page on github has a lot of broken links / bad pictures

### ISSUE THREAD

**Issue by whasf** [tonesto7/nest-manager#391]
In looking for help to troubleshoot my issues I tried clicking on the "Projects Help Page" located near the bottom of https://github.com/tonesto7/nest-manager, it goes to https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/help-page.html which looks like it could be helpful but there is a 404 for https://rawgit.com/tonesto7/nest-manager/master/Documents/help/automations/renote-sensors.html and the pages that do work have missing images.

**Comment by imnotbob** [comment]
There is documentation located here:
http://thingsthataresmart.wiki/index.php?title=Nest_Manager

**Comment by tonesto7** [comment]
I've removed the help pages and embedded in the wiki pages.
