### ISSUE TITLE
Thermostat Automation - Contact Automation doesn't seem to work

### ISSUE THREAD

**Issue by whasf** [tonesto7/nest-manager#392]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?1
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: iOS
* Mobile App Version: 2.2.3

## Expected Behavior

I expect the contact automation to turn off my Nest when the door is open

## Current Behavior

It used to work, it stopped working unexpectedly. I have tried steps including recreating the automation and even removing and re-adding the nest manager

## Steps to Reproduce (for bugs)

1.Create new automation
2. Thermostat Automations
3. Select my thermostat
4. Turn off if door/window contact open?
5. Contact Sensors Config
6. Which Contacts?
7. Back Door
8. Leave all defaults, hit "done"

It is created without error but if I open the door it doesn't turn off the Nest. This used to work before the update.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
It would be help to see the IDE logs for Nest Manager and the automation.

Note that contacts sets the thermostat to ECO mode, so your ECO temperatures in the thermostat (or native nest mobile/web app) needs to be used to ensure ECO temperatures are set.

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

Login into the ide   http://ide.smartthings.com
go to Live Logging tab

Run tests of the automation

Share the IDE logs with us.  You can also private message us via the ST community site with the logs.  (Do not post your IDE logs on the community as it has your auth tokens in it.)

**Comment by whasf** [comment]
I think I have to let my new community account age? I just created one and I don't see a way to create a new private message..

**Comment by imnotbob** [comment]
You can post here

**Comment by whasf** [comment]
[removed attachment]

Here is the attachment. At 9:35 I closed the door, at 9:44 I opened it. Nothing ever happened.

**Comment by imnotbob** [comment]
In the logs I don't see the contact automation reporting.

I See a motion sensor providing temperature -this is to the remote sensor automation 

There should be in the logs messages conWatCheck.....   which shows the contact automation enabled.

In your automation, I expect you have remote sensor enabled,  but I don't see any messages from the contact automation showing it is enabled.   Go to you automation, and enable the contact automation.

Can you check that, and/or post logs showing the time when you go into Nest Manager SmartApp and hit done (it will show us what is enabled.)

**Comment by whasf** [comment]
[removed attachment]

Attached log.. I deleted the contact automation and re-created it and it works!

**Comment by imnotbob** [comment]
did you install fresh V4 of Nest manager, or did you upgrade from V3?  If you upgraded, all automations needed to be deleted prior to the upgrade from V3 to V4....

**Comment by whasf** [comment]
Nope, I did a minor upgrade last month I think? But in the troubleshooting of all this I have removed and re-installed the program a few times. I don't know. 
I'll go ahead and remove my logs and close this out. Thank you for the help on my issues.
