### ISSUE TITLE
API | Diagnostics | Testing... Broken...

### ISSUE THREAD

**Issue by kpdillon** [tonesto7/nest-manager#393]
1 Nest Protect.  When testing a simulation of smoke, carbon or low battery, message continuously says Skipping... A Test is already Running.... Tested it multiple times, rebooted hub, no change in behavior.

**Comment by kpdillon** [comment]
Had a colleague test on a completely independent device, he reports the same issue.

**Comment by imnotbob** [comment]
After you run a test, you have to disable all the test variables (and hit done to save) to reset the test before you can enable another test.

**Comment by kpdillon** [comment]
Hmmm, I believe I have done that but still cannot clear this message.  When you say disable test variables you mean switch all the simulation switches off save it and gen go back in and switch one on, right?  I've done that and still get the same message.  Happens to my friend who has his own setup too.

**Comment by imnotbob** [comment]
Can you try this version and let me know if it resolves the issue?

https://gist.github.com/imnotbob/d724e7fb4db9a103ccbe2bfbbe876376

**Comment by kpdillon** [comment]
Hi, I tested that version and it does appear to resolve the issue!  Thank you!

**Comment by kevinwestby** [comment]
I get the same error if I do back-to-back tests (even after clearing previous test) or running Smoke, then trying Carbon/Low Battery.  I was able to run one successful test of the Smoke alert....but all subsequent tests are returning the “A test is already running” message.  I am running the code above and even tried killing the ST app and relaunching.....same result.

**Comment by imnotbob** [comment]
It would be good to see screen shots.  You do need to turn off all tests, hit done, then go back to the page and re-enable.

If you are changing devices to test, you should still turn off the test and hit done before changing to a new device.

I looked over the code again, and I cannot pick out an issue.  Tony may be able to test further.

**Comment by imnotbob** [comment]
Update to the latest code in the gist
https://gist.github.com/imnotbob/d724e7fb4db9a103ccbe2bfbbe876376

**Comment by kevinwestby** [comment]
Ok, will give it a try


Kevin Westby, CISSP, CCSP, CIPT
(319) 795-0420
kevin@kevinwestby.com<mailto:kevin@kevinwestby.com>
http://www.westbydigitalmedia.com

Take pictures…in 20 years, you’ll be glad you did.
