### ISSUE TITLE
Is there a way to filter out certain weather advisories?

### ISSUE THREAD

**Issue by cmeans** [tonesto7/nest-manager#395]
There have been a lot of weather advisories of late (I'm in Chicago, so yes, it's cold and the weather can get rough)...I'm generally fine with most of the notifications, but ones for "Small Craft" just aren't useful to me (I don't own a boat, and don't plan on getting on one most of the time) and clutter the notifications up.  It would be nice to have some way to filter out certain notifications, either by category, type or maybe just key words.

**Comment by tonesto7** [comment]
I like the idea.  Let me look into it

**Comment by tonesto7** [comment]
I just wanted to let you know that we haven't forgotten about this.  We are trying to come up with a solution because this is slightly more complex than it appears ;)

**Comment by cmeans** [comment]
OK.  I'll wait patiently :)  Thanks for the update.

**Comment by tonesto7** [comment]
This has been added in to the best of our ability and free time into the weather device preferences of the device handlers.
