### ISSUE TITLE
Nest Cam Error

### ISSUE THREAD

**Issue by Vijaye82** [tonesto7/nest-manager#396]
## Verify the following before opening an issue:
 

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 4
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: iOS
* Mobile App Version: 2.2.3

## Expected Behavior
So usually when i go into the Nest Cam it loads up like a summary page which i can then click to view the feed

## Current Behavior
Now when i go into the summary page i get the following error....

{"error" : true, "true" : "groovy.lang.MissingMethodException" , "message" : "An unexpected error occurred. "}

This error happened before the latest update of nest manager, so i updated and hoped it would it fix it, but i still got the error. 

hope this is an easy fix

**Comment by imnotbob** [comment]
If you can share more logs with us that would be good.

This is in the IDE under "Live Logging".  You should private message them to us in the community forums so as to not publish information too widely...

**Comment by Vijaye82** [comment]
cool thanks will do.... not to seem to dumb but how do i pvt msg on here and to who?

**Comment by tonesto7** [comment]
Thanks for reporting this Vijaye.

I am able to reproduce this error on my end.  I'm investigating right now.  Once i find the cause I will push out a fix

**Comment by Vijaye82** [comment]
thanks tonesto7, love the smartapp and appreciate the work you do.

Anyone thought of a smartapp for netatmo welcome and presense?

**Comment by tonesto7** [comment]
I'm aware of the cause but it may take a couple days to work through a workaround.

**Comment by tonesto7** [comment]
I have this fixed can you please try updating your camera device handler code with this and let me know how it goes after updating? 

https://gist.github.com/tonesto7/e946e4964da059849bf9789fcc9c894b

**Comment by Vijaye82** [comment]
just given it a go now and it seems to be working again... will keep an eye on it and will let you know if any issues... thanks and great job with a quick fix

**Comment by tonesto7** [comment]
Closing this out as v2.4.0 of the camera device has fixed these issues
