### ISSUE TITLE
WIll not log into Nest

### ISSUE THREAD

**Issue by rbramhill1** [tonesto7/nest-manager#399]
I have managed to integrate with github and I have the nest manager showing in the marketplace, I click to go to the log in page and it comes up with NEST page. I enter my details correctly but then I get an error message 
AN ERROR OCCURRED
Connecting to ST-Integration is currently unavailable. Please contact home for more information
I cannot get any further as I am unable to log in
Any advice please

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x} You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: Android
* Mobile App Version: 2.2.2

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
 Get it to work

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
t would be good for you to private message us IDE logs of the issue you are having:  (you may want to send the message via the community forum to avoid it being posted here)

Login into the IDE -> "Live Logging"

Leave that window open

Go to Nest Manager and run your test/experiment/problem

cut and paste the IDE logs to us in a private message.

This will help us have more information on what is going on.

Do double check all the install steps have been followed:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

**Comment by rbramhill1** [comment]
Many thanks for your help. I am very new to github so it is probably my mistake. I cannot see how to send you a private message. Can I post the logs here or is that not recommended?

**Comment by dabdine-r7** [comment]
Experiencing the same issue, same steps as above. The IDE logs don't show anything other than ` ||| Nest Manager | AuthToken not found: Directing to Login Page` for Nest Manager.

**Comment by dabdine** [comment]
Experiencing the same issue. All I see in the ST IDE logs is `||| Nest Manager | AuthToken not found: Directing to Login Page`.

**Comment by rbramhill1** [comment]
‎18‎:‎03‎:‎00: warn ||Nest Manager | Missing: structData null 
‎18‎:‎02‎:‎50: info ||| Nest Manager | AuthToken not found: Directing to Login Page 

Are you also getting the warn marker as well? I have no idea what Missing: structData null 
refers to and I have no idea how to fix it!

**Comment by dabdine** [comment]
Doing a bit of hunting, it seems the developer oauth config used for nest-manager may have met its quota?

http://stackoverflow.com/questions/35696028/nest-auth-an-error-occured-connecting-to-xx-is-currently-unavailable

In other words, there can be no new users of nest-manager unless (1) a request to increase the quota is submitted by nest-manager developers and accepted by Nest/Google or (2) someone revokes their nest access tokens (disables the integration).

**Comment by tonesto7** [comment]
I've made some changes to the token.  Please try reinstalling Nest Manager again

**Comment by rbramhill1** [comment]
Excellent, all working now
On to my next problem the Yale z wave module!

**Comment by leearosner** [comment]
Just installed Nest Manager for the first time. Experiencing same Nest Log on issue from within Smartthings Mobile App.

Any thoughts?

**Comment by imnotbob** [comment]
Lee (sp) - please open another issue, and PM us IDE logs.


It would be good for you to private message us IDE logs of the issue you are having: (you may want to send the message via the community forum to avoid it being posted here)

Login into the IDE -> "Live Logging"

Leave that window open

Go to Nest Manager and run your test/experiment/problem

cut and paste the IDE logs to us in a private message.

This will help us have more information on what is going on.

Do double check all the install steps have been followed:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

**Comment by imnotbob** [comment]
Please do check that your ST location is setup correctly, and that you are using the correct SmartThings shard.

You can check your location in the mobile app:
three horizontal bars at bottom right
Select your location, and the settings gear in upper right
ensure your location is set, and hit done.

ST support can assist you to ensure you are using the right shard, and the location is set correctly.

They won't assist too much on installing Nest Manager - our instructions should help you there as we have several thousand installs.

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

**Comment by teeter02** [comment]
First time installer.  Looks like a really complete Nest Integration.  But I cannot get past OAuth authentication with Nest.  The NM Smartapp is OAuth enabled, and after clicking 'Login to Nest' on the NM Login Page, I do get to the Nest 'Works with Nest' handshake page.  However, upon clicking the gold 'Accept' button there I get the following error:

> An error occurred.  Connecting to ST-Integration-3 is currently unavailable.  Please contact **Home** for more information.

Ran live logging on my SmartThings IDE and nothing came across while doing these actions to be able to report here.  I think Nest is just rejecting the handshake/token.  @tonesto7 - may be that the actions you took to tweak things 8 days ago are still at issue?

Please let me know how I might be able to help diagnose further.

Thanks,

Teeter02

**Comment by teeter02** [comment]
@tonesto7 - Nevermind on the livelogging comment.  Here's what I see now:

> ‎4d2364c6-90b3-440b-b5bf-1a8489222f33 12‎:‎05‎:‎16‎ ‎PM: warn ||Nest Manager | Missing: structData null 
> 4d2364c6-90b3-440b-b5bf-1a8489222f33 ‎12‎:‎04‎:‎50‎ ‎PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page

Hope this helps...

**Comment by tonesto7** [comment]
Sorry we are running out of user token :(
I've switched over to our other token now while I wait for nest to review our code and grant us more users.  

Try running the install again and you should be able to sign in :)

**Comment by leearosner** [comment]
Should I uninstall Nest Manager before reinstalling?

Lee A. Rosner, CCIM SIOR | Managing Principal

Coldwell Banker Commercial Island Corporate Services
1601 Veterans Memorial Highway, Suite 420
Islandia, NY 11749
631-761-6886 Direct Dial | 631-786-0557 M
lrosner@cbcli.com | www.cbcli.com | www.linkedin.com/in/leerosner

**Comment by tonesto7** [comment]
You don't need to uninstall from the IDE just back out and start over again in the mobile app

**Comment by teeter02** [comment]
@tonesto7 - Just tried again and now instead of getting the 'Nest:  Works with Nest' page when you click 'Login to Nest' from NM, now I'm getting:

>>An error occurred.
>>An error occurred while fetching client info

Please advise.

**Comment by tonesto7** [comment]
if you can wait 5 minutes i'm pushing out our next release.  That way you can start with the latest release

**Comment by teeter02** [comment]
@tonesto7 - no problem.  Just give me a heads up when its ready and I'll pull from Git and try again.

**Comment by tonesto7** [comment]
ok v4.4.0 is out.  Just update App and all device handler code

**Comment by leearosner** [comment]
All set.

Thx 

Lee A. Rosner, CCIM SIOR | Managing Principal

Coldwell Banker Commercial Island Corporate Services
1601 Veterans Memorial Highway, Suite 420
Islandia, NY 11749
631-761-6886 Direct Dial | 631-786-0557 M
lrosner@cbcli.com | www.cbcli.com | www.linkedin.com/in/leerosner

**Comment by rbramhill1** [comment]
Okay I got it all working but now I can't get the update working. I mistakenly how to use github etc
Any one help

**Comment by imnotbob** [comment]
Can you say more on what is / is not working?

This is the latest version we put out yesterday, following latest instructions we updated on:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

Can you share IDE logs?

If you believe all this is up to date, we will need to see IDE logs

This is the "live logging" tab when you login to the IDE.  Leave that window open and run your test/failure, then send us the log.  It is good to not post it here, but a private message in the forums (that is more secure, less folks seeing information on your setup)

**Comment by dwuk1** [comment]
11:51:32: warn ||Nest Manager | Missing: structData null
11:51:29: info ||| Nest Manager | AuthToken not found: Directing to Login Page 
@tonesto7  
Hey man, Really appreciate what you've done here.. 
I don't suppose you could tell me if we maxed the token again?..
Sorry for pestering you, but I've hit a wall with this..

**Comment by imnotbob** [comment]
give it a try now

**Comment by dwuk1** [comment]
@imnotbob 

Thank you sir.. you are awesome.
 ;D

**Comment by dwuk1** [comment]
Thanks for all this.... 👍  good stuff!
