### ISSUE TITLE
add alarm capability to nest protect

### ISSUE THREAD

**Issue by citrusmoose** [tonesto7/nest-manager#400]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats? 1
* How many Protects? 1
* Are you Using the Nest Presence Device? no
* iOS or Android?: iOS
* Mobile App Version: 2.2.3

## Expected Behavior

It would be nice if the alarm capability could be added to the Nest Protect device handler.  That way it could double as a siren.  I haven't seen any tickets or references to doing this in the community so I'd thought I'd suggest it.  Sorry if it's a stupid idea.

## Current Behavior

The device handler for the Protect doesn't have the alarm capability.  Maybe for a good reason.

## Context

I don't have a siren now, but I do have the Protect, which is capable of producing a loud sound.

**Comment by imnotbob** [comment]
It is an interesting idea.

Unfortunately Nest does not give us an access to control the sound (no on or off).

I can  understand why they don't as the core of the system is the smoke/co2 detection and alert.

**Comment by tonesto7** [comment]
I'm going to close this as there is not much that can be done at the moment
