### ISSUE TITLE
No Nest Manager app in SmartApps Marketplace

### ISSUE THREAD

**Issue by ghost** [tonesto7/nest-manager#402]
## Verify the following before opening an issue:
- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
0. Yet to install it.

* How many Protects?
2.

* Are you Using the Nest Presence Device?
No.

* iOS or Android?:
iOS

* Mobile App Version:
SmartThings 2.2.3

## Expected Behavior
Expecting a My Apps section to appear. It doesn't, and therefore no Nest Manager.

## Current Behavior
Marketplace>SmartApps displays Social and More as its last two entries. No My Apps appears.

## Context
So, can't install Nest functionality in SmartThings.

Let it be said, I'm sure this is ID10T error. I've missed something. But I don't know what. I've been what I thought was meticulous.

Waah.

**Comment by imnotbob** [comment]
I suspect you did not install properly in the correct SmartThings Shard.

Please review the install instructions at:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

- Particularly ensure you are in the correct Shard, (and your hub is there also), and then closely follow the install instructions.

ST support can assist you in ensuring your in the proper shard and your hub is setup correctly.   They likely will not help too much with Nest Manager, but the instructions above are pretty good, as we have several thousand installs.

**Comment by ghost** [comment]
My shard shows as https://graph.api.smartthings.com/ when entering using http://ide.smartthings.com/. I suspect this was causing issues.

Switching to https://graph-na02-useast1.api.smartthings.com/ manually and starting over seems to have fixed everything.

Thanks for your help!
