### ISSUE TITLE
Unable to add Nest Devices

### ISSUE THREAD

**Issue by bosutton** [tonesto7/nest-manager#405]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS
* Mobile App Version: 

## Current Behavior

Hello, I am trying to install and integrate my new smartthings app and nest manager. I've spent half a dozen hours reading about how to do this, watching videos, and trying desperately to get my Nest to connect to smartthings. I had an issue with getting the "MyApps" section to show up so that I could formally download nest manager. I found that this was because I have a v2 hub and needed to be doing things through this IDE website https://graph-na02-useast1.api.smartthings.com instead of this one  https://graph.api.smartthings.com/. Once I started using the correct smartthings IDE site (the formerof the two aforementioned addresses), I followed the instructions here (http://thingsthataresmart.wiki/index.php?title=Nest_Manager) in order to integrate and install nest manager. Everything downloaded to my phone perfectly and I have the nest manager smartapp in my smartthings app. However, I am unable to see any of the devices in my things. I only have a nest thermostat, so am only really trying to add one thing. I also cross referenced my installation with this video: https://www.youtube.com/watch?v=gcmVSmoGQ7c. I am doing things per the instructions but cannot get any of the devices to show up. Note that when I use my nest login credentials in the initial setup screen of nest manager, it does not recognize any devices. Also, I am unable to go manually add a new device in the smartthings app. Please help. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
Let us know if you are still having problems, with the latest kit (put out yesterday) and updated instructions.

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

If you believe all this is up to date, we will need to see IDE logs

This is the "live logging" tab when you login to the IDE.  Leave that window open and run your test/failure, then send us the log.  It is good to not post it here, but a private message in the forums (that is more secure, less folks seeing information on your setup)

**Comment by tonesto7** [comment]
closing this issue
