### ISSUE TITLE
Nest Cam Issue since update

### ISSUE THREAD

**Issue by Vijaye82** [tonesto7/nest-manager#412]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

About Your Setup:

How many Thermostats?: 0
How many Protects? 4
Are you Using the Nest Presence Device? Yes
iOS or Android?: iOS
Mobile App Version: 2.2.3
Expected Behavior

So usually when i go into the Nest Cam it loads up like a summary page which i can then click to view the feed.

Current Behavior

When i click the play button for the feed it sometimes shows the live feed and then crashes or crashes without loading the feed.

This error happened since the latest update of nest manager, so i deleted everything and reloaded the app and handlers and hoped it would it fix it, but i still got the error.

hope this is an easy fix

**Comment by tonesto7** [comment]
This is a bug with the iOS client.  Sometimes it takes a few times for the stream to work

**Comment by Vijaye82** [comment]
Do you think its something i should raise with smartthing support? And is there anything i should mention when i log it with them so its easier for them to fix?

**Comment by tonesto7** [comment]
The problem is that we are using undocumented which means unsupported features to accomplish the video stream
