### ISSUE TITLE
Issues changing temperature

### ISSUE THREAD

**Issue by simonfunston** [tonesto7/nest-manager#413]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? yes
* iOS or Android?: Android
* Mobile App Version:

## Expected Behavior

When changing from one temp to another I expect the last value to be saved.

## Current Behavior

If I try and change a large number of increments, for example 27 to 22 in 0.5 increments it fails and stays on 27, logs from example:

7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (27.0°C) | Original Temp: (22.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (27.0°C) | Original Temp: (22.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | Time to Target: (120 Minutes) | Original State: (System is Idle)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | Last Nest Check-in was: (Jan 18, 2017 - 10:28:48 PM) | Original State: (Jan 18, 2017 - 10:24:25 PM)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:28:58: info ||| Nest Manager | No Device or Structure poll - Devices Last Updated: 7 seconds ago | Structures Last Updated 7 seconds ago
e9b49ed2-31d8-40ca-821a-986949cbac13  22:28:54: debug Nest Presence Device: Last Parent Refresh time: (Jan 18, 2017 - 10:28:54 PM) | Previous Time: (Jan 18, 2017 - 10:24:36 PM)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:28:51: debug getChildDevices(true), children=3
720798bf-efee-4657-9bcd-619e1d0adb2b  22:28:51: debug Nest Manager | API Device Data HAS Changed
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:50: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (22.0°C) | Original Temp: (22.5°C

## Steps to Reproduce (for bugs)

1. Change temp in multiple increments
2. Wait and observer temp changing back to original value

## Context

Please include a copy of your log under the IDE if possible>>>

Can only change temp in small increments

7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (27.0°C) | Original Temp: (22.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (27.0°C) | Original Temp: (22.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | Time to Target: (120 Minutes) | Original State: (System is Idle)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:59: debug Nest Thermostat - Downstairs: UPDATED | Last Nest Check-in was: (Jan 18, 2017 - 10:28:48 PM) | Original State: (Jan 18, 2017 - 10:24:25 PM)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:28:58: info ||| Nest Manager | No Device or Structure poll - Devices Last Updated: 7 seconds ago | Structures Last Updated 7 seconds ago
e9b49ed2-31d8-40ca-821a-986949cbac13  22:28:54: debug Nest Presence Device: Last Parent Refresh time: (Jan 18, 2017 - 10:28:54 PM) | Previous Time: (Jan 18, 2017 - 10:24:36 PM)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:28:51: debug getChildDevices(true), children=3
720798bf-efee-4657-9bcd-619e1d0adb2b  22:28:51: debug Nest Manager | API Device Data HAS Changed
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:28:50: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (22.0°C) | Original Temp: (22.5°C

**Comment by imnotbob** [comment]
In these logs, I don't see any logs showing Nest Manager sending commands to Nest and the nest response.  I don't know if that is because you did not grab them from the IDE, or the commands were never sent to Nest.   

So it would be good to see more logs if they are available, showing Nest Manager issuing the temp changes to Nest and Nest's response.

**Comment by simonfunston** [comment]
This is a full log of me trying to change from 28 to 21:

It seems to be this line causing the issue:
debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (28.0°C) | Original Temp: (21.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7

e9b49ed2-31d8-40ca-821a-986949cbac13  22:42:25: debug Nest Presence Device: Last Parent Refresh time: (Jan 18, 2017 - 10:42:25 PM) | Previous Time: (Jan 18, 2017 - 10:41:21 PM)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:22: debug getChildDevices(true), children=3
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:21: info ||| Nest Manager | Updating Device Data (Last Updated: 63 seconds ago) (async)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:21: info ||| Nest Manager | Updating Structure Data (Last Updated: 127 seconds ago) (async)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:13: info ||| Nest Manager | nestResponse Processed queue: 0 (devices/thermostats | (target_temperature_c:28.0)) SUCCESSFULLY!
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:12: trace ||Nest Manager | queueProcNestApiCmd Url: https://firebase-apiserver26-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2 | params: [uri:https://firebase-apiserver26-tah01-iad01.dapi.production.nest.com:9553/devices/thermostats/Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2, path:/devices/thermostats/Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2, requestContentType:application/json, headers:[Content-Type:application/json, Authorization:Bearer c.hbsadVfmmfNl7Ub9Ybim2HwKatt2d8A4qezjjwpQHMZlMdzvDjdCCkWRTML9BQJbeF1lIOvApropnGGbUTPTCHC9Y96BjBxvW1KA9NTTcnLwuhyj9ho6rXM7MsPSvN0LhES7x4LDicTsijbJ], body:{"target_temperature_c":28.0}]
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:12: trace ||Nest Manager | queueProcNestApiCmd Url: https://developer-api.nest.com | params: [uri:https://developer-api.nest.com, path:/devices/thermostats/Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2, requestContentType:application/json, headers:[Content-Type:application/json, Authorization:Bearer c.hbsadVfmmfNl7Ub9Ybim2HwKatt2d8A4qezjjwpQHMZlMdzvDjdCCkWRTML9BQJbeF1lIOvApropnGGbUTPTCHC9Y96BjBxvW1KA9NTTcnLwuhyj9ho6rXM7MsPSvN0LhES7x4LDicTsijbJ], body:{"target_temperature_c":28.0}]
720798bf-efee-4657-9bcd-619e1d0adb2b  22:42:12: trace ||Nest Manager | workQueue Run queue: 0 async
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:45: debug Nest Thermostat - Downstairs: UPDATED | Pause Updates is: (false) | Original State: (true)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:41:45: info ||| Nest Manager | schedNextWorkQ schedTime: 27 | queue: 0 | recentSendCmd: 0 | last seconds: 37 | cmdDelay: 4
720798bf-efee-4657-9bcd-619e1d0adb2b  22:41:45: info ||| Nest Manager | Adding to Queue 0: Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2, devices/thermostats, target_temperature_c, 28.0, Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2
720798bf-efee-4657-9bcd-619e1d0adb2b  22:41:45: debug Nest Manager | setTargetTemp: Hcp4is99KXCYg-cfoQVFZFAxor0r-MP2 | (28.0)C | virtual false
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:26: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (28.0°C) | Original Temp: (21.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:26: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (28.0°C) | Original Temp: (21.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:26: debug Nest Thermostat - Downstairs: UPDATED | Last Nest Check-in was: (Jan 18, 2017 - 10:41:10 PM) | Original State: (Jan 18, 2017 - 10:40:09 PM)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (21.0°C) | Original Temp: (21.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (21.0°C) | Original Temp: (21.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 21.0)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (21.5°C) | Original Temp: (22.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (21.5°C) | Original Temp: (22.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 21.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (22.0°C) | Original Temp: (22.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (22.0°C) | Original Temp: (22.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 22.0)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:23: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (22.5°C) | Original Temp: (23.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (22.5°C) | Original Temp: (23.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 22.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (23.0°C) | Original Temp: (23.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (23.0°C) | Original Temp: (23.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 23.0)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (23.5°C) | Original Temp: (24.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (23.5°C) | Original Temp: (24.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 23.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (24.5°C) | Original Temp: (25.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (24.5°C) | Original Temp: (25.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:22: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 24.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (25.0°C) | Original Temp: (25.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (25.0°C) | Original Temp: (25.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 25.0)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (25.5°C) | Original Temp: (26.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (25.5°C) | Original Temp: (26.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 25.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (26.0°C) | Original Temp: (26.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (26.0°C) | Original Temp: (26.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 26.0)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (26.5°C) | Original Temp: (27.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (26.5°C) | Original Temp: (27.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 26.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (26.5°C) | Original Temp: (27.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 26.5)
e9b49ed2-31d8-40ca-821a-986949cbac13  22:41:21: debug Nest Presence Device: Last Parent Refresh time: (Jan 18, 2017 - 10:41:21 PM) | Previous Time: (Jan 18, 2017 - 10:40:17 PM)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (27.0°C) | Original Temp: (27.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (27.0°C) | Original Temp: (27.5°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:21: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 27.0)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:20: debug Nest Thermostat - Downstairs: UPDATED | Heat Setpoint is (27.5°C) | Original Temp: (28.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:20: debug Nest Thermostat - Downstairs: UPDATED | thermostatSetPoint Temperature is (27.5°C) | Original Temp: (28.0°C)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:20: debug Nest Thermostat - Downstairs: Sending changeSetpoint(Temp: 27.5)
7ceb0aff-c864-45fc-96f2-569afc0581b7  22:41:20: debug Nest Thermostat - Downstairs: UPDATED | Pause Updates is: (true) | Original State: (false)
720798bf-efee-4657-9bcd-619e1d0adb2b  22:41:18: debug getChildDevices(true), children=3
720798bf-efee-4657-9bcd-619e1d0adb2b  22:41:18: debug Nest Manager | API Device Data HAS Changed

**Comment by imnotbob** [comment]
So what I see is:

Nest throttling is going on - a lot of commands are being sent in a short time

See:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager#Nest_API_Rate_Limits

I do see at the top (end of the log by time) that the command to set 28 was executed.

So what I think is happening

You are sending a large # of commands, and they just queue up in Nest manager (you see the device saying it received the command and showing results as if the command finished, but the command has not been sent to nest yet due to rate limiting)

Later (1m, 2m ,3m) a command runs, so the depth of the queue has things "really far behind".

Solution: 
A) let the system idle down stop sending commands, and let's let the command flush out...

B)  Once the system "catches up", send commands more slowly

How are you sending the commands - are you in the ST mobile app adjusting the Nest thermostat device?  Or is this another smartapp sending commands?

**Comment by simonfunston** [comment]
I suspected that given it works with one or a small number of commands. The issue is that it is the only way I can change from one temp to another, particularly if I want to turn it off. Going from 21 to 9 would cause 22 commands to be sent which would be throttled and fail. So in reality I want to send one command, change from 21 to 9, I don't actually want to change to anything in between. Two ways to achieve it would be to allow a temp to be typed in or conflate the commands, collect all the commands in 5s and take the last temp as the desired one. 

This is in the ST mobile app, the actions are the same as the Nest app but assume it does just collect the last desired temp. 

Thanks

**Comment by tonesto7** [comment]
it shouldn't take more than one as long as you don't wait more than 2 seconds between each temp change increment.  There is a delay in sending the commands for scenarios like this.   The SmartThings UI is very limiting in how we can make for a better experience

**Comment by imnotbob** [comment]
What version are you running?  Is it the latest?

We do have code to conflate settings near each other, and there is also a slider in the dth to set the number you want as a single setting.

**Comment by simonfunston** [comment]
Yes, the latest version, I installed it for the first time last night. Will try the slider and see if it resolves it.

Thanks

**Comment by jb78** [comment]
I am having a similar issue. The temp change will not stick. Seems to be a recent issue.

**Comment by imnotbob** [comment]
It would be good to see IDE logs.  Please post them as a private message in the community forum to us to protect data security.

**Comment by tonesto7** [comment]
I'm going to close since it's been a month and haven't heard anything further.
