### ISSUE TITLE
Smartapp crashes before launching, temp is blank

### ISSUE THREAD

**Issue by robinogi** [tonesto7/nest-manager#414]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? Y
* iOS or Android?: ios
* Mobile App Version: most current 

## Current Behavior

Temp in smartapp was always showing 15.5 and was not responsive to CoRE programming. I removed all attached SmartApps/routines and uninstalled/reinstalled the app. Now thermostat is found but is blank in the "things" section and crashes the app when I try to open it. 

## Steps to Reproduce (for bugs)

1. Uninstall nestmanager
2. Reinstall nestmanager 
3.authenticate to nest account 
4.configure devices
5. Smartapp thermostat "thing" is present but blank and crashes 

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
what version are you running?   Is it the latest?

Do you have IDE logs to post?

have all instructions from : 
http://thingsthataresmart.wiki/index.php?title=Nest_Manager

been followed?

**Comment by robinogi** [comment]
Yes, I've followed all the steps. I'm running the most current version of the ST app, and version 4.4.2 of nest manager. The live log is below:
101fa4d6-47d7-449f-861b-7d6083aab6fd 10:16:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 56 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:15:04 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 63 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:15:04 PM: info ||| Nest Manager | Updating Structure Data (Last Updated: 123 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:14:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 59 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:13:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 60 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:13:01 PM: info ||| Nest Manager | Updating Structure Data (Last Updated: 177 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:12:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 60 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Thermostat 9ip-6hHEHD27X0a2qbj3T1Axor0r-MP2 (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Weather NestWeather | iR02kb2aDY-ZscNP5VDEMzCb-mnnemW6NDLP7VsSgX3q952XRgFI2w (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Presence NestPres | iR02kb2aDY-ZscNP5VDEMzCb-mnnemW6NDLP7VsSgX3q952XRgFI2w (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:01 PM: debug getChildDevices(true), children=3101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:01 PM: debug Nest Manager | API Device Data HAS Changed101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 57 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:10:48 PM: info ||| Nest Manager | Retrieving Local Weather Conditions101fa4d6-47d7-449f-861b-7d6083aab6fd 10:10:04 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 63 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:10:04 PM: info ||| Nest Manager | Updating Structure Data (Last Updated: 123 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:09:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 60 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:08:01 PM: info ||| Nest Manager | Updating Device Data (Last Updated: 60 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:08:01 PM: info ||| Nest Manager | Updating Structure Data (Last Updated: 176 seconds ago) (async)
When I try to launch the "thing" called "Nest Thermostat", the ST app (ios) crashes before it loads the details. When I try to load the weather app, it says:{"error":true,"type":"groovy.lang.MissingMethodException","message":"An unexpected error occurred."}

When I launch the "Nest Presence Sensor" app, it show the proper status and arrival time. 


Robin




On Sat, Jan 21, 2017 at 8:05 PM -0400, "imnotbob" <notifications@github.com> wrote:












what version are you running?   Is it the latest?


Do you have IDE logs to post?


have all instructions from :

http://thingsthataresmart.wiki/index.php?title=Nest_Manager


been followed?

**Comment by imnotbob** [comment]
It is saying you did not update the device handlers properly.  It is showing 3 out of date.

Please check you followed the instructions, including "publish for me" in the IDE.

||| Nest Manager | Updating Device Data (Last Updated: 60 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Thermostat 9ip-6hHEHD27X0a2qbj3T1Axor0r-MP2 (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest

101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Weather NestWeather | iR02kb2aDY-ZscNP5VDEMzCb-mnnemW6NDLP7VsSgX3q952XRgFI2w (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest

101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Presence NestPres | iR02kb2aDY-ZscNP5VDEMzCb-mnnemW6NDLP7VsSgX3q952XRgFI2w (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest

**Comment by robinogi** [comment]
That was it! Updated the device handlers. Thanks!

Robin




On Sat, Jan 21, 2017 at 10:23 PM -0400, "imnotbob" <notifications@github.com> wrote:












It is saying you did not update the device handlers properly.  It is showing 3 out of date.


Please check you followed the instructions, including "publish for me" in the IDE.


||| Nest Manager | Updating Device Data (Last Updated: 60 seconds ago) (async)101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Thermostat 9ip-6hHEHD27X0a2qbj3T1Axor0r-MP2 (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest


101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Weather NestWeather | iR02kb2aDY-ZscNP5VDEMzCb-mnnemW6NDLP7VsSgX3q952XRgFI2w (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest


101fa4d6-47d7-449f-861b-7d6083aab6fd 10:11:02 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Presence NestPres | iR02kb2aDY-ZscNP5VDEMzCb-mnnemW6NDLP7VsSgX3q952XRgFI2w (v4.2.0) REQUIRED: (v4.4.0) Update the Device to latest

**Comment by robinogi** [comment]
... actually, the Thermostat part is working and the local weather is
partially working.  I put in the Custom Weather Location as [pws:INSLAKES2]
which is the name of my local weather station.  The temp shows as a "thing"
but when I try to go into it I get the same {"error":true,
"type"L"groovy.lang.MissingMethodException","message":"An unexpected error
occured."}

When I go to the "Recently" tab, it looks like it's gathering
precipitation, UV index, city, etc, but it's not displaying on the "Right
Now" section of the smartapp

The live log shows:

61a41a02-13be-4f43-9c5a-5906fefbb914
<https://graph-na02-useast1.api.smartthings.com/ide/logs#61a41a02-13be-4f43-9c5a-5906fefbb914>
 9:43:24 AM: error groovy.lang.MissingMethodException: No signature of
method: physicalgraph.device.DeviceTypeExecutorBase$_closure5.doCall() is
applicable for argument types: (java.lang.String,
java.lang.NullPointerException) values: [getWeatherHTML Exception:,
java.lang.NullPointerException: Cannot invoke method toInteger() on null
object]
Possible solutions: doCall(), doCall(java.lang.Object), call(),
call([Ljava.lang.Object;), call(java.lang.Object), findAll() @ line 1578
61a41a02-13be-4f43-9c5a-5906fefbb914
<https://graph-na02-useast1.api.smartthings.com/ide/logs#61a41a02-13be-4f43-9c5a-5906fefbb914>
 9:43:04 AM: debug Local Weather (WU): checkStateClear...resetting HISTORY
toggle
61a41a02-13be-4f43-9c5a-5906fefbb914
<https://graph-na02-useast1.api.smartthings.com/ide/logs#61a41a02-13be-4f43-9c5a-5906fefbb914>
 9:43:04 AM: debug Local Weather (WU): checkStateClear...resetting ALL
toggle
61a41a02-13be-4f43-9c5a-5906fefbb914
<https://graph-na02-useast1.api.smartthings.com/ide/logs#61a41a02-13be-4f43-9c5a-5906fefbb914>
 9:41:13 AM: error groovy.lang.MissingMethodException: No signature of
method: physicalgraph.device.DeviceTypeExecutorBase$_closure5.doCall() is
applicable for argument types: (java.lang.String,
java.lang.NullPointerException) values: [getWeatherHTML Exception:,
java.lang.NullPointerException: Cannot invoke method toInteger() on null
object]
Possible solutions: doCall(), doCall(java.lang.Object), call(),
call([Ljava.lang.Object;), call(java.lang.Object), findAll() @ line 1578
61a41a02-13be-4f43-9c5a-5906fefbb914
<https://graph-na02-useast1.api.smartthings.com/ide/logs#61a41a02-13be-4f43-9c5a-5906fefbb914>
 9:40:59 AM: error groovy.lang.MissingMethodException: No signature of
method: physicalgraph.device.DeviceTypeExecutorBase$_closure5.doCall() is
applicable for argument types: (java.lang.String,
java.lang.NullPointerException) values: [getWeatherHTML Exception:,
java.lang.NullPointerException: Cannot invoke method toInteger() on null
object]
Possible solutions: doCall(), doCall(java.lang.Object), call(),
call([Ljava.lang.Object;), call(java.lang.Object), findAll() @ line 1578


Robin

**Comment by imnotbob** [comment]
I would try another weather station and see if it works.   I have seen folks connect to a weather station that does not return proper weatherunderground API data.

**Comment by imnotbob** [comment]
That is assuming everything else is up to date

**Comment by tonesto7** [comment]
Is this issue still occurring?

**Comment by robinogi** [comment]
No, issue is resolved. Thanks!



Robin

On April 8, 2017 at 2:08:53 PM, Tonesto7 (notifications@github.com) wrote:

Is this issue still occurring?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonesto7/nest-manager/issues/414#issuecomment-292731699>,
or mute the thread
