### ISSUE TITLE
Fan button not working

### ISSUE THREAD

**Issue by toxsid** [tonesto7/nest-manager#415]
When clicking the "Fan AUTO" button, the button displays "Working" until smartthings is closed and reopened. When checking the smartthings log. I get the following:

Nest Thermostat - Hallway: setThermostatFanMode Received an Invalid Request: fanOn

- OAuth is enabled
- The smartapp is using the latest version 4.4.1
- Device types have been published for me
- One thermostat
- Using nest presence
- iOS
- API status is GOOD

In addtion I have not been able to change temperatures. It seems as though I can update on the app and then it will reset and go back to my original temperatures without changing the thermostat.

Thank you in advance!

**Comment by imnotbob** [comment]
I see the issue and have posted a fix for the next release.

It should be out in next week or so.

**Comment by toxsid** [comment]
Thank you. Looking forward to the update!
