### ISSUE TITLE
getting java security exception error?

### ISSUE THREAD

**Issue by neocody** [tonesto7/nest-manager#417]
Set it up exactly via manual method, after setting up the smartapp I started to get an error when viewing things page of the SmartThings app and this is what was spit out from the live log:

**b7e18f0c-2381-486f-bc54-5eeeeaa071ed 10:09:53 PM: error java.lang.SecurityException: Getting properties on class physicalgraph.app.exception.UnknownDeviceTypeException is not allowed @ line 6053**
b7e18f0c-2381-486f-bc54-5eeeeaa071ed 10:09:53 PM: warn ||Nest Manager | addRemoveDevices Exception | Error: Device Handlers are Missing or Not Published. Please verify all device handlers are present before continuing.
79e8e945-8be6-4b23-9acd-e185663d9fea 10:09:45 PM: info ||| Nest Location Home Watchdog | watchDog scheduled (32 4/30 * ?)
b7e18f0c-2381-486f-bc54-5eeeeaa071ed 10:09:39 PM: debug Nest Manager | Updated with settings: [tempChgWaitVal:4, weathAlertNotif:true, weatherDevice:true, cameras:[C4hINnmdat9m9PqOJRbeIX9v0Kc8x8tE6totmbeYZm5QMaK9K_jD9g, bCZ2HD5BZT6PY7hKEEfHDqPOWEAjVxOML1eWFBBS7S5QMaK9K_jD9g], structures:MbPcAj9YdxC6Lx0n_4qEWW0_6S-JttZxXvvFOFD8i77mrWj6zhIrAA, mobileClientType:ios, optInAppAnalytics:true, optInSendExceptions:true, presDevice:true, thermostats:[Hcp4is99KXAznVBy-JT8BlAxor0r-MP2]]

## Verify the following before opening an issue:
- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? 1
* iOS or Android?: IOS
* Mobile App Version: Nest or ST? 99% Sure it's the latest

## Context

trying to get it to work

Please include a copy of your log under the IDE if possible>>>
¯\_(ツ)_/¯

**Comment by imnotbob** [comment]
See the next line below your bolded line:

b7e18f0c-2381-486f-bc54-5eeeeaa071ed 10:09:53 PM: warn ||Nest Manager | addRemoveDevices Exception | Error: Device Handlers are Missing or Not Published. Please verify all device handlers are present before continuing.


Please review the instructions and ensure you have installed / updated the device handlers and "publish for me"

http://thingsthataresmart.wiki/index.php?title=Nest_Manager
