### ISSUE TITLE
State does not change from Eco mode to set temperature upon presence detection.

### ISSUE THREAD

**Issue by ndmax** [tonesto7/nest-manager#418]
## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: iOS
* Mobile App Version: 2.2.5

## Expected Behavior

Based on current settings: 1) All monitored presence devices (3x iOS devices) leave; 2) After 5min delay, ST triggers "Away"  mode and Nest switches to "Away" presence status and changes from current temperature (e.g. cool 75 deg) to ECO mode; 3) One or more monitored presence devices return; 4) After 5min delay, ST triggers "Home" mode and Nest switches to "Home" presence, out of Eco mode and back to scheduled temperature (e.g. cool 75 deg).

## Current Behavior

1) All monitored presence devices (3x iOS devices) leave; 2) After 5min delay, ST triggers "Away"  mode and Nest switches to "Away" presence status and changes from current temperature (e.g. cool 75 deg) to ECO mode; 3) One or more monitored presence devices return; **4) Nest remains in Eco mode until manually changed via app or physical device.

## Steps to Reproduce (for bugs)

1. Configure Nest Manager's Nest Mode - Nest Home/Away Automation
2. Enable "Set ECO mode when away" in Additional Settings
3. Trigger "Away" in ST, which in turn triggers "Away" Nest presence status and ECO mode.
4. Trigger "Home" in ST. Nest remains in ECO Mode.  Sadness.

## Context

Please include a copy of your log under the IDE if possible>>>

This is probably the single most important automation in our moderately extensive home automation network.  When nobody's home, shut the AC off; when someone comes home, turn it back on.  The configuration has worked well previously (improving on Nest's approach dramatically), but currently does not function as expected.

**Comment by imnotbob** [comment]
It would be good to see IDE logs for these steps, both nest manager, and the dth's associated with it.

These are available by logging into the IDE, and selecting "live logging", then running your tests above with the Live logging window remaining open.  Then share the logs with us.

You should send the logs via a private message in the ST forum, as posting them here are readable by all to see...

**Comment by ndmax** [comment]
Hello Anthony,

I've sent the live logging related to the issue posted on GitHub
<https://github.com/tonesto7/nest-manager/issues/418>.  I hope it is useful
for fixes/development.

Best,
Nathan

**Comment by imnotbob** [comment]
Where are the logs?

**Comment by ndmax** [comment]
I sent them as a private message on the ST community forum ("Live Logging for NM + DTH" from "nmax").
