### ISSUE TITLE
Lost in all the information

### ISSUE THREAD

**Issue by shpankie** [tonesto7/nest-manager#421]
I'm pretty new to all this and trying to get my feet wet.  i am looking to integrate Nest protect to Smartthings hub and i see a ton of information, but to me it looks scattered and i can't make heads and tails.  Is there a location that has is broken down into steps.....more or less?

## About Your Setup:
just one Nest protect and one smartthings hub.  couple of bulbs and stuf, but i don't think it's relevant.

## Expected Behavior
Have Nest protect appeared and posibly push alerts through smartthings hub.

## Current Behavior
no behavior.  can't figure out the setup.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by imnotbob** [comment]
If you have not done so, please read this:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

**Comment by shpankie** [comment]
Thank you.  I found what i was looking for, but now trying to enable github integration and stuck on cloning the https in the stem where i need to authenticate with github from git.  Like i said, i'm a newbie.  Not sure if it is something you can answer or i need to seek answers within github.

**Comment by imnotbob** [comment]
https://community.smartthings.com/t/faq-github-integration-how-to-add-and-update-from-repositories/39046

Should help, and you can ask questions of the community.
