### ISSUE TITLE
Cannot lock thermostat for remote sensor...

### ISSUE THREAD

**Issue by spencerthayer** [tonesto7/nest-manager#422]
I would like to setup a **Thermostat Automation Config** with the **Remote Sensor Automation** for **Use Alternative Temp Sensors Control Zone temperature?** but when I go to click **Remote Sensor Config** I get the following error:

> Cannot lock thermostat for remote sensor – thermostat may already be in use. Please correct.

Any idea why this is? I have only one Nest thermostat and want to use a smartthings multi-sensor as my alternative thermostat.

**Comment by imnotbob** [comment]
What version are you running?

This suggests:
a) you already have a remote sensor created, using the physical thermostat

b) a ST issue that some state was lost.

If you are sure you don't have two automations using the same thermostat (either as the primary thermostat or as a mirror), a way to fix this in 4.5.2 is:

Nest Manager app ->Apps | Device Preferences -> Logging -> Reset Application Data

Ensure you hit done all the way out.   If you find Reset Application Data already on, turn it off, and hit done all the way out, then do it it again to turn it on.

This will not erase your settings, but will re-initialize the automations.

**Comment by spencerthayer** [comment]
*Nest Manager app ->Apps | Device Preferences -> Logging -> Reset Application Data*

Confirmed working! Thank you @imnotbob so much.
