### ISSUE TITLE
Updating Issues from Master

### ISSUE THREAD

**Issue by spencerthayer** [tonesto7/nest-manager#424]
For some reason, my Nest Manager software won't update. I've updated to 4.5.0 using the master branch but it still says I'm at 4.3.0. Is this a common bug? Is there a fix? Or should I uninstall everything and start from scratch.

`12:51:49 PM: error |Nest Manager | NEED SOFTWARE UPDATE: Thermostat jlpzX94f4wce9wWPYP5iuMn7UfMulpEX (v4.3.0) REQUIRED: (v4.5.0) Update the Device to latest`

**Comment by tonesto7** [comment]
http://thingsthataresmart.wiki/index.php?title=Nest_Manager#Installation

This usually happens because the code is being updated on the SmartThings shard.

Use https://ide.smartthings.com and see if the code there is v4.5.x

**Comment by spencerthayer** [comment]
> SmartThings shard

Thank you @tonesto7 for the assist. I'm unfamiliar with this term, what is a "shard?" Is that just a branded name for a server at another location or is like a database shard? If so it's really weird that SmartThings would be fragmenting their database with shards.

**Comment by spencerthayer** [comment]
Yup. That's the problem. I am on `graph-na02-useast1` and Nest is operating on some other database instance. How annoying. Thanks!
