### ISSUE TITLE
HVAC interfering with Nest in Eco Mode.  why?

### ISSUE THREAD

**Issue by ghost** [tonesto7/nest-manager#425]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1 UK version (no AC)
* How many Protects? 2 UK Wired
* Are you Using the Nest Presence Device? yes
* iOS or Android?: Android
* Mobile App Version: v2.2.7

## Expected Behavior
Smarthings uses Nest Manager to set Temp to 14c and away mode 10 minutes after we have left the house for work..  however at about 15:15 last week and today  the heating was back to 20c.
ST Recently log showed the following:

> Nest Thermostat - Hallway.
> Nest HVAC mode is heat mode

and then the nest started heating the house.  We do not have HVAC so why is this being set?  do I have the wrong Device Source Code for my Thermostat?  I removed this code last week thinking it was buggy.  I reinstalled the code a few days ago, and the same thing happened again.

is this code buggy are am i using or setting up the rule incorrectly as I cannot fanthom why ST/Nest Manger thinks I have a HVAC when i dont.

I have had to uninstall the Thermostat source code since it is not operating the way it should. it should not turn on my heating whilst I am away.

**Comment by imnotbob** [comment]
Would need to see IDE "Live Logging" to comment on what is going on.

What automation are you using to adjust the temps and set away?

Are you using Nest's eco mode?  they have deprecated "away" mode for changing temps.  You need to set ECO temps in your thermostats, and have your automation (or Nest Managers's Nest Mode automation) set your home to eco, away when you leave, and return them to normal when you return.

I have not seen anything like you describe across the 4000+ of installs we have.

**Comment by ghost** [comment]
Ok, thanks for the update, I have removed the app for now as I could not stop my nest from turning on the heat when this app was installed and I was not home.  I thought I would mention it in case anyone had a similar issue. it looks like I am the only one, so I will close this issue and just do without.

Thanks for your help.

**Comment by imnotbob** [comment]
Sorry you had problems.   This is not the norm we see.  If you decide to install again and have issues let us know.   I'm sure it could work well for you once we saw what the problem was.

We have seen a lot of reliability with Nest Manager.   Most errors we have worked with folks on have been auth issues, ST state loss, out of date software.
