### ISSUE TITLE
Error: Device Handlers are Missing or not Published.

### ISSUE THREAD

**Issue by picabotwo** [tonesto7/nest-manager#427]
I just installed the APP from scratch for the first time. I was able to authenticate to NEST and it shows my two thermostats. I was able to complete the setup and it said app successfully published. But as soon as that happens I get a notification that states:

Error: Device Handlers are Missing or Not published. Please verify all device handlers are present before continuing. I do not see any listed under my device handlers on the IDE.

Any assistance on a missed step would be appreciated. Thanks!

## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

It shows two devices pending install, but I do not see any option to install them.

## About Your Setup:
* How many Thermostats?: 2
* How many Protects? 0 
* Are you Using the Nest Presence Device? no
* iOS or Android?: Android
* Mobile App Version: Latest (installed today)

**Comment by imnotbob** [comment]
you did review these instructions on installing the app and device handlers:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager

specifically:

http://thingsthataresmart.wiki/index.php?title=Nest_Manager#Installation_Instructions

similar to the Nest manager app, devices have to be installed, saved, publish for me.
