### ISSUE TITLE
App Does not Update

### ISSUE THREAD

**Issue by S-house** [tonesto7/nest-manager#428]
When I open the App, Just get the Circle Doohickey? For the Nest Protect.
  

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
can you share ide logs for this?

**Comment by S-house** [comment]
is this what you are looking for?


Date    Source  Type    Name    Value   User    Displayed Text
2017-04-01 4:14:23.192 PM EDT
moments ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/cc5eeff0-1717-11e7-914d-0ab785873efa?all=&source=&max=25>         DEVICE          lastConnection  Sat Apr 01 16:14:10 EDT 2017            Home - Hallway last connection is Sat Apr 01 16:14:10 EDT 2017
2017-04-01 4:05:23.294 PM EDT
11 minutes ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/8a806880-1716-11e7-998b-12337cd3be70?all=&source=&max=25>      DEVICE          lastConnection  Sat Apr 01 16:02:40 EDT 2017            Home - Hallway last connection is Sat Apr 01 16:02:40 EDT 2017
2017-04-01 4:02:23.172 PM EDT
14 minutes ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/1f38b960-1716-11e7-9b9d-12f3193f5286?all=&source=&max=25>      DEVICE          lastConnection  Sat Apr 01 15:59:34 EDT 2017            Home - Hallway last connection is Sat Apr 01 15:59:34 EDT 2017
2017-04-01 3:32:29.199 PM EDT
44 minutes ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/f1ea8190-1711-11e7-9b51-0ac23ae6dd16?all=&source=&max=25>      DEVICE          lastConnection  Sat Apr 01 15:29:34 EDT 2017            Home - Hallway last connection is Sat Apr 01 15:29:34 EDT 2017
2017-04-01 3:14:24.183 PM EDT
1 hour ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/6b3d0980-170f-11e7-a5fc-061a4231ca10?all=&source=&max=25>  DEVICE          lastConnection  Sat Apr 01 15:12:36 EDT 2017            Home - Hallway last connection is Sat Apr 01 15:12:36 EDT 2017
2017-04-01 3:02:25.198 PM EDT
1 hour ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/be402ce0-170d-11e7-9d71-12d86ddbc8c0?all=&source=&max=25>  DEVICE          lastConnection  Sat Apr 01 14:59:33 EDT 2017            Home - Hallway last connection is Sat Apr 01 14:59:33 EDT 2017
2017-04-01 2:32:25.169 PM EDT
2 hours ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/8dcd5c80-1709-11e7-b3b2-0a61d28558dc?all=&source=&max=25>         DEVICE          lastConnection  Sat Apr 01 14:32:00 EDT 2017            Home - Hallway last connection is Sat Apr 01 14:32:00 EDT 2017
2017-04-01 2:29:23.181 PM EDT
2 hours ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/2145b350-1709-11e7-9d71-12d86ddbc8c0?all=&source=&max=25>         DEVICE          lastConnection  Sat Apr 01 14:27:32 EDT 2017            Home - Hallway last connection is Sat Apr 01 14:27:32 EDT 2017
2017-04-01 2:17:32.212 PM EDT
2 hours ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/798ea190-1707-11e7-9aac-0a5a6e9ec968?all=&source=&max=25>         DEVICE          lastConnection  Sat Apr 01 14:16:27 EDT 2017            Home - Hallway last connection is Sat Apr 01 14:16:27 EDT 2017
2017-04-01 2:02:25.190 PM EDT
2 hours ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/5ce471c1-1705-11e7-8447-0a8d6948c7b4?all=&source=&max=25>         DEVICE          lastConnection  Sat Apr 01 14:01:32 EDT 2017            Home - Hallway last connection is Sat Apr 01 14:01:32 EDT 2017
2017-04-01 1:53:23.183 PM EDT
2 hours ago <https://graph-na02-useast1.api.smartthings.com/device/7e8697ee-05a3-4d5d-be60-7d2bfadad467/event/19e1dcb0-1704-11e7-9581-12c0e0d0712e?all=&source=&max=25>         DEVICE          lastConnection  Sat Apr 01 13:50:36 EDT 2017            Home - Hallway last connection is Sat Apr 01



________________________________

**Comment by imnotbob** [comment]
yes, but a longer time.  I see no errors in this short list.

I suggest you share this via private message in the ST Community forums, as posting here is for all to read.
