### ISSUE TITLE
Multiple Instances of "NST Automations"

### ISSUE THREAD

**Issue by Fresh1179** [tonesto7/nest-manager#432]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [ x] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats? 1:
* How many Protects? 3
* Are you Using the Nest Presence Device?No
* iOS or Android?: iOS
* Mobile App Version:

## Expected Behavior

I followed the steps to update to the latest version of NST Manager.  I used the IDE and Github to download NST Automations.  I updated the device handlers to the latest versions and published all.  Oauth is enabled for NST Manager and NST Automations.  Under my "SmartApps" in the ios app, I have two seperate "NST Automations" tiles.  When I click on either of them i get a spinning action wheel and nothing occurs.  The thermostat device, and three nest protect devices appear to be working correctly but I am not quite sure if this is a failed install of NST Automation or what the expected behavior should be.  I upgraded from version 4.52.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by Fresh1179** [comment]
Figured it out.  Please ignore.  Works Well.

**Comment by rrkraft** [comment]
What did you do to fix it? I have the same issue and cannot get rid of them.
