### ISSUE TITLE
Warning Nest Thermostat Offline

### ISSUE THREAD

**Issue by rbiffle** [tonesto7/nest-manager#433]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 3
* How many Protects? 0
* Are you Using the Nest Presence Device? Yes
* iOS or Android?:iOS 
* Mobile App Version: latest

## Expected Behavior
 not receive warning about nest thermostats being offline.  

## Current Behavior
 receive a ST message warning me that the nest thermostats are offline.  When I check them them are actually online.  Only occurs after the update to 5.0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
 

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
Are you positive you are running the latest version of all of the code?

**Comment by rbiffle** [comment]
I believe the fix you instructed us to perform yesterday resolved the issue.  I followed your instructions yesterday around 5 pm and have not received the warning message since.  

Thank you for all your hard work and responsiveness!

**Comment by tonesto7** [comment]
Glad to hear it.  Thanks for the update
