### ISSUE TITLE
Adding Remote Sensor Automation Error

### ISSUE THREAD

**Issue by compmas2** [tonesto7/nest-manager#435]
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects?:  3
* Are you Using the Nest Presence Device?:  Yes
* iOS or Android?:  Android
* Mobile App Version:  

## Expected Behavior
I click to enable a Remote Sensor under Automations.  Once I have filled in the Rule Action Type, Default Temp Sensors, Desired Temps, Action Threshold Temp, and Change Temp Increments, I should be able to click Done and have the settings take and go back to the main Automation modification screen.

## Current Behavior
When I go to click Done after entering items in the fields list above, I get the following error message and can't exit the Remote Sensor Automation screen:
Please check the value range of input fields.
I have checked the input ranges and they are all with in range or are using the default values.
If I just press the back button it appears to save my settings, but it created a bad NST Automation that throws an error when you open it in the settings.

## Steps to Reproduce (for bugs)
1. Go to Create NST Automation
2. Select Thermostat Automations
3. Select a Thermostat
4. Select/Enable Use Alternate Temp Sensors Control Zone temperature.
5. Click on Remote Sensor Config
6. Set the Rule Action Type to Auto
7. Select the Default Temp Sensors (I choose 4 different sensors, one of them being the Nest Thermostat)
8. Set the Desired Default Temps.
9. Click Done
10. The error "Please check the value range of input fields" appears
11. Since I was stuck in the screen I pressed the back button
12. This created a "NST Automation" under the Automations section, but when I click on it to view it I get another error.
13. Pressing back at this point seems to automatically remove the NST Automation I just checked that gave the error.

**Comment by tonesto7** [comment]
I'm not near my computer this weekend but will try and see if I can duplicate this.

**Comment by tonesto7** [comment]
I'm not able to duplicate this on iOS client, but can on the Android.  I've tried modify the code, but nothing works.
It's a bug with the android client and decimal inputs using a range. 

https://community.smartthings.com/t/decimal-input-s/64260/5

I'm not sure why you are seeing an automation installed that is corrupted.

**Comment by compmas2** [comment]
I tried adding the Remote Sensor Automation with my logs enabled and made sure each number did not contain a decimal and that seemed to work.  I still get an error if I don't toggle the Debug option on and off on the last confirmation screen, but after doing that I was able to add the automation successfully

**Comment by tonesto7** [comment]
I trying to find where the blank automation is being created.  This shouldn't be possible.
