### ISSUE TITLE
Adding Nest Mode Automation Error

### ISSUE THREAD

**Issue by compmas2** [tonesto7/nest-manager#436]
## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects?: 3
* Are you Using the Nest Presence Device?: Yes
* iOS or Android?: Android
* Mobile App Version: 2.3.1 Build 211001

## Expected Behavior

I should be able to click the Done button after configuring a Nest Mode Automation and have it added without error.

## Current Behavior

When I add a Nest Mode Automation and configure the settings, I get an error when clicking the final Done button to add the automation.  The only way to successfully get out of this screen is to enable Debug and then I disable Debug.  Then the Done button works without any issues.

## Steps to Reproduce (for bugs)

1. Click to Create New Automation (NST)
2. Click Nest Mode Automations
3. Select the modes for Home and Away
4. Enabled Set ECO mode when away.
5. Click Done
6. Under the Automation Configuration screen click Done again, which results in the error message:  "Please fill out all required fields.
7. If I enable and disable the Debug Option and then click Done, then it successfully adds the automation.

## Context

I am unable to add a Nest Mode Automation without having to do the workaround of enabling and disabling Debug Option.

**Comment by tonesto7** [comment]
Does it generate an exception in the ide logs?

Out of curiosity are you using android client?
I'm not around my computer this weekend but if I can get an idea where to look i can repair it on my phone and push out the fix.

**Comment by tonesto7** [comment]
Nvm which client. I'm viewing from my phone and missed the client you entered above
