### ISSUE TITLE
How to delete NST-Manager SmartApp

### ISSUE THREAD

**Issue by rrkraft** [tonesto7/nest-manager#439]
My Nest Thermostat stopped working. I read somewhere to delete everything and start it again which I tried. But now I still have 3 NST-Automations SmartApps and I cannot delete them. How can I do this so that I can start from scratch and get the application back?

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? 1
* iOS or Android?: iOS
* Mobile App Version: Newest

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by compmas2** [comment]
If the NST Automations show up under your SmartApps separate of NST Manager, then you are getting empty NST Automations like I was which throw an error when you try to open them.

If this is the case then you can remove the NST Automations forcefully through the IDE interface.  In the IDE, go to My Locations -> [Location Name] -> List SmartApps -> Edit (towards the top right).  Then click remove on all the NST Automations.

After this you should be able to go into the NST Manager and select to "Uninstall this App".  If it still doesn't work then you must be using one of the NST Manager device handlers in a routine.

**Comment by tonesto7** [comment]
Thanks @compass2.  
I'm flying solo this week support wise and works been taking most of my extra time.

**Comment by rrkraft** [comment]
The thing is that I deleted all device handlers and the Nest Application. Yet, I still couldn't delete these NST-Automation SmartApps. The system told me that they're used but I couldn't find where. As said, there was no Nest Manager anymore and I didn't use them in any other automation (which are totally unrelated to my thermostat)

I was able to delete them all out of the IDE (Except of the nst-automation device handler), and install and publish them back into my IDE and then into the mobile app. Everything works now but I still have 6 or 7 NST-automations in the smart-apps tab.

Another observation is that the device health checks seem to interfere with your application. When I turn that on the nest thermostat or the nest cam will be marked unavailable and are not usable anymore. I de-installed it due to these issues but when it broke again I remembered a post mentioned the device health and to turn it off.

**Comment by tonesto7** [comment]
You didn't need to delete the devices and smartapps from the IDE.
In the IDE goto My Locations > SmartApps > click the edit button below the banner ( Be very careful not to click the wrong app as it won't ask if your sure you want to uninstall) > Click the red Uninstall on each NST automation instance you want to remove.

**Comment by rrkraft** [comment]
Ah. I didn't know this yet. Should I leave one in there or should I delete all of them?

**Comment by tonesto7** [comment]
If your NST is installed and the only one there is the watchdog then you can leave it.

**Comment by rrkraft** [comment]
I'm not sure I understand. I have 4 automations configured within nest-manager. Watchdog is one of them. 

Right now my SmartApps pages shows
CoRE
NST Automations
NST Manager

So me deleting all but one NST Automations in the IDE fixed the multiple entries. But I think you mentioned above that these NST Automations get created if some error during adding the NST manager occurs.

I also think it was Nest Manager before and now it's called NST Manager.

**Comment by agrieco** [comment]
I'm having a similar problem deleting.  Going to locations->smartapps helped for the watchdog app, but when I go to delete the "Nest Manager" SmartApp- I get "There was an error uninstalling your SmartApp."  the same is true when I try to uninstall it from the mobile client (iOS)

Any pointers?

**Comment by tonesto7** [comment]
Are you running the latest code and devices?
This sounds like corrupted state.

**Comment by agrieco** [comment]
Yes-SmartApps show no updates available. 

I've just gone through and deleted all the Nest devices and now it appears to have magically disappeared.  Very weird- I had upgrade for the first time in a long time this weekend and it went to this state.  

Not sure how to reproduce- but just so you know.

thanks

**Comment by tonesto7** [comment]
yea some of the data must have been corrupted on ST.
Did you re-install?  If yes is it working good now?

**Comment by agrieco** [comment]
Working just fine so far.  thanks for checking.

**Comment by LevinusHaines** [comment]
Sorry Tonesto7, but this app is a plague on SmartThings.  I was never able to get it working correctly, and it spewed out errors for months.  I finally go in to delete it and it clings on like some sort of disease.  I've tried every method.  I'm having to systematically overhaul my hub because of this.  Thanks!

It insists there are updates.  I click on update to go from 5.2 to 5.2.3.  I log into the IDE and hit update.  It gives me a happy little "Updated SmartApp".  Then...no change.  It still insists I'm on version 5.2.  I could really care less what version I'm on, because none of them worked.  None of the uninstall methods mentioned here were effective.

I've gone through the app and left it blank.  I've deleted ALL routines and other smartapps (which took me ages to do...).  I've tried going under Locations - SmartApps - Edit and Uninstalling.  I've tried re-registering my hub.  Nothing.  Somehow, Tonesto7 has figured out how to permanently infect a hub.  I've written an e-mail to support to see if they can do it on their end.

**Comment by tonesto7** [comment]
v5.2.3 has a fix to help with removing it.

**Comment by LevinusHaines** [comment]
But I can't update it!

**Comment by cpmorris1001** [comment]
@LevinusHaines I’m in the same boat.  I need some help.  Were you ever able to remove this?  I hope yes and then the question is how?
