### ISSUE TITLE
Remote Sensor and custom names

### ISSUE THREAD

**Issue by rrkraft** [tonesto7/nest-manager#440]
A few observations: 
When using remote sensor the Nest heat setpoint seems to be set incorrectly. 
I also cannot rename devices. There's a Null word in it and I can change only what is after null but it shows the whole string in ST.

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? 1
* iOS or Android?: iOS
* Mobile App Version: 5.0.3

## Expected Behavior

I have a temperature sensor in a kind of cold room and created a virtual thermostat using this sensor and the Nest temperature sensor using Remote Sensors. I have a schedule which uses this virtual sensor to set the temperature at night but I used the normal Nest thermostat during the day. Both heat set points are set to 68 degrees (day and night). Yet when it changed the schedule this morning it set the virtual thermostat to 68 but the real Nest device to 64. Yesterday it was 68 and 66. The temperature in the house was 69 (Nest and room sensor). So I cannot see why it set it to 64. I know it has to set my Nest to other temperatures to change the temperature in the other room where the remote sensor is. But 64 makes no sense at all. I would expected a higher temperature if the remote room is below 66.

Another observation is custom names. When I changed them it put the old name followed by null and then the new name. Whenever I change it now it will change the part after null but not the part before it. But the ST Home page shows the part before null. 

And then I have the issue with deleting NST-automation SmartApps. But I have a different issue open for this.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
Remote sensor is odd one...  It actually sets the temperatures with an offset +-/5 degrees by default to make sure to prevent rapid cycling of the HVAC.  
This is @imnotbob design.

As far as the names i'm working in the automation code now so will investigate this.  

Thank you for reporting all of these issues.

**Comment by tonesto7** [comment]
I can't duplicate the issue you are seeing with the label.  Can you send me a screenshot?

**Comment by rrkraft** [comment]
Can I send you the images privately? I don't want to post them here so that everyone can see them. I'm a bit privacy sensitive .... I don't know what someone could do with the names of my automations but I'm also not a hacker ...

**Comment by rrkraft** [comment]
So I don't really get the remote sensor thing. If it sets the temperature to 64 degrees on the real thermostat how would it heat the house if the temperature would fall below 68 (the value on the virtual thermostat)? Does it monitor the temperature in ST and change the temperature when it things my heat should come on?

**Comment by imnotbob** [comment]
It does adjust the temps to turn on / off the thermostat.

See: http://thingsthataresmart.wiki/index.php?title=NST_Manager#Remote_Sensor
