### ISSUE TITLE
While everything is working right now, it freaks me out that a) When I open NST Automations it gives me a something is wrong! message and b) I can't de-install it.. not even via the 'location button route' it is gone there.. but not on the online API and the smart apps listing (had three before..)

### ISSUE THREAD

**Issue by LeisureL** [tonesto7/nest-manager#450]
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
Can you post IDE logs as private message in the community forum to us?

What version are you running?
