### ISSUE TITLE
Camera Unavailable

### ISSUE THREAD

**Issue by jjbarker1965** [tonesto7/nest-manager#451]
I just installed Smartthings and Nest Manager 5.0
I can see both of my nest camera's but when trying to view the streaming video, it give the error message "Camera Unavailable"
I can turn streaming on / off on the camera and do a snapshot no problem...but as soon as I try and connect to the camera to view the video, I get the error message.
I can view the video stream in the Nest app.
Does anyone have and ideas ?
Thanks

**Comment by imnotbob** [comment]
Ensure the camera is setup for public access.

See:

http://thingsthataresmart.wiki/index.php?title=NST_Manager

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Nest_Camera

**Comment by jjbarker1965** [comment]
Thanks you very much, I don't know how I missed that during my install.
Appreciate the help
