### ISSUE TITLE
Nest is offline notification constantly triggering 

### ISSUE THREAD

**Issue by rebootsramblings** [tonesto7/nest-manager#452]
## Verify the following before opening an issue:

- [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Expected Behavior

Since Updating to 5.0.9 including device handler, I have been getting a constant Repeating notification saying my nest is offline

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
Check the IDE logs.

also, go into the devices in question in the Smartthings mobile app, hit settings (gear in upper right), then hit done.

If this does not resolve it, please post IDE logs after trying to above
