### ISSUE TITLE
Nest Thermostat not following NST Automations

### ISSUE THREAD

**Issue by jraldama** [tonesto7/nest-manager#453]
Since last version was installed the NST Automations have ceased to work.
I can see on the Event List that Nest Thermostat was sent an APP_COMMAND 'setCoolingSetpoint' but there actual nest tunit does not change the set point so HVAC does not trigger.

## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X ] The SmartApp and Device are using the latest version.
- [X ] You have reviewed the Readme for potential fixes.
- [ X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 3
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:IOS 10
* Mobile App Version:

## Expected Behavior
The nest thermostat should receive the new set point and trigger HVAC

## Current Behavior
Nothing happens

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
Can you provide IDE logs?  It would best to do this as a private message in the community forums to avoid public sharing of your information.

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Troubleshooting

**Comment by jraldama** [comment]
Whats the best way to get the IDE logs? This is what I see on screen

 

 

For the thermostat:

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#0b6e855d-bba6-4966-b31b-1e4dbc212d63> 0b6e855d-bba6-4966-b31b-1e4dbc212d63 9:57:36 AM: debug Nest Thermostat - 2nd Floor (Hallway): UPDATED | Device Changes Made by (remSen: Set Nest Thermostat - 2nd Floor (Hallway) Cool Setpoint 70.0) at (May 19, 2017 - 9:57:35 AM)

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#0b6e855d-bba6-4966-b31b-1e4dbc212d63> 0b6e855d-bba6-4966-b31b-1e4dbc212d63 9:56:36 AM: debug Nest Thermostat - 2nd Floor (Hallway): UPDATED | Device Changes Made by (remSen: Set Nest Thermostat - 2nd Floor (Hallway) Cool Setpoint 70.0) at (May 19, 2017 - 9:56:36 AM)

 

 

On the automations

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:58:39 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | setTstatAutoTemps() | Setting tstat [Nest Thermostat - 2nd Floor (Hallway) | mode: (cool) | coolSetpoint: (70.0) °F ]

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:58:35 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | setTstatAutoTemps: [tstat: Nest Thermostat - 2nd Floor (Hallway) | Mode: cool | coolSetpoint: 70.0°F | heatSetpoint: null°F]

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:58:35 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | Remote Sensor: COOL - Adjusting CoolSetpoint to Turn On Thermostat

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:58:35 AM: trace | Nest Automations (2nd Floor Thermostat) (NST) | Remote Sensor: COOL - (Sensor Temp: 79.5 - CoolSetpoint: 77.0)

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:57:40 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | setTstatAutoTemps() | Setting tstat [Nest Thermostat - 2nd Floor (Hallway) | mode: (cool) | coolSetpoint: (70.0) °F ]

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:57:35 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | setTstatAutoTemps: [tstat: Nest Thermostat - 2nd Floor (Hallway) | Mode: cool | coolSetpoint: 70.0°F | heatSetpoint: null°F]

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:57:35 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | Remote Sensor: COOL - Adjusting CoolSetpoint to Turn On Thermostat

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:57:35 AM: trace | Nest Automations (2nd Floor Thermostat) (NST) | Remote Sensor: COOL - (Sensor Temp: 79.5 - CoolSetpoint: 77.0)

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:56:40 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | setTstatAutoTemps() | Setting tstat [Nest Thermostat - 2nd Floor (Hallway) | mode: (cool) | coolSetpoint: (70.0) °F ]

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:56:35 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | setTstatAutoTemps: [tstat: Nest Thermostat - 2nd Floor (Hallway) | Mode: cool | coolSetpoint: 70.0°F | heatSetpoint: null°F]

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:56:35 AM: info ||| Nest Automations (2nd Floor Thermostat) (NST) | Remote Sensor: COOL - Adjusting CoolSetpoint to Turn On Thermostat

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4> 899f9d5c-e4b3-43b1-bb0a-f6c3159ad1b4 9:56:35 AM: trace | Nest Automations (2nd Floor Thermostat) (NST) | Remote Sensor: COOL - (Sensor Temp: 79.5 - CoolSetpoint: 77.0)

 

 

On Nst manager

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#b826495e-918f-48df-9f20-f9e3c2e911aa> b826495e-918f-48df-9f20-f9e3c2e911aa 9:58:35 AM: warn || NST Manager | updateChildData() Device ydV6sYINctVtrVzMFMn96UqJ6a_76jyZ unclaimed

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#b826495e-918f-48df-9f20-f9e3c2e911aa> b826495e-918f-48df-9f20-f9e3c2e911aa 9:58:35 AM: warn || NST Manager | updateChildData() Device v4qTgaPbSJK90NjY7JvgOPOCwKMGf6xFJWqgPnbpPzVKiemv--o8mQ unclaimed

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#b826495e-918f-48df-9f20-f9e3c2e911aa> b826495e-918f-48df-9f20-f9e3c2e911aa 9:58:35 AM: warn || NST Manager | updateChildData() Device ydV6sYINctVHA1JluXqQJEqJ6a_76jyZ unclaimed

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#b826495e-918f-48df-9f20-f9e3c2e911aa> b826495e-918f-48df-9f20-f9e3c2e911aa 9:58:35 AM: warn || NST Manager | updateChildData() Device ydV6sYINctUaYJNrB06JVUqJ6a_76jyZ unclaimed

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#b826495e-918f-48df-9f20-f9e3c2e911aa> b826495e-918f-48df-9f20-f9e3c2e911aa 9:58:33 AM: info ||| NST Manager | API Device Data HAS Changed

 <https://graph-na02-useast1.api.smartthings.com/ide/logs#b826495e-918f-48df-9f20-f9e3c2e911aa> b826495e-918f-48df-9f20-f9e3c2e911aa 9:58:32 AM: info ||| NST Manager | Updating Structure Data (Last Updated: 179 seconds ago) | Updating Device Data (Last Updated: 179 seconds ago) (async)

**Comment by imnotbob** [comment]
It would be good to move this to a private message in the community forums.

Do you know how to send private messages there?   Everything post here is "very public".

Looking at the logs, something is up with your devices.   You may want to send in a private message
screen shot of 

In IDE -> My Location -> your location -> List SmartApps

scroll down to Nest Manager (Or NST manager), and send the screen shot.    

Then in IDE:
 My Devices 

Sort by Type (may have to wait a minute for sort control to show up), then scroll so all the Nest devices are visible, and take a screen shot.

Again, I suggest all this move to private messages in the forum for privacy.
