### ISSUE TITLE
Oops! We Encountered an error.  Please try again.

### ISSUE THREAD

**Issue by eLKab0ng** [tonesto7/nest-manager#454]
I've been having all sorts of ongoing issues with the NST Manager that peaked last night with the Nest no longer receiving automation requests (Night time temp changes, etc) and culminated this morning when it was indicating improper temperatures/humidity and was unresponsive to commands to change temp manually.  I did my best diagnosing, I deleted the offending device, and then ultimately delete and reinstalled the entire NST Manager.  Now, I'm stuck trying to log back in to Nest, and once I get to "Accept", I'm stuck in an endless loop of "Oops..." or "We can't reach Nest.com right now. Try again later."  Since there is no error logging for an app that hasn't been installed, I can't really tell what's going on.

## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 1
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS 10
* Mobile App Version: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
Can you give it a try again?  I made some changes on our end.

**Comment by eLKab0ng** [comment]
Looks like we're in Monkey Business.  Thanks for the help!

**Comment by nrmurel** [comment]
I am having a similar issue, I just keep getting "Oops..." or "We can't reach Nest.com right now. Try again later." when I hit accept.

**Comment by marshalk86** [comment]
Same issue here. Any updates?

**Comment by imnotbob** [comment]
try again - I made a change

**Comment by marshalk86** [comment]
I Force Stopped the Android App and restarted it. Tried again, and I get the same error. However, I get the error on a new page, that I haven't seen before. This page appears before it gives me the option to press Accept (after entering my Nest username and password).

Do I need to reinstall the SmartApps on the IDE website?

**Comment by marshalk86** [comment]
I tried again and got it to work.
Thanks!
