### ISSUE TITLE
Unable to override default Nest Weather location

### ISSUE THREAD

**Issue by DonMcKee** [tonesto7/nest-manager#455]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: Android
* Mobile App Version:

## Expected Behavior

Nest Weather should honor customized weather location.
## Current Behavior

Nest Weather continues to use the "default" location.  Log indicates "custLocStr:pws:KCASANJO164" and "useCustWeatherLoc:true", yet info is coming from station KCASANJO375 (see screenshot).   I tried specifying location by zip code (even using one in another state), but continued to get info from the same station.  I tried specifying the station or zip between "[ ]", with no change in behavior.

## Steps to Reproduce (for bugs)

1. NST Manager/Modify devices/Device Customization/Customize Weather Location
2. Use  Custom Location ON
3. Manually Set Weather Location
4. "Done" your way out

## Context

Temperature from reported location is as much as 5 degrees warmer than my actual location.

Please include a copy of your log under the IDE if possible>>>

6:56:56 PM: debug NST Manager | NST Manager Updated...with settings: [appDebug:false, pollValue:180, custLocStr:pws:KCASANJO164, tempChgWaitVal:4, thermostats:[gUpeEUao25-kT5cw2h_hFUqJ6a_76jyZ], disAppIcons:false, optInSendExceptions:true, pollWaitVal:10, mobileClientType:android, presDevice:true, devNameOverride:true, weatherShowGraph:true, resetAllData:false, pollStrValue:180, weatherDevice:true, protects:[ceHN2fyGl3WrninrDn9HBEqJ6a_76jyZ, ceHN2fyGl3XAdFlyzwkZs0qJ6a_76jyZ], childDebug:true, pollWeatherValue:60, tstatShowHistoryGraph:true, useCustWeatherLoc:true, debugAppendAppName:true, weathAlertNotif:true, custWeatherLocSrch:false, structures:N_SXYf0ZQFYDSzBuRuj47kzS4i2mGk2Vdl1jDUxQIV2stfj0wmaXNA, showProtActEvts:true, useMilitaryTime:false, optInAppAnalytics:true]
![2017-05-27 02 07 01](https://cloud.githubusercontent.com/assets/24657954/26517121/152c22c0-4247-11e7-9019-e38b64fb9a6a.png)

**Comment by imnotbob** [comment]
thx for the report (and sorry for the trouble)

I see the issue, and have submitted a fix for it.

Tony will be releasing the kit.

**Comment by imnotbob** [comment]
This should be fixed in 5.1 release

**Comment by DonMcKee** [comment]
Sorry for the delayed follow-up.  I'm not seeing any difference in behavior (currently running the 5.1.4 version of Nest Manager).  If "Use Custom Location" is "on", and "Use semi-automated search" is "off", anything I set in "Manually Set Weather Location?" is ignored, and the "Weather Location" reverts to "Hub Location (95120)".

Since the semi-automated search _does_ work, but doesn't give me the station that I want, I added the entry that I wanted to the search results just to see if it would work:

```
def getWeatherQueryResults(query) {
	LogTrace("Getting Weather Query Results for '$query'")
	def objMap = [:]
	if(query) {
		def params = [uri: "http://autocomplete.wunderground.com/aq?query=${query.toString().encodeAsURL()}", contentType:"application/json", requestContentType:"application/json"]
		def data = getWebData(params, "weather location query", false)
		data?.RESULTS?.each { res ->
			log.debug "item: ${res?.name} | Zip: ${res?.zmw}"
			objMap[["zmw:${res?.zmw}"].join('.')] = res?.name.toString()
		}
                objMap["pws:KCASANJO164"] = "KCASANJO164, Blossom Hill and Camden, San Jose, CA, US"
	}
	return objMap
}
```

It did!  I was able to select my entry from the list, and it was used as expected.  So, the downstream code is working for the "pws" station, if I can get it configured in the first place. :wink:

**Comment by imnotbob** [comment]
If you want to fill in a specific station, you disable "Use semi-automated search?"

then it will offer you to manually enter a station, which you would do with pws:stationID

**Comment by DonMcKee** [comment]
> If you want to fill in a specific station, you
> disable "Use semi-automated search?" ....

Right, that's what I try to do, but it doesn't "take".  If I disable "Use semi-automated search?", and manually enter anything, I always get "Hub Location (95120)".  As a work-around (because I don't understand the code :wink:), I forced the station I wanted into the search results list, and picked it from there.

-Don

**Comment by imnotbob** [comment]
I have put in an update to correct this.  Will be in next release tony pushes out.

**Comment by rogermommaerts** [comment]
HI, Can you tell me how this was corrected? How can I select a specific weather station? Thanks.
