### ISSUE TITLE
"Operating" Graph No Longer Shows Events on Event History Graph

### ISSUE THREAD

**Issue by citrusmoose** [tonesto7/nest-manager#457]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 1
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS
* Mobile App Version: 2.3.6

## Expected Behavior

I should see plot points on the yellow "Operating" graph on the Event History graph.

## Current Behavior

The yellow "Operating" graph appears flat, even though the system has been operating.

## Steps to Reproduce (for bugs)

1. Notice the system running
2. View Event History graph
3. Notice other graph lines change accordingly
4. Notice "operating" graph not change

**Comment by tonesto7** [comment]
Thanks for pointing this out.  I'm seeing the same on my instance.  I will investigate and get a fix out

**Comment by imnotbob** [comment]
This is fixed in 5.1 release
