### ISSUE TITLE
Interface Issues on the Thermostat Device

### ISSUE THREAD

**Issue by citrusmoose** [tonesto7/nest-manager#458]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats? 1
* How many Protects? 1
* Are you Using the Nest Presence Device? No
* iOS or Android? iOS
* Mobile App Version: 2.3.6

## Expected Behavior

The font size for temperature on the main tile of the thermostat should be larger.  The controls (up/down arrows) on the main tile should change the setpoints.  There should be relatively minimal whitespace between the  slides and bottom control tiles.

## Current Behavior

The font size for the temperature on the main tile is small.  The controls on the main tile do not change the setpoint.  I assume this is because it's in auto mode.  There's a relatively large amount of whitespace between the slides and bottom control tiles.

## Steps to Reproduce (for bugs)

1. View a thermostat device
2. Change mode to auto
3. Try and press up or down arrow on main tile
4. Notice nothing happen

## Context

I see a bunch of these when I try to change setpoints with the arrows on the main tile:
> warn || Nest Thermostat - Hallway: Temp Change without a chgType is not supported!!!

I assume that's because it's in auto mode.  I expect to see an error of some sort, or perhaps the arrows shouldn't be there at all in auto mode.  Or perhaps the arrows should change the setpoints for the detected mode.
See the attached images for display issues (sorry about size, not sure how to reduce with github's markdown).  Thanks!
![small_temperature_font_size](https://cloud.githubusercontent.com/assets/888906/26582436/24b7218e-450f-11e7-8cfc-f3dd7e2fbbe5.png)
![whitespace_issue](https://cloud.githubusercontent.com/assets/888906/26582774/5b5e53f0-4510-11e7-9689-51c662a20026.png)

**Comment by tonesto7** [comment]
The issue with the font is a client bug.  It's fixed in upcoming 2.4.0 client.  

As far as the set point stuff we can't display error in the device handlers themselves.  We are limited by ST. 
We added push notifications for errors and what not but those only display for a moment 
I added in HTML but it can't refresh itself and doesn't work that great on the android client.

**Comment by imnotbob** [comment]
ST released the new mobile client
