### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Tokn59** [tonesto7/nest-manager#459]
![enterdevice](https://cloud.githubusercontent.com/assets/9215231/26796813/188fbaf8-4a2b-11e7-82ef-3522511a50cf.JPG)
![smartapps](https://cloud.githubusercontent.com/assets/9215231/26796814/199443d8-4a2b-11e7-9df5-892f08325c76.JPG)

Hello,

I tried to following the full NST_Manager installation Guide. I ran into problems at 2 points :
At the section "Nest Device Installation" it is said to : 
- click on "My Devices" and then "+ New Device" and copy paste the code for each device listed below.

I do not see how that can be done with "My Devices". I do not have the option here to paste any code, it's just a form you need to fill in with the name, label, ID ... of the new device, no option to paste any code.

Secondly I went to the process of the installation of the SmartApps but see nowhere in my IOS App a "My Apps" sectionb ?

Any help wouldbe greatly appreciated !

Thanbks & Kind Regards,

Tony

**Comment by tonesto7** [comment]
It doesn't say 'my devices'  it says 'my device handlers'.   From there you can create new device from code

**Comment by Tokn59** [comment]
Thanks for the quick reply .. Sorry but I am confused here (see secreenshjot attached)
![nest1](https://cloud.githubusercontent.com/assets/9215231/26797130/2f0a8b04-4a2c-11e7-9d14-2c101d11cd95.JPG)

**Comment by Tokn59** [comment]
Sorry accidentally closed this

**Comment by Tokn59** [comment]
I did install all the different device handlers (see screenshot) but not clear how I can add device now (referring to doc which says) :  "and copy paste the code for each device listed below." as the code below is for the device handlers, not for the devices ?
![devhandlers](https://cloud.githubusercontent.com/assets/9215231/26797812/7d3b67f6-4a2e-11e7-907c-a8ef6a209151.JPG)
**

**Comment by imnotbob** [comment]
have you been able to correct the installation?
