### ISSUE TITLE
Can't control thermostat

### ISSUE THREAD

**Issue by whasf** [tonesto7/nest-manager#460]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 1
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: iOS
* Mobile App Version: 2.4.0

## Current Behavior

My Nest devices are showing as unavailable in the UI

## Steps to Reproduce (for bugs)

I did a clean install, enabled oAuth, logged into Nest with my email/pass. The native Nest application sees my thermostat and protect fine.

See attached logs, the nest API is reporting that my thermostat is offline for some reason :( 

1.
2.
3.
4.

## Context

I can't control my thermostat!

Please include a copy of your log under the IDE if possible>>>
[tstat_offline.txt](https://github.com/tonesto7/nest-manager/files/1062863/tstat_offline.txt)

**Comment by whasf** [comment]
I noticed it started happening this afternoon (6/8). I tried upgrading Nest, and then doing a full rip and reinstall. No help :(
Also, I have three unavailable items in my device list on the mobile app:
* Nest Protect
* Nest Thermostat
* Nest vThermostat (my SmartThings hallway sensor that i'm trying to use as a remote temp sensor)

**Comment by imnotbob** [comment]
your log shows an error from nest that the device is offline.

When you go into the nest mobile app, is this what it shows you?

**Comment by whasf** [comment]
In the Nest mobile app my thermostat and Protect show as online. 
What's weird is the vThermostat that I made from my smartthings motion sensor also shows unavaialable.

**Comment by whasf** [comment]
I upgraded to 5.1.1, removed, and reinstalled. Attached is the log file. It finds my devices, but then they just go offline. The Home/Away isn't correct either, ST status is "away".... 
I don't know what's up, totally broken :(
[reinstall.txt](https://github.com/tonesto7/nest-manager/files/1064999/reinstall.txt)

**Comment by tonesto7** [comment]
if they show it's a bug in the ST platform.  Open each device UI and press the settings gear at the top right where you go to change the device label.  Press Done.  It will run a repair process within 30 seconds.

Home/Away status is very accurate..  I need you to elaborate on that more where are seeing the issue

**Comment by whasf** [comment]
Hmm... In the SmartThings IDE it was showing a conflict for the nest-protect device handler and I couldn't clear that up. I removed the GitHub integration and re-setup everything and now it looks good, except my protect went offline again.

Current status:
Nest tstat = Good
Nest presence = Good
Virtual tstat = Good
Protect = unavailable
I'll reboot the Protect later tonight when I get home and see if it repairs itself.

**Comment by whasf** [comment]
Reset the protect and it now shows online in ST app.

Thanks and sorry for the bother!
