### ISSUE TITLE
"Use this pincode to connect with Nest"

### ISSUE THREAD

**Issue by jefflv** [tonesto7/nest-manager#463]
## Verify the following before opening an issue:
- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS
* Mobile App Version: Nest Manager 5.1.1

## Expected Behavior
After pressing Accept, Nest Manager is added to SmartThings

## Current Behavior
After pressing Accept, message appears "Use this pincode to connect with Nest"

## Steps to Reproduce (for bugs)
1) Try to add NST Manager SmartApp
2) Enter Nest username/password for authentication
3) Press the Accept button.

## Context
Cannot install NST Manager

**Comment by imnotbob** [comment]
We have just updated the tokens, let us know if it is working now.

**Comment by brian-pollard** [comment]
I was having the same problem. After clicking the Accept button, it now gives a Website Not Available error instead of providing a pincode. 

https://graph.api.smartthings.com/oauth/callback?state=...&code=... could not be loaded because: net::ERR_CONNECTION_TIMED_OUT

**Comment by imnotbob** [comment]
it should be fixed now.

**Comment by brian-pollard** [comment]
Thank you very much. Working well now. Question - do you know if there is a
way to trigger the alarm on a nest protect? I want to use them as alarms
for a security system

**Comment by imnotbob** [comment]
Nest does not give us access to the components of the protect.

See:  http://thingsthataresmart.wiki/index.php?title=NST_Manager#Other_Requests
