### ISSUE TITLE
Weather Device constantly polls and impacts hub performance 

### ISSUE THREAD

**Issue by andynewton0** [tonesto7/nest-manager#464]
After updating app to 5.1.2 and all device handlers to 5.1.0 I noticed the hub performs badly at time. When I look at the activity feed I found the NST Weather device was constantly reporting/polling.

I removed the Weather Device and this stopped ..   

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
Can you turn it back on, and give us IDE logs?

**Comment by tonesto7** [comment]
Just to be clear. Cloud devices have absolutely no interaction with the Hub at all so there are not impacting performance

**Comment by andynewton0** [comment]
Hi


Thanks for the response to my issue.


When I tried to turn on the device and capture the logs I saw something interesting in the logs which reported the NST automations were out of date. I had incorrectly assumed that having updated the app and device handlers I didnt need to do this , which I have now so the errors for this have now disappeared from the logs.


However as soon as I switch on the weather device I get 12-14 events appear in the activity feed from the Nest Weather device, however they do not appear in the logs.


That said I think I might now have an idea what is wrong.. I also have the Rboys Smart Weather app installed which I think maybe conflicting ..   anyway I capatured the logs at the time when NST Weatheer device dumps the 12-14 events in the activity feed. However I dont thnk this will tell you much.


I can remove the Smart Weather app is that helps.


Re the point about cloud services impacting hub performance.  If I issue a command via the app and the cloud service is busy dealign with inputs from other devices then there is a delay. This I can equate to the network scenario when you for example have a busy uplink and as the packets needed to requested your download cant get to the server via the busy uplink so the download performance appears slow. I think the NST manager / weather device was throwing out either errors (caused by version mismatch) or updates which kept the cloud device busy so it wouldnt respond to my inputs or other routine requests.. thus giving the impression of slow hub performance.


Hope this helps .


6787cdbd-9f4f-41a1-a8b1-6a4e260049b9<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#6787cdbd-9f4f-41a1-a8b1-6a4e260049b9> 16:06:08: debug Parse returned [name:temperature, value:27, unit:C, descriptionText:{{ device.displayName }} was {{ value }}°C, translatable:true]
6787cdbd-9f4f-41a1-a8b1-6a4e260049b9<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#6787cdbd-9f4f-41a1-a8b1-6a4e260049b9> 16:06:08: debug description: temperature: 27.33
36a9eed8-2f3c-4535-b94c-a1d96dbf6f77<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#36a9eed8-2f3c-4535-b94c-a1d96dbf6f77> 16:06:00: debug Parse returned {{ linkText }} has left
8680f2af-4a4d-4d19-962a-c32159c96c71<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#8680f2af-4a4d-4d19-962a-c32159c96c71> 16:05:54: trace Refresh weather, update frequency 5 minutes
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:55: debug WUSTATION: oldKeys = []
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:55: debug WUSTATION: event: [name:forecastIcon, value:partlycloudy, displayed:false]
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:55: trace physicalgraph.device.cassandra.DeviceState@1f485fb4
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:54: debug WUSTATION: event: [name:localSunset, value:9:18 PM, descriptionText:Sunset today at is 9:18 PM]
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:54: debug WUSTATION: event: [name:wind, value:4, unit:MPH]
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:54: debug WUSTATION: event: [name:illuminance, value:10000]
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:54: debug WUSTATION: event: [name:weather, value:Clear]
b86bab19-fc2d-446e-b306-e0c6a290da6a<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#b86bab19-fc2d-446e-b306-e0c6a290da6a> 16:05:54: debug WUSTATION: event: [name:humidity, value:40, unit:%]
c3f816cc-3c5f-4a5d-b41c-9f699ac1fd45<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#c3f816cc-3c5f-4a5d-b41c-9f699ac1fd45> 16:05:42: trace getPhrases(), state.welcomeIssue = null
4a206fbc-0fb8-4d5a-9e01-57f540d3a1cb<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#4a206fbc-0fb8-4d5a-9e01-57f540d3a1cb> 16:05:35: info ||| NST Manager | No Device or Structure poll - Devices Last Updated: 33 seconds ago | Structures Last Updated 32 seconds ago


Regards



Andrew Newton

________________________________

**Comment by imnotbob** [comment]
most of those logs are not from the NST manager weather device, but some  other device.

There is one message from NST Manager, the rest are not us.

if you have enabled built-in automations that are part of nst manager, if they use a weather device, they need the nest manager weather device enabled.

**Comment by andynewton0** [comment]
Ok but now getting these !!
[Image]

Send via mobile
________________________________

**Comment by imnotbob** [comment]
no attachment on your note.  please post IDE 'live logging' logs if you are having issues.

It is best to put these in a private message in the forum to us if you don't want the information public

**Comment by andynewton0** [comment]
Ah sorry was there no image attached ? These were not logs that I can provide from the IDE these were notticiations to my phone re api calls.

Have attached again

No problem with putting in forum oublic or private , just would like to help resolve errors and make it better for everyone to use ..

Thanks for the help to date

[Image]

Send via mobile
________________________________

**Comment by imnotbob** [comment]
still no attachment

**Comment by andynewton0** [comment]
Hi, it was a photo so may have been blocked.


the error was a smart thing notification to my phone which said the following and was repeated a few times.


Nest Manager API CMD Failed:

The (structures: (away: away)) CMD

sent to the API has failed.

Status Code: null


All errors are the same, usually I get two or three in a short space of time then nothing for days.


Also happens at random times , not when system is doing anything such as arming or disarming


Trouble is these do not show in logs either .. it seems notification don't appear in the logs


Hope this is useful




________________________________

**Comment by imnotbob** [comment]
make sure you are running the latest version

Are you saying you see nothing in "live logging" in the IDE?   There should be something, especially if there are errors.

We had one other user have issues with nothing in live logging.  We had them contact smartthings, not to debug nest manager, but just to get live logging to work.   Then we can help debug nest manager.

**Comment by andynewton0** [comment]
Initial answer is yes as I know live logging does not display a lot of things.


But as this is ill regular I cant say until it happens again.. if it does I will check live logging straight away


Regards


Andy Newton


________________________________
