### ISSUE TITLE
Can't reach nest.com right now. Try again soon.

### ISSUE THREAD

**Issue by ijaspley** [tonesto7/nest-manager#465]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* Are you Using the Nest Presence Device? I was before
* iOS or Android?: Android (main), iOS occasionally
* Mobile App Version: Latest

## Expected Behavior
 Should pass the Accept button in WWN

## Current Behavior
 Button reverts back to Accept, message 'Can't reach nest.com right now. Try again soon.' appears at the top of the screen

## Steps to Reproduce (for bugs)

1. Remove all Nest devices
2. Remove NST Manager smartapp
3. Reinstall NST Manager smartapp
4. Attempt to log in with Nest credentials

## Context
 I can no longer use NST manager or Nest devices in Smartthings

Please include a copy of your log under the IDE if possible>>>

**Comment by ijaspley** [comment]
![screenshot 2017-06-16 at 12 07 52](https://user-images.githubusercontent.com/19664782/27224429-ff6984e0-528c-11e7-817e-73a490849dd0.png)

**Comment by imnotbob** [comment]
should be working now

**Comment by ijaspley** [comment]
It sure is, thanks
