### ISSUE TITLE
Error when trying to add automations

### ISSUE THREAD

**Issue by bexier** [tonesto7/nest-manager#466]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [ x] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?4
* Are you Using the Nest Presence Device?no
* iOS or Android?: Android
* Mobile App Version:6.0

## Expected Behavior
 I click add automations and a big red error banner appears at the top. I uninstalled everything and reinstalled. I am expecting the automation to turn on/off cameras when home/away mode changes.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
can you provide IDE logs?

In a private message in the forum would be best to control the sharing of data.

**Comment by bexier** [comment]
How do I leave a private message? And should I provide you the string of characters from the app or copy paste the information from IDE -> locations -> smartapps -> NST MANAGER or Nest Manager?

**Comment by imnotbob** [comment]
Live Logging is
IDE -> "Live Logging", leave window open a couple mins, then do your action, then cut and paste the log.

You can (if you like) send us screen shot of
IDE -> "My Locations" -> select location
scroll down to where NST manager is visible then take screen shot of the smartapps with NST manager visible (do not need to click again)

Sending a private message in the forums is done by go into web browser for ST community forums, select in upper right the circle with letter (your account), then select mail icon

Tony's and my handles are listed here: http://thingsthataresmart.wiki/index.php?title=NST_Manager#Project_Summary

**Comment by bexier** [comment]
Sent.  I hope I got the right info.  I ran through the process and when I "updated" (mind you no automation was added because of error) The live logs reported.  Also got a screen grab of the roll over report under locations with the other apps showing.
