### ISSUE TITLE
Not Found - We're very sorry, but that page doesn't exist.

### ISSUE THREAD

**Issue by jamesstruble** [tonesto7/nest-manager#468]
I get the "Not Found - We're very sorry, but that page doesn't exist." message after I click the ACCEPT button on the Works with Nest page.

Any suggestions on how to get beyond this message?

## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X ] The SmartApp and Device are using the latest version.
- [X ] You have reviewed the Readme for potential fixes.
- [ X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
sorry about that, should be fixed now

**Comment by jamesstruble** [comment]
Wow!!!! Thanks

Sent from my iPhone

On Jul 4, 2017, at 10:41 AM, imnotbob <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry about that, should be fixed now
