### ISSUE TITLE
Fresh install - NEST Camera issue

### ISSUE THREAD

**Issue by Tokn59** [tonesto7/nest-manager#469]
I did a fresh install of the Repo. Everything works fine. 2 NEST protect devices are found and working. However the NEST camera gives some errors. (See screenshots)

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
-> UPDATED IN THE IDE, IOS App Shows version is v5.0.9 and new version is available, not sure how to update this.
- [ X] You have reviewed the Readme for potential fixes.

- [X ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 2
* Are you Using the Nest Presence Device? NO
* iOS or Android?: IOS
* Mobile App Version: LATEST

## Expected Behavior
Camera should show streaming

## Current Behavior
I get conflicting info. "Active" but no streaming (SEE SCREENSHOTS) and ERROR "Camera ID Not Found"

## Steps to Reproduce (for bugs)

1. Click on camera in App IOS
2. Shows no image
3. Shows error
4.

## Context

No entries in LOG IDE
![img_4860](https://user-images.githubusercontent.com/9215231/27875080-45111aba-61b2-11e7-8247-fb1acf926180.PNG)
![img_4861](https://user-images.githubusercontent.com/9215231/27875081-4516e7ce-61b2-11e7-8924-1a2d840129cf.PNG)

**Comment by imnotbob** [comment]
Do you have IDE logs?
http://thingsthataresmart.wiki/index.php?title=NST_Manager#Troubleshooting

**Comment by squeaky369** [comment]
I am having a similar issue with my setup (sorry in advance if I should create a new issue or not).

However, my device info is all filled out, Public video is turned on, Nest Manager is version 5.1.8, OAuth is turned on and everything is published. My Nest Thermostat and Presence Sensor is working fine, just the cameras are not streaming / displaying.

The odd thing is, it's detecting motion (I have snapshots turned off), so it's reading the camera, just not showing anything on the screen. 

When I try and stream, this shows up in the logs:

```
8:42:21 AM: info ||| NST Manager | No Device or Structure poll - Devices Last Updated: 120 seconds ago | Structures Last Updated 120 seconds ago
8:41:53 AM: debug streamHandler(stream: XXX), deviceId: XXXX
8:41:21 AM: info ||| NST Manager | No Device or Structure poll - Devices Last Updated: 60 seconds ago | Structures Last Updated 60 seconds ago
XXX  8:40:29 AM: debug [SM] poll() - Updating device 'Front Door'
XXX  8:40:29 AM: trace [SM] Executing 'ringApiGet()'
XXX  8:40:29 AM: trace [SM] Executing poll()
XXX  8:40:29 AM: debug getChildDevices(false), children=1
XXX  8:40:29 AM: debug Health Poll is called
XXX  8:40:25 AM: debug Nest Camera - Driveway: ┌────────New Camera Event────────
XXX  8:40:25 AM: debug Nest Camera - Driveway: │	Type: Motion Event
XXX  8:40:25 AM: debug Nest Camera - Driveway: │	Start Time: (Wed Jul 19 08:39:32 EDT 2017)
XXX  8:40:25 AM: debug Nest Camera - Driveway: │	End Time: (Wed Jul 19 08:39:37 EDT 2017)
XXX  8:40:25 AM: debug Nest Camera - Driveway: │	Zones: [Driveway]
XXX  8:40:25 AM: debug Nest Camera - Driveway: │	Took Snapshot: false
XXX  8:40:25 AM: debug Nest Camera - Driveway: └────────────────────────────
8:40:21 AM: info ||| NST Manager | API Device Data HAS Changed (POLL(ASYNC))
8:40:21 AM: info ||| NST Manager | Updating Structure Data (Last Updated: 180 seconds ago) | Updating Device Data (Last Updated: 180 seconds ago) (async)
8:39:21 AM: info ||| NST Manager | No Device or Structure poll - Devices Last Updated: 120 seconds ago | Structures Last Updated 120 seconds ago
```

**Comment by imnotbob** [comment]
We should take this to a private message in the community forums, to avoid too much public sharing.

Our handles are in the NST manager docs:

http://thingsthataresmart.wiki/index.php?title=NST_Manager
