### ISSUE TITLE
Thermostat screen up/down temp does not change

### ISSUE THREAD

**Issue by smartmanjeff** [tonesto7/nest-manager#471]
## Verify the following before opening an issue:

- [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [ x] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:2
* How many Protects?3
* Are you Using the Nest Presence Device?no
* iOS or Android?:android
* Mobile App Version:2.4.1

## Expected Behavior
 number would change up and down when you select up or down arrow
 number should change :-)

## Current Behavior
number stays the same as the current temp

## Steps to Reproduce (for bugs)

1.select thermostat -> right now
2.click up or down arrow to change the temp
3.
4.

## Context
change temp, the one below the fan and home icons work as another way to change

Please include a copy of your log under the IDE if possible>>>

**Comment by johnny2678** [comment]
Not high priority since you change setpoints using the red/blue settings below the main tile, but this does impact the WAF.  She just told me the new thermostat controls didn't work :)

**Comment by smartmanjeff** [comment]
Defenetly, just thought I'd put it out there in case is was just me.

**Comment by imnotbob** [comment]
Is your thermostat in auto mode, or heat or cool?

In auto, the up/down do not work (we don't know to adjust the lower heat setting or higher cool setting)

Unfortunately St does not make it easy for us to remove controls based on "mode".

**Comment by smartmanjeff** [comment]
Cool mode


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: imnotbob <notifications@github.com> Date: 7/12/17  9:01 AM  (GMT-05:00) To: tonesto7/nest-manager <nest-manager@noreply.github.com> Cc: smartmanjeff <jeffcevans@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tonesto7/nest-manager] Thermostat screen up/down temp does not change (#471) 
Is you thermostat in auto mode, or heat or cool?
In auto, the up/down do not work (we don't know to adjust the lower heat setting or higher cool setting)
Unfortuatnely St does not make it easy for us to remove controls based on "mode".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tonesto7/nest-manager","title":"tonesto7/nest-manager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tonesto7/nest-manager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@imnotbob in #471: Is you thermostat in auto mode, or heat or cool?\r\n\r\nIn auto, the up/down do not work (we don't know to adjust the lower heat setting or higher cool setting)\r\n\r\nUnfortuatnely St does not make it easy for us to remove controls based on \"mode\".\r\n"}],"action":{"name":"View Issue","url":"https://github.com/tonesto7/nest-manager/issues/471#issuecomment-314761919"}}}

**Comment by imnotbob** [comment]
Are you running 5.1.6 version?

If so we may ask you to enable some diag logging for us to look at.  If so we should take this into a private message in the forums, so we don't disclose a lot of data publicly.

Let us know if you are interested, and send us a private message in the ST community forum

**Comment by johnny2678** [comment]
I noticed the buttons don't work in auto mode - and your explanation makes sense.  Just switched cool mode and the up/down in the main tile adjusts temp accordingly. 

Running the latest - 5.1.6

**Comment by smartmanjeff** [comment]
running 5.1.6. sent logs in message. Doesn't seem to work in cool, auto for me on 2 thermostats

**Comment by tonesto7** [comment]
#509
