### ISSUE TITLE
Nest account acceptance fails during App install on iOS

### ISSUE THREAD

**Issue by blandry613** [tonesto7/nest-manager#473]
During the install of the Nest Manager app the Nest Credentials page returns an error "Opps! We encountered an error. Please try again." when "Accept" is selected.

## Verify the following before opening an issue:

- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 3
* Are you Using the Nest Presence Device? no
* iOS or Android?: iOS
* Mobile App Version: 2.4.1

## Expected Behavior
After selecting "Accept" to the terms and conditions the configuration should continue.

## Current Behavior
Returns the error: "Opps! We encountered an error. Please try again."

## Steps to Reproduce (for bugs)
Select Nest Manager from My Apps in the Add a SmartApp screen of the SmartThings app.

## Context
Unable to install the app. 

 info ||| Nest Manager | AuthToken not found: Directing to Login Page

**Comment by fstephanie** [comment]
I have the same problem.

**Comment by pascualg805** [comment]
same issue here as well.

**Comment by imnotbob** [comment]
try now, let me know if it works

**Comment by blandry613** [comment]
Thanks, works for me now.

Brent


On Aug 1, 2017, at 5:43 PM, imnotbob <notifications@github.com> wrote:

try now, let me know if it works

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonesto7/nest-manager/issues/473#issuecomment-319505792>,
or mute the thread

**Comment by pascualg805** [comment]
fixed it.  thanks!

**Comment by fstephanie** [comment]
Works for me too!

**Comment by billykwong** [comment]
I have the same problem.  Not working as of 9/12/17.

**Comment by bencrundwell** [comment]
Yeah, same problem here. Latest version, OAuth enabled, just wont let me Accept the Nest terms :(

**Comment by imnotbob** [comment]
Please see the instructions:

http://thingsthataresmart.wiki/index.php?title=NST_Manager

specifically:

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Installation_Instructions
note the section on Nest Developer Account

https://community.smartthings.com/t/release-nst-manager-v5-0/83228/733

The issue is Nest will not give us more tokens (you can get them yourself), because they view the tokens as not kept private enough. Smarthings will not assist us in keeping them private enough to meet Nest’s ask. So we are stuck between rock and hard place.

**Comment by pzmosquito** [comment]
creating Nest Developer Account solved the problem, working great now! Thank you!

**Comment by bencrundwell** [comment]
Yeah Same here! Instructions are a little off. Had to google the nest developer account signup link and you have to use a unique App name, but otherwise all working now!

**Comment by billykwong** [comment]
Instructions may need a bit updating, but I got it working as well after finding the Nest Developer Account and using my own unique app name.
