### ISSUE TITLE
Nest Protect shows as 'Wired' when it's a battery version

### ISSUE THREAD

**Issue by uk-rj** [tonesto7/nest-manager#474]
## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApp and Device are using the latest version.
- [X] You have reviewed the Readme for potential fixes.
- [X] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 1
* Are you Using the Nest Presence Device? Y
* iOS or Android?: iOS
* Mobile App Version: Latest

## Expected Behavior
Nest Protect Device on SmartThings reports the power type of the Nest Protect as 'Battery'

## Current Behavior
Nest Protect Device on SmartThings reports Nest Protect power type as 'Wired' type when infect it's a battery type.

## Steps to Reproduce (for bugs)
1. Click on the Nest Protect device from the 'Things' menu list.
2. In the 'Right Now' status -> Device Info -> Power type. Shows as Wired.

## Context
Minor issue, more of an FYI.

**Comment by imnotbob** [comment]
Can we see some of your log data?

If so, can you private message me in the forums?  This is to avoid too much public sharing of your acct info.   My handle is in the NST Manager docs:

http://thingsthataresmart.wiki/index.php?title=NST_Manager

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Project_Summary
Send it to Eric

**Comment by imnotbob** [comment]
also please update to the version just released, and let us know if the problem persists

**Comment by uk-rj** [comment]
So I have gone in to the application today to grab the logs for you, but it is now showing a power type as 'Battery'. I have gone in to the application multiple times and it's now correctly showing, I wonder if it was some sort of incorrect registration at the Nest end... who knows. Anyway the issue is resolved now so I'll close it.
