### ISSUE TITLE
Temperature display color doesn't translate to Celsius

### ISSUE THREAD

**Issue by physhster** [tonesto7/nest-manager#475]
When switching to Celsius, the displayed temps show inaccurate temperature colors. I.E. it shows dark blue for 22C while 72F is more yellow/orange-ish.

## Expected Behavior
Displayed temp color matches the actual temperature

## Current Behavior
Temperatur color matches the comfort level regardless of the unit used (Customary or Metric).

## Steps to Reproduce (for bugs)
1. Switch ST app to Celsius
2. Observe temperature in My Home
3. Displayed color is inaccurate

**Comment by imnotbob** [comment]
See:

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Installation
