### ISSUE TITLE
NEST Camera : Camera ID Not Found

### ISSUE THREAD

**Issue by Tokn59** [tonesto7/nest-manager#477]
## Verify the following before opening an issue:

- [X ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X ] The SmartApp and Device are using the latest version.
- [X ] You have reviewed the Readme for potential fixes.
- [X ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: IOS
* Mobile App Version: Latest NEST, Smartthings Apps in use on latest build of IOS, iPhone & iPad
**Info from the 2 Nest protect devces is shown correctly in the App**

## Current Behavior

When trying to view live feed from my camera (1 installed) in the IOS App I get the messages : 
- Camera Cannot be found
- Camera ID Not Found
## Steps to Reproduce (for bugs)

1.Open Smartthings App
2.Go to the NEST Camera
3.Click on "Streaming"
4.

## Context

Please include a copy of your log under the IDE if possible>>>
My IDE log for this camera shows the following : 
6d9e1dad-406d-41d6-888b-d154f0057826  11:51:39 AM: trace streamingOn...
6d9e1dad-406d-41d6-888b-d154f0057826  11:51:36 AM: error java.lang.NullPointerException: Cannot invoke method refresh() on null object @ line 231
6d9e1dad-406d-41d6-888b-d154f0057826  11:51:36 AM: debug polling parent...
6d9e1dad-406d-41d6-888b-d154f0057826  11:51:34 AM: error java.lang.NullPointerException: Cannot invoke method refresh() on null object @ line 231
6d9e1dad-406d-41d6-888b-d154f0057826  11:51:34 AM: debug polling parent...
6d9e1dad-406d-41d6-888b-d154f0057826  11:48:15 AM: trace streamingOn...
6d9e1dad-406d-41d6-888b-d154f0057826  11:47:07 AM: trace streamingOn...
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:49 AM: debug repairHealthStatus([flag:true])
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:42 AM: trace initialize(): Ran within last 2 seconds - SKIPPING
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:42 AM: debug initialized...
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:42 AM: debug updated...
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:42 AM: debug repairHealthStatus(null)
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:42 AM: debug initialized...
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:42 AM: debug updated...
6d9e1dad-406d-41d6-888b-d154f0057826  11:46:01 AM: trace streamingOn...

Thank you for helping me solve this issue !!!
Kind Regards,
Tony

**Comment by imnotbob** [comment]
I suggest you go into NST Manager -> Manage Devices ->Nest Cameras

If the camera is visible there, de select it, and done your way out

wait 30 seconds, then go back in and select it and again done your way out


if you don't see it there, you may need to re-install.  Please ensure all software is up to date
and the instructions have been followed.

http://thingsthataresmart.wiki/index.php?title=NST_Manager

**Comment by Tokn59** [comment]
Hello, The camera is visible in NST Manager. By going in Manage devices I can Select/Deselect it as you said.

In the App the camera (Black windows where image should appear) it first says :


  *   Camera Active
  *   Then “Connecting”
  *   “Camera cannot be found. We are trying to connect”

Then nothing happens anymore, keeps saying “connecting”

I will delete NST manager from Smartthings and re-install everything from scratch again.

Thank you !

Tony

**Comment by Tokn59** [comment]
Sorry but this still does not work .. same error as before ...

**Comment by tonesto7** [comment]
#371
