### ISSUE TITLE
Issue with loading/Refreshing device information page

### ISSUE THREAD

**Issue by Protocol-X** [tonesto7/nest-manager#479]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: Android 7.0
* Mobile App Version:  5.1.9

## Expected Behavior
Information Page loads and Refreshes when pressing the refresh buttons

## Current Behavior
If the refresh button is pressed after selecting your device from the device list, I receive a 404 error
If the device page is exited and accessed again it loads indefinitely.  The only fix is to kill the app and open it again

## Steps to Reproduce (for bugs)

1.  404 Reproduction:  Smartthings > My Home > Nest Protect Device > Either of the 2 refresh buttons
2. Loading indefinitely: Smartthings > My Home > Nest Protect Device > back button >  Nest Protect Device

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
#500
