### ISSUE TITLE
can only view each device once - device does not refresh

### ISSUE THREAD

**Issue by jonbristow** [tonesto7/nest-manager#480]
- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: Android
* Mobile App Version: 2.5.0

## Expected Behavior
If viewed information on one of my protect devices and hit back button to view all devices and then go back to protect device same information (or updated) information is displayed.

## Current Behavior
when you go back to a previously viewed device no information is displayed and an animated circle is visible.  The only way to view the information is to exit the app, kill the app, then restart smartthings.  This behaviour is also happening on the weather device.

## Steps to Reproduce (for bugs)
1. Go to all My Home and list all things
2.  Select Nest Device
3. Hit back button
4. Select Nest Device again - no info and animated circle appears as if stuck refreshing

**Comment by tonesto7** [comment]
#500
