### ISSUE TITLE
Installed NST automation error

### ISSUE THREAD

**Issue by Coryrichter94** [tonesto7/nest-manager#487]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?0
* Are you Using the Nest Presence Device?yes
* iOS or Android?: Android
* Mobile App Version:2.5.1

## Expected Behavior
 it should let me edit the automation

## Current Behavior
 when I click on one of my automations (just one) it says something's wrong. We can't load your screen right now. 

## Steps to Reproduce (for bugs)

1.enabled debug option
2.enabled verbose logging

## Context

Please include a copy of your log under the IDE if possible>>>

I have tried to disable all automations but it does not disable this automation. 
This live logging was captured for the automation that is having error.
4cca460b-3622-45dd-96db-ceb252e42847 11:01:12 PM: error groovy.lang.MissingMethodException: No signature of method: script15054099285491752369473.getId() is applicable for argument types: () values: []
Possible solutions: getAt(java.lang.String), getApp(), getLog(), getUtil(), wait(), getBaseId() @ line 8061

**Comment by Rickala** [comment]
I have the same problem. Nest manager works though.
