### ISSUE TITLE
Nest Thermostat to find a Forecasted Temp Value and to adjust the Thermostat Temp Value at a specified Time Value.

### ISSUE THREAD

**Issue by jeffjaslow** [tonesto7/nest-manager#489]
Hello Tony,

Sorry to bother you....

I have a Nest Thermostat and live out in Colorado where there are some major temperature fluctuations: 30 degree nights and 80 degree days...But, sometimes 30 degree nights turn into 48 degree days...I would prefer to not HEAT AND COOL the house the same day for energy savings; Instead I would like to use the outside temperatures to help maintain a comfortable and environmentally friendly temperature inside the house.

**_If I set the Nest Temp to HEAT the house to 68_**: 
At night when the temp drops the house heats to 68 BUT then IF the OUTSIDE TEMP reaches 80 at some point in the day the internal temp rises in the house into the 80s UNLESS I set the COOL function as well.

**_If I set the Nest Temp to HEAT the house to a lower temperature like 60_**:
At night when the temp drops the house heats to 60 BUT then IF the OUTSIDE TEMP only reaches 48 at some point in the day I need to HEAT in the house to 72 to make it comfortable.

**_If I set the Nest Temp to COOL the house to a lower temperature like 68_**:
At night  the house COOLS to 68 BUT then IF the OUTSIDE TEMP the next day, only reaches 48, at some point in the day I need to HEAT in the house to 72 to make it comfortable.

I need the Nest Thermostat to find a Forecasted Temp Value and to adjust the Thermostat Temp Value at a specified Time Value:
IF the forecasted TEMP VALUE >=78 @2 pm, THEN at 5 am SET Temperature to COOL 72.
IF the forecasted TEMP VALUE <=50 @ 2 pm, THEN at 6 am SET Temperature to HEAT  68.

      _IF the COOL switch to HEAT function is not available then maybe:
      IF the forecasted TEMP VALUE <=50 @ 2 pm, THEN at 12:01 am SET Temperature to COOL to 84))._

I am not a programmer so I was wondering if there was a way to tweak your program to do that?

Any help would be appreciated.

Thanks.

Jeff Jaslow

**Comment by tonesto7** [comment]
I never saw this till now... This is exactly the use case the External Temp Automation in the SmartApp

**Comment by jeffjaslow** [comment]
Sorry to bother you...

I have downloaded, Authorized, and republished NST Manager and Automation
with a Nest Developer Token.

When I try to run the NST Manager program, I get through the Nest Login
Profile, but when I ACCEPT Works with Nest I get an Oops Something went
wrong error.

I deleted all and retried with the same error.

Any suggestions?

Jeff Jaslow
