### ISSUE TITLE
Thermostat Device doesn't load (spins/freezes) on Android. Fine on iOS.

### ISSUE THREAD

**Issue by lfcow** [tonesto7/nest-manager#492]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [ x] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?2
* Are you Using the Nest Presence Device? Yes
* iOS or Android?: Android
* Mobile App Version: 2.6.1 215737

## Expected Behavior

The thermostat "right now" page should load with details about the thermostat (temps, presence , etc.

## Current Behavior

"Right Now" tab for thermostat just spins with a circle icon in the middle. It sometimes spins choppy and sometimes just sits there not spinnning. Nothing loads

## Steps to Reproduce (for bugs)

1. Click My Home
2.Click Things
3. Click on the thermostat
4. Right Now tab comes up but does not load anything

## Context

The thermostat is completely unusable. Though the temp does show in the "things" menu before tapping it so some data is getting through. This is broken on my Android 8 phone, but works fine on iOS device.

Please include a copy of your log under the IDE if possible>>>
There's nothing in the IDE log or the device log generated by this action.

**Comment by lfcow** [comment]
Actually i just noticed that it does load some of the "Right Now" tab. It seems to load the top and the bottom, but not the part in the middle. I didn't notice this before because it was scrolling to the  middle automatically.
![screenshot_20170929-223539](https://user-images.githubusercontent.com/2508284/31041671-4f5949ea-a567-11e7-8996-202226b903a8.png)


![screenshot_20170929-223545](https://user-images.githubusercontent.com/2508284/31041674-555eb618-a567-11e7-84d4-ed8fb1c33b06.png)
![screenshot_20170929-223549](https://user-images.githubusercontent.com/2508284/31041675-5576a516-a567-11e7-8b62-f4dc6d252c2c.png)

**Comment by lfcow** [comment]
Looks like maybe something to do with the graph not loading? Not sure if this has anything to do with it, but my SST graph URL is https://graph-na04-useast2.api.smartthings.com and not the one that you reference in the wiki

**Comment by tlm4594** [comment]
I'm having the same exact issue. I've removed the device, re-added, but I get nothing. I cannot see anything at all--- it just spins. I cannot even move to the Recently and Smart Apps tab. I have a Google Pixel XL running Android 8.0 Oreo.

**Comment by lfcow** [comment]
Mine actually started working kind of sometimes.

**Comment by lfcow** [comment]
I removed the enter NST Manager, the automations, device handlers etc. Once
I added them again, it seems to work OK. the middle part takes a few
seconds to load.

However, I also had a couple extra thermostat devices in my Alexa app. I
removed the disconnected ones there also.

**Comment by audioe** [comment]
I'm having the same problem.  Android Samsung Galaxy S8+

**Comment by tlm4594** [comment]
I wish I could say I've had success. I'm sure I'm doing something wrong, but I'm banging my head against the wall. I've triple checked everything. No matter what I do, remove/re-install nothing works. It just spins. Am I being impatient here? Does it take a while for the codes to work? 
![img_20171006_094307](https://user-images.githubusercontent.com/26230171/31281030-4803f3f6-aa7c-11e7-9ed9-c6390bd0b65a.jpg)

**Comment by agentdr8** [comment]
Just tried setting up NST Manager for the first time today and also encountered this behavior on my Pixel running 8.0. Don't have an iOS device to test, but setup everything as outlined in the Google Doc regarding Nest Dev clientId & secret, and OAuth on the smartapp.

Tried removing all the devices, DTHs, and smartapps and now the IDE is throwing _500 Internal Server Errors_ when I try to remove the Nest Weather device. When I open the NST Manager smartapp on the phone, it gives me a _Something's Wrong -- We can't load your screen right now_ error so I can't remove it from the phone or the IDE.

**Comment by lfcow** [comment]
I've been finding that the spinning only stops after .I try and scroll a
few times.

**Comment by uberrob** [comment]
Not sure this helps, but I just did an update to the most recent version of device handlers and the smartapps for the NST manager, and I am getting identical behavior to what is described here:
- open the NST Manager Smartapp for the Nest Thermostat, and I get the sit-and-spin screen. Occasionally, I can get the screen to refresh by bouncing back and forth between "right now" and "recently," but that's pretty annoying.

All of the other NST devices are operating correctly. Just the thermostat.

**Comment by wjhutchina** [comment]
Hello, I'm new to NST Manager, i just installed it a couple nights ago. I went through and verified i did it correctly a couple times. I too am experiencing the same behavior. I also have a pixel with 8 on it. I added some routines with the thermostat and those seem to execute without any issue. its only when i try to access the thermostat from the things menu that it does not load.

**Comment by agentdr8** [comment]
Not sure why, but as @crickett mentioned, if you try and scroll/swipe up/down a few times while the spinner is showing, it tends to go away and you can see the expected info.

**Comment by zebozebo** [comment]
pixel 8 here. same spinning issue and scrolling is kind of fixing it but not really.
I am using a remote sensor as the temp source and another issue i'm seeing is that the virtual Nest I created is not displaying the temperature correctly. However, the automations are properly starting/stopping based on the true temp of the sensor, thankfully.

**Comment by dansrogers** [comment]
Pixel with Android 8 here.  It's also broken for me in the same way described above.  I'm having trouble figuring out what the error might be.  I've commented out graphHTML from the list of tiles in the meantime.  Any clues where I can look?

**Comment by wjhutchina** [comment]
I noticed on my wife's phone (lg v20) it loaded a what's changed/new
section. I don't recall this loading on my phone(pixel XL). Maybe that is
the culprit. Just a thought not much of a programmer....

**Comment by punkgamer69** [comment]
I am also have this issue on Google Pixel XL on Android 8.0. If I just open up the thermostat on Right Now it never loads and the circle spins in choppy manner. But if I quickly switch to Recently or SmartApps then go back to Right Now everything loads except the graphs. Those never load.

**Comment by tlm4594** [comment]
I have a Google pixel xl running on Oreo 8.1. Had the exact same issues on 8.0, downloaded and installed 8.1 through Android beta and now it works perfectly.

**Comment by tonesto7** [comment]
this is unfixable at the moment.  I added a disclaimer to users who defined there primary device in the smartapp.  This will show in each device the first time it's loaded

**Comment by SSlimC** [comment]
Same issue here, Pixel XL on Android 8
Based on the new information in this post I can confirm a few swipes brings up the basic controls(more then I could do before)
Thanks

**Comment by TheMadDaddy** [comment]
Same, must be an Oreo support issue. I also have android 8 on a different device and experience the same issue.

**Comment by DNARNA** [comment]
Same issue with my Pixel 2 XL and Android 8.1.0
All of Smartthings seems pretty slow but NST Manager never manages to load the historical temperature graph that it used to, just spins.  I can scroll up and down to see the other aspects of the thermostat but that part is just stuck.
