### ISSUE TITLE
Oauth Callback Exception: groovyx.net.http.HttpResponseException: Bad Request @ line 7000 

### ISSUE THREAD

**Issue by cjayres** [tonesto7/nest-manager#493]
Followed instructions to a T. Issue I am having is I am getting the following error in the logs

Oauth Callback Exception: groovyx.net.http.HttpResponseException: Bad Request @ line 7000 

Seems to be to do with Nest developer auth redirects. Can you help me with precise settings for this. this happens after hitting accept after logging on.  Also it displays HTML codes in the ios app. with messages like OH No! something went wrongm internal server error

**Comment by tonesto7** [comment]
I'm telling you that the redirect url in the develop page is wrong
It needs to be and not http://https://graph.api.smartthings.com/oauth/callback

**Comment by cjayres** [comment]
Hi wow thanks for the fast response. My redirect URL is https://graph.api.smartthings.com/oauth/callback
![capture](https://user-images.githubusercontent.com/30316586/31279697-e99fffb4-aaa1-11e7-83a4-00b0faf55fea.JPG)

**Comment by cjayres** [comment]
tried it in both default position and in the additional redirects and both

**Comment by cjayres** [comment]
overcame initial oops error by removing trailing spaces on the client ID and secret ID

**Comment by cjayres** [comment]
really appreciate all the help you give to the community

**Comment by cjayres** [comment]
As far as I can see I have set it up as per your instructions. Any help appreciated as I am completely stuck now.

**Comment by cjayres** [comment]
Hi. 

Any chance you can help me resolve this? 

Kind regards. 

Chris.

**Comment by cjayres** [comment]
still stuck on this. looked everywhere. Please help Using my own auth details from Nest developer account.
