### ISSUE TITLE
Installed and configured Nest Manager v5.2.1, but Nest Protect doesn't show up under Things

### ISSUE THREAD

**Issue by frazzlegod** [tonesto7/nest-manager#496]
I had issues with the previous version - NST Manager v5.2.0 - after creating my own auth token. It was very difficult to remove the SmartApp from my SmartThings (kept receiving error messages when attempting uninstall, both from the SmartApp itself and via SmartThings IDE), but I eventually managed it.

I have now re-installed the SmartApp, recently updated to v5.2.1, gone through all of the config settings, added my one and only Nest product - a Nest Protect - as done previously, tapped Save, Save, Save etc., received the "Successfully installed Nest Manager" message, BUT my configured Nest Protect device refuses to appear under Things.

Went into Nest Manager SmartApp again, my Nest Protect device appears as configured, but seems to still be displayed under "Devices pending install".

How do I get my Nest Protect device to appear under Things?

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

* How many Thermostats?: 0
* How many Protects? 1
* Are you Using the Nest Presence Device? No
* iOS or Android?: Android 7.0
* Mobile App Version: Latest, v5.2.1

## Expected Behavior
After installing and configuring Nest Manager SmartApp with single Nest Protect device and saving all settings, the Nest Protect device should appear under Things.

## Current Behavior
After installing and configuring Nest Manager SmartApp with single Nest Protect device and saving all settings, the Nest Protect device is not appearing under Things.

## Steps to Reproduce (for bugs)
See above

**Comment by frazzlegod** [comment]
Closing issue.

I found a similar issue to this - #494 - and followed @robfgreenwood's solution, by doing a complete uninstall and re-install of all device handlers and SmartApps via the IDE, which has resolved my issue too. All is now working as expected for me :)

Thanks again for such great apps, appreciate all your efforts in creating them.

**Comment by mattkerwin24** [comment]
I'm in between the SmartThings ADT security hub and Nest Protect...it seems for ease of use / setup the ADT system is a little simpler for setting up with SmartThings, but has anyone had any luck with getting Nest Secure to work with SmartThings?
