### ISSUE TITLE
You are missing the Client ID and Secret

### ISSUE THREAD

**Issue by deichenlaub** [tonesto7/nest-manager#497]
I followed all the steps (I think) using Git Hub integration. OAuth is True for NEST Manager. When I go into my phone / Marketplace / My Apps and touch Nest Manager, I get this message:

Status Page:
You are missing the Client ID and Secret.
We can no longer provide you with a built-in Nest Client ID an d Secret. Please check the Wiki for Detailed instructions on creating your own Nest Dev ID and Secret.

## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 5
* Are you Using the Nest Presence Device? no
* iOS or Android?: android
* Mobile App Version:
Not sure - installed 10/15/17

## Expected Behavior

The Nest Manager should install

## Current Behavior

I get the error message above

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I want to add the smoke detectors to my hub because that provides a house-wide mesh network that can be used for other devices. I don't have to worry about the distance to the hub.

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
DID YOU CHECK THE WIKI AND CREATE A NEST DEV ACCOUNT

**Comment by deichenlaub** [comment]
I missed that. MAlbert I'm looking at the wrong wiki? I'll look again. Thanks.
Sent from my Galaxy Tab A (2016)-------- Original message --------From: Tonesto7 <notifications@github.com> Date: 10/17/2017  11:14 AM  (GMT-05:00) To: tonesto7/nest-manager <nest-manager@noreply.github.com> Cc: deichenlaub <deichenlaub@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tonesto7/nest-manager] You are missing the Client ID and Secret
  (#497) 
DID YOU CHECK THE WIKI AND CREATE A NEST DEV ACCOUNT

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tonesto7/nest-manager","title":"tonesto7/nest-manager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tonesto7/nest-manager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tonesto7 in #497: DID YOU CHECK THE WIKI AND CREATE A NEST DEV ACCOUNT"}],"action":{"name":"View Issue","url":"https://github.com/tonesto7/nest-manager/issues/497#issuecomment-337262287"}}}

**Comment by deichenlaub** [comment]
That was it. Everything is working fine. Thanks.

**Comment by Hectoracosta** [comment]
Hello Tonesto. I got a massage when I get to the Nest Manager app in my phone.
(Nest Manager | AuthToken not found: Directing to Login Page)
This message is from my Life Logging.
Is there anything I'm missing.
I didn't had a problem creating my OAuth in Nest, all of that when well I think.
Please help.

**Comment by Cullinsg** [comment]
Im setting this up as well, will i need a oauth URl or jus the client ID and secret?

**Comment by cyanks** [comment]
I am having the same issue.

**Comment by dinkey88** [comment]
what to do after you create nest dev account?

**Comment by Yoshukai** [comment]
I’m having now You are missing the Client ID and Secret

**Comment by cyanks** [comment]
Interesting 
And for me my Nest Presence Device is not working.  It’s not detecting when I am Away?
Any thoughts/help would be appreciated

**Comment by dewana421** [comment]
I am having the same issue..on my smartapp, OAuth is True for NEST Manager. When I go into my phone / Marketplace / My Apps and touch Nest Manager, I get this message:

**Status Page:
You are missing the Client ID and Secret.
We can no longer provide you with a built-in Nest Client ID and Secret. Please check the Wiki for Detailed instructions on creating your own Nest Dev ID and Secret.**

Yes I created a nest dev account..created my OAuth in Nest which gave me a client id and client secret...my question is do i need to put that info from nest somewhere? if so then where because i dont see any option to do it ?
fyi i did a similar setup with my smart door lock and i did that integration via JSON Complete API and that went pretty well as I was able to put in the client ID and secret info in configuration but here there is no such option??

**Comment by scoob5684** [comment]
I tried to make a dev account with nest and it says they are not accepting new dev apps so no clientsecret anything you can help with

**Comment by imnotbob** [comment]
you should be able to login with your primary nest credentials.
