### ISSUE TITLE
NST Manager gets error when accept terms and conditions

### ISSUE THREAD

**Issue by mitchcat2000** [tonesto7/nest-manager#498]
I have used the document on wiki to do the merge install for the NST Manager and I generated my own tokens on Nest Dev site, but once I enter my nest user name and password the works with nest screen comes up with the accept button and it quickly "Oops! We've encountered an error. Please try again."
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 1
* Are you Using the Nest Presence Device? No
* iOS or Android?: Android
* Mobile App Version: 2.8.0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
 Can't link nest

Please include a copy of your log under the IDE if possible>>>

**Comment by myrison** [comment]
This appears to have something to do with the oauth redirect, but I'm admittedly guessing.  I have the same problem as a few other posts here in "issues list." 

The oauth 500 errors are described here:
https://community.smartthings.com/t/status-code-500-from-oauth-token/58054

Whenever I try to access the oauth callback URL, I get a 500 error, which I'm sure is the cause of not being able to authenticate with Nest and get a token back.  However, I can't figure out how to fix it.

It's the same error this user is having in another issue:
https://github.com/tonesto7/nest-manager/issues/493

Whether you use this callback:
https://graph-na04-useast2.api.smartthings.com/oauth/callback (my shard)

Or the generic one:
https://graph.api.smartthings.com/oauth/callback

SmartThings is now returning a 500 error for both of those pages.

Help would be appreciated.

**Comment by tonesto7** [comment]
This is almost always caused by whitespace being at the end of the oauth path or it added an http:// in front of the https://  in the nest developer portal

**Comment by cjayres** [comment]
Tonesto you closed my issue and I have checked for spaces and there aren't any and also my redirect is HTTPS only. I included screen shots in my issue describing and showing this. #493

**Comment by cjayres** [comment]
if I click on my redirect I get

Oh No! Something Went Wrong!
Error
500: Internal Server Error
URI
/oauth/callback
Reference Id
38aecc50-a7dc-4e7d-bee7-444b7e5078d0
Date
Fri Nov 10 19:15:15 UTC 2017

**Comment by mitchcat2000** [comment]
I have been in today and I have gone through all the steps from the cases
that you shared and I am still having the issue. Below is a screen shot of
my screen, I have no white space before or after the id or secret and not
sure what else to try, any help?

[image: Inline image 1]
