### ISSUE TITLE
Thermostat Setting & Temperature won't write

### ISSUE THREAD

**Issue by ctine2020** [tonesto7/nest-manager#499]
## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?2
* Are you Using the Nest Presence Device?N
* iOS or Android?:Android
* Mobile App Version:5.2.1

## Expected Behavior
 If I change from Heat to Cool, it should remain on cool.  If I change temp to 71 from 75 it should set nest to 71.

## Current Behavior
 In example above after a brief delay, App reverts back to Heat and 75 respectively.

## Steps to Reproduce (for bugs)

1.  Set Heat to Cool
2.  Change temp from 71 to 75
3.  Reset token as solution (didn't work)
4.  Uninstalled, reinstalled.  (didn't work) Reset token again (didn't work)

## Context
 Set my Thermostat through ST

Please include a copy of your log under the IDE if possible>>>

## Log Issues Found
12:06:47 AM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): target_temperature_f) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
12:06:47 AM: error nullLogger Error - type: error | msg: null | logSrc: Manager
12:06:47 AM: warn || NST Manager | [nestCmdResponse] | Status: (400) | Error Message: [message:No write permission(s) for field(s): target_temperature_f, details:[fields:target_temperature_f], error:No write permission(s) for field(s): target_temperature_f, instance:24dceccf-bc31-42e9-ad76-6169cc86b17c, type:https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]

12:05:20 AM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): hvac_mode) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
12:05:20 AM: error nullLogger Error - type: error | msg: null | logSrc: Manager
12:05:20 AM: warn || NST Manager | [nestCmdResponse] | Status: (400) | Error Message: [message:No write permission(s) for field(s): hvac_mode, details:[fields:hvac_mode], error:No write permission(s) for field(s): hvac_mode, instance:82e5d5a7-b24a-4d86-8779-c4d631058c27, type:https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]

**Comment by tonesto7** [comment]
This was Due to only having read permission set for the thermostat
