### ISSUE TITLE
Doesn't load the middle portion 

### ISSUE THREAD

**Issue by krypto6969** [tonesto7/nest-manager#500]
I installed the nest manager for my nest thermostat and it show up on my phone. The top portion of the screen works and I'm pretty sure it changes the temp

but

it looks like it doesn't load the middle portion - I just get a spinning blue loading animation - it never finishes.

Any idea where to check?

**Comment by ctine2020** [comment]
I believe this is an android issue that folks have notified ST about.  It's nothing to do with NST Manager from what I've read.

**Comment by tonesto7** [comment]
I can't fix this.  I tried again the other day and ST has made it worse.  They don't want to fix it apparently

**Comment by tonesto7** [comment]
I added a disclaimer to users who defined their primary device in the smartapp.  This will show in each device the first time it's loaded

**Comment by Haocen** [comment]
Can a toggle be added to hide the HTML part as a workaround?
