### ISSUE TITLE
Nest Developer Account Instructions - Google Drive TOS

### ISSUE THREAD

**Issue by camrex** [tonesto7/nest-manager#502]
I have been trying to follow the directions on the wiki. However the link for the Nest Developer Account instructions leads to a Google Drive page indicating document can not be accessed due to Terms of Service violation.

## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [x ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS
* Mobile App Version: 2.9.0 (1421)

## Expected Behavior
Installation directions should be accessible.

## Current Behavior
Installation directions are not accessible

## Steps to Reproduce (for bugs)
1. Click on "Creating Your ID and Token for Nest" link. (https://docs.google.com/document/d/1JoqNijFvLAHaQIMrqHCSBXgglUqdEnj3rBD9EiPP3bs/edit?usp=sharing)
2. Get TOS violation page.
3.
4.

## Context
Can not get NST manager to work without creating NEST ID & token.

**Comment by tonesto7** [comment]
Thanks for pointing this out.  I’ve corrected the issue
