### ISSUE TITLE
Updating nest manager

### ISSUE THREAD

**Issue by Maicach** [tonesto7/nest-manager#503]
I keep getting messages to update the nst manager. When I connected it a while back, you didn't have anymore tokens. So I followed your steps, registered with Nest and got it all connected. So I get the message to update and I go into the IDE. I do not see any updates but I believe there are. What do you advise?

**Comment by tonesto7** [comment]
This is usually because something is wrong and you need to review the Logs in the IDE.  Almost always it's because the device handlers or automation app is not running the most recent code.
