### ISSUE TITLE
Unable to select location during install

### ISSUE THREAD

**Issue by theRISCyALU** [tonesto7/nest-manager#505]
I am working through the install and after successfully logging into my nest account, I am unable to select a location. "You can't currently add this". I double checked that the Smart Things location and Nest both have a location configured.

## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* Are you Using the Nest Presence Device? 0
* iOS or Android?: Android
* Mobile App Version: 5.2.2 / smart things 2.9.0

## Expected Behavior
I should be able to pick a nest location that I want to control. There are no locations or the list of locations is not available.

## Current Behavior
I am unable to select a location. "Select Location:" "Nest Locations" "You can't currently add this"

## Steps to Reproduce (for bugs)
1. After completing all steps from the smart apps IDE and creating a nest developer account, begin the process of adding the custom app to smart things on a mobile device
2. sign into nest from within the NST Manager
3. Accept Terms
4. Press Done
5. Choose Location, which errors out as explained above.

## Context
I am trying to perfom first time set up. I was unable to do this as I could not choose which nest location I want to control.

0ee13ff2-3d10-44a8-afb5-d7eb1019a44c  11:39:44 PM: warn DEPRECATION: You no longer need to call 'unsubscribe' within the 'uninstalled' method.
0ee13ff2-3d10-44a8-afb5-d7eb1019a44c  11:39:44 PM: warn || Nest Manager | Nest Token revoked
0ee13ff2-3d10-44a8-afb5-d7eb1019a44c  11:39:43 PM: info ||| Nest Manager | revokeNestToken()
0ee13ff2-3d10-44a8-afb5-d7eb1019a44c  11:39:06 PM: warn || Nest Manager | Missing: structData null
0ee13ff2-3d10-44a8-afb5-d7eb1019a44c  11:39:06 PM: error getApiData (type: str) Exception: java.lang.NullPointerException: Cannot get property 'null' on null object

**Comment by tonesto7** [comment]
I'm looking into the issue

**Comment by tonesto7** [comment]
This is resolved as of v5.2.3

**Comment by IonCaza** [comment]
Experiencing this on 5.3.5 :( any ideas?

EDIT: This was because I was using a family account. Login to the main account made it work. Thank you!
