### ISSUE TITLE
I can't get passed location after setting up the smart app.

### ISSUE THREAD

**Issue by ConnifBoudoin** [tonesto7/nest-manager#507]
cannot get passed location screen when setting up nest manager.

## Verify the following before opening an issue:

- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApp and Device are using the latest version.
- [x ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
Sorry for the inconvenience.   I have fix pending... I will push it out in the next 1-2 hours

**Comment by bjvivs** [comment]
tonesto7 i am having the same issue, look forward to fix push and thanks for your work here this is great can't wait to try this out

**Comment by ConnifBoudoin** [comment]
It appears that the problem for the most part has been fixed. I was able to install the smartapp in my android phone a second time. Much quicker than the first time. I am getting things like a camera window and thermostat window. I can take a snapshot with the camera but no live streaming. It says that the camera is unavailable. I can also see if there is motion and if there is noise or quiet. So far the most part it appears to be partially working which is much better than yesterday when I couldn't get past the location screen after login.

**Comment by tonesto7** [comment]
@ConnifBoudoin  You really need to read the wiki to understand why the camera stream isn't working.  Also the device should be telling you why it's not streaming (the android client requires a full close and reopen of the app to get the HTML content to load)
