### ISSUE TITLE
Commands in the Smart App are executed

### ISSUE THREAD

**Issue by aibrahi3** [tonesto7/nest-manager#513]
## Verify the following before opening an issue:

- [X ] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ X] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [ X] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [X ] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects?: 0 
* How many Cameras?: 0
* Using the Nest Presence Device? yes
* Using the Nest Weather Device? yes
* iOS or Android?: android
* Mobile App Version: 2.1

## Expected Behavior

- the commands in the smart app should execute but they just revert to original state. 

## Steps to Reproduce (for bugs)

1. Increased the temperature in the smart app to 73, it reverted to 72 after a few seconds without making the change
2.
3.
4.

LOG:
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:40 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:40 AM: debug A sensor event occurred: [name:illuminance, deviceId:5e07a410-c104-45ff-8c9d-c2f329dc7446, isoDate:2017-11-17T12:37:40.261Z, unit:lux, value:511]
525a8202-6420-4727-b3f3-8d1888057f82  7:37:36 AM: debug Nest Thermostat - Dining Room: UPDATED | Fan Mode: (Auto) | Original State: (On)
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:38 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:38 AM: debug A sensor event occurred: [name:thermostatOperatingState, deviceId:525a8202-6420-4727-b3f3-8d1888057f82, isoDate:2017-11-17T12:37:38.849Z, unit:null, value:idle]
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:38 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:38 AM: debug A sensor event occurred: [name:thermostatFanMode, deviceId:525a8202-6420-4727-b3f3-8d1888057f82, isoDate:2017-11-17T12:37:36.249Z, unit:null, value:auto]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:26 AM: info ||| NST Manager | Updating Device Data (Last Updated: 46 seconds ago) (async)
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:22 AM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): fan_timer_active) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:22 AM: error nullLogger Error - type: error | msg: null | logSrc: Manager
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:22 AM: warn || NST Manager | [nestCmdResponse] | Status: (400) | Error Message: [message:No write permission(s) for field(s): fan_timer_active, details:[fields:fan_timer_active], error:No write permission(s) for field(s): fan_timer_active, instance:84283d16-9ab0-43d0-b8a5-64a77e6f53e8, type:https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:22 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U | ObjType: devices/thermostats | ObjKey: fan_timer_active | ObjVal: true | QueueNum: 1 | Redirect: true]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:21 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U | ObjType: devices/thermostats | ObjKey: fan_timer_active | ObjVal: true | QueueNum: 1 | Redirect: false]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:21 AM: trace | NST Manager | workQueue │ Run Queue: 1 | (async)
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:17 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:17 AM: debug A sensor event occurred: [name:thermostatOperatingState, deviceId:525a8202-6420-4727-b3f3-8d1888057f82, isoDate:2017-11-17T12:37:17.455Z, unit:null, value:fan only]
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:17 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:37:17 AM: debug A sensor event occurred: [name:thermostatFanMode, deviceId:525a8202-6420-4727-b3f3-8d1888057f82, isoDate:2017-11-17T12:37:17.428Z, unit:null, value:on]
525a8202-6420-4727-b3f3-8d1888057f82  7:37:17 AM: debug Nest Thermostat - Dining Room: UPDATED | Fan Mode: (On) | Original State: (Auto)
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:17 AM: info ||| NST Manager | schedNextWorkQ │ queue: 1 │ schedTime: 4 │ recentSendCmd: 2 │ last seconds: 42 │ cmdDelay: 4 │ allowAsync: true
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:17 AM: info ||| NST Manager | Adding Cmd to Queue 1 (qsize: 1): HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U, devices/thermostats, fan_timer_active, true, HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:37:17 AM: debug NST Manager | setFanMode | Setting Thermostat (Nest Thermostat - Dining Room - HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U) Fan Mode to (On)
65f1abab-3d15-4282-9691-649be4a1c01e  7:36:53 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:36:53 AM: debug A sensor event occurred: [name:illuminance, deviceId:5e07a410-c104-45ff-8c9d-c2f329dc7446, isoDate:2017-11-17T12:36:53.335Z, unit:lux, value:498]
525a8202-6420-4727-b3f3-8d1888057f82  7:36:52 AM: debug Nest Thermostat - Dining Room: UPDATED | thermostatSetPoint Temperature is (72°F) | Original Temp: (73°F)
525a8202-6420-4727-b3f3-8d1888057f82  7:36:52 AM: debug Nest Thermostat - Dining Room: UPDATED | Heat Setpoint is (72°F) | Original Temp: (73°F)
65f1abab-3d15-4282-9691-649be4a1c01e  7:36:52 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:36:52 AM: debug A sensor event occurred: [name:thermostatSetpoint, deviceId:525a8202-6420-4727-b3f3-8d1888057f82, isoDate:2017-11-17T12:36:52.110Z, unit:F, value:72]
65f1abab-3d15-4282-9691-649be4a1c01e  7:36:52 AM: debug sending data to AT
65f1abab-3d15-4282-9691-649be4a1c01e  7:36:52 AM: debug A sensor event occurred: [name:heatingSetpoint, deviceId:525a8202-6420-4727-b3f3-8d1888057f82, isoDate:2017-11-17T12:36:52.090Z, unit:F, value:72]
4db4fcaa-ef97-4fa2-9652-b6bc387c7380  7:36:47 AM: debug [SM] poll() - Updating device 'Front Door'
4db4fcaa-ef97-4fa2-9652-b6bc387c7380  7:36:47 AM: trace [SM] Executing 'ringApiGet()'
4db4fcaa-ef97-4fa2-9652-b6bc387c7380  7:36:47 AM: trace [SM] Executing poll()
4db4fcaa-ef97-4fa2-9652-b6bc387c7380  7:36:47 AM: debug getChildDevices(false), children=1
4db4fcaa-ef97-4fa2-9652-b6bc387c7380  7:36:47 AM: debug Health Poll is called
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:40 AM: info ||| NST Manager | Updating Structure Data (Last Updated: 140 seconds ago) | Updating Device Data (Last Updated: 43 seconds ago) (async)
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:36 AM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): target_temperature_f) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:36 AM: error nullLogger Error - type: error | msg: null | logSrc: Manager
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:36 AM: warn || NST Manager | [nestCmdResponse] | Status: (400) | Error Message: [message:No write permission(s) for field(s): target_temperature_f, details:[fields:target_temperature_f], error:No write permission(s) for field(s): target_temperature_f, instance:28229bd1-a7dd-419b-9350-71dad71e8af4, type:https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:35 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U | ObjType: devices/thermostats | ObjKey: target_temperature_f | ObjVal: 73 | QueueNum: 1 | Redirect: true]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:35 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U | ObjType: devices/thermostats | ObjKey: target_temperature_f | ObjVal: 73 | QueueNum: 1 | Redirect: false]
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:35 AM: trace | NST Manager | workQueue │ Run Queue: 1 | (async)
525a8202-6420-4727-b3f3-8d1888057f82  7:36:31 AM: debug Nest Thermostat - Dining Room: UPDATED | Pause Updates is: (false) | Original State: (true)
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:31 AM: info ||| NST Manager | schedNextWorkQ │ queue: 1 │ schedTime: 4 │ recentSendCmd: 3 │ last seconds: 39 │ cmdDelay: 4 │ allowAsync: true
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:31 AM: info ||| NST Manager | Adding Cmd to Queue 1 (qsize: 1): HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U, devices/thermostats, target_temperature_f, 73, HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U
d340bcda-e799-4a2e-83a8-a929a94e1cd1  7:36:31 AM: debug NST Manager | setTargetTemp | Setting Thermostat (Nest Thermostat - Dining Room - HSxQTyaiJJxxXTIrVaT3y9vhhgSX497U) Target Temp to (73°F)
 7:36:17 AM: info Waiting on events...
 7:36:17 AM: info For past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.
 7:36:17 AM: info This console provides live logging of your SmartThings.

## Context

Please include a copy of your log under the IDE if possible

**Comment by imnotbob** [comment]
Note following in logs:

d340bcda-e799-4a2e-83a8-a929a94e1cd1 7:37:26 AM: info ||| NST Manager | Updating Device Data (Last Updated: 46 seconds ago) (async)
d340bcda-e799-4a2e-83a8-a929a94e1cd1 7:37:22 AM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): fan_timer_active) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
d340bcda-e799-4a2e-83a8-a929a94e1cd1 7:37:22 AM: error nullLogger Error - type: error | msg: null | logSrc: Manager
d340bcda-e799-4a2e-83a8-a929a94e1cd1 7:37:22 AM: warn || NST Manager | [nestCmdResponse] | Status: (400) | Error Message: [message:No write permission(s) for field(s): fan_timer_active, details:[fields:fan_timer_active], error:No write permission(s) for field(s): fan_timer_active, instance:84283d16-9ab0-43d0-b8a5-64a77e6f53e8, type:https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]

This suggests the token was not created correctly for permissions.

**Comment by aibrahi3** [comment]
I changed the permission on the nest developer page as I just realized my mistake... However not sure how to update the smart app now to reflect this change

**Comment by imnotbob** [comment]
if you edited the token, then typically you need to go into Nest mobile app and accept use of the new token.   Then you need to go into smartthings and the works with nest and accept use of the new token privs.

(or you can uninstall and re-install Nest manager)

If you created a new token, you need to add new token information

**Comment by aibrahi3** [comment]
Thank you, I will re-install the NST manage

**Comment by aibrahi3** [comment]
Thank you, That did the trick!
