### ISSUE TITLE
Nest Manager refuses to work

### ISSUE THREAD

**Issue by yandreev3** [tonesto7/nest-manager#517]
I can go through and install the two smartapps and all of the device handlers but once I set up the smart app, it stops working.

## Verify the following before opening an issue:
- [X] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [X] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [X] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 2
* How many Protects? 4
* How many Cameras? 0
* Using the Nest Presence Device? NA
* Using the Nest Weather Device?  NA
* iOS or Android?:  Android Nougat
* Mobile App Version:  2.11.0

## Expected Behavior
The smartapp should load.

## Current Behavior
The smartapp doesnt load once its been set up and doesnt see my nest devices. Once I install the two apps and device handlers, I followed the nest developer instructions and generated a key and secret. I then edited the smartapp settings and copy pasted the two into their respective boxes. I then went to the mobile app and added the smartapp. During the setup, before logging into nest with my credentials, I got a log warning that said "2:10:54 PM: warn || Nest Manager | Missing: structData null". I continued on with the nest login and once that was complete the smartapp asked for me to pick the nest location. Once I picked it, I got an error in the app saying "unable to refresh page" I clicked next and I got no devices available but could set up the rest of the app. Once it was all done, clicking the smartapp gave me an error saying the page could not be loaded. I tried reinstalling the app manually instead of using the repository install and got the same result.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Please include a copy of your log under the IDE if possible:

85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:31:22 PM: info ||| Nest Manager | No Devices Selected; Polling is OFF
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:31:22 PM: trace | Nest Manager | stateCleanup
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:31:01 PM: info ||| Nest Manager | Installing Watchdog App
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:31:01 PM: debug Nest Manager | Nest Manager Updated...with settings: [optInSendExceptions:false, structures:nPSJ35PHPgiJGIa_oyW0Bp2xg6az9cFamQuug1c1f090_XtJMXZmtQ, optInAppAnalytics:false]
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:31:00 PM: info ||| Nest Manager | Installing Watchdog App
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:31:00 PM: debug Nest Manager | Installed with settings: [optInSendExceptions:false, structures:nPSJ35PHPgiJGIa_oyW0Bp2xg6az9cFamQuug1c1f090_XtJMXZmtQ, optInAppAnalytics:false]
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:30:37 PM: info ||| Nest Manager | Nest AuthToken Generated SUCCESSFULLY
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:30:05 PM: warn || Nest Manager | Missing: structData null
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:30:02 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
85fcd98e-6eac-4c2f-9dd4-00ac3e36aa36  2:30:02 PM: info ||| Nest Manager | appData.json File HAS Changed

Also just checked, Nest developer page is saying there are 0 current users using that developer product-------- Changed to 1 user after a while. App still does not load.

**Comment by yandreev3** [comment]
Definitely not a closed issue. Problem wasn't resolved.

**Comment by tonesto7** [comment]
I suggest you remove everything (apps/devices, code from smartthings) then remove the nest developer product and start over from the beginning and follow the process exactly.
