### ISSUE TITLE
Smarthing won't allow me to change Oauth information

### ISSUE THREAD

**Issue by sandifer** [tonesto7/nest-manager#522]
i get the "you are missing client ID and secret" error on smartthings app. I researched and found out I needed to create a Nest deverlopers account to create my own ID and secret for Oauth. I did all that and now have the ID ans Secret from Nest.However when I go into Oauth section of smartthings those 2 sections can not be changed or edited. i've tried deleting and starting over and I've also tried several browseres but those two fields cannot be edited to put the Nest credentials in. Any help would be appreciated.. Thanks

ssandifer@gmail.com

**Comment by breedm** [comment]
You've got to enter your Developer's Product ID and Product Secret into the Settings area of the MySmartApps IDE for NST Manager, not where you're looking for OAuth.  I tried to do the same thing.

Review directions: https://rawgit.com/tonesto7/nest-manager/master/Documents/instructions/Nest%20Developer%20-%20Nest%20Product.pdf
