### ISSUE TITLE
Nest will not update temperature, reverts back

### ISSUE THREAD

**Issue by DJDeleeted** [tonesto7/nest-manager#525]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?:1
* How many Protects?0
* How many Cameras?0
* Using the Nest Presence Device? no
* Using the Nest Weather Device? yes
* iOS or Android?: android
* Mobile App Version: 5.2.3

## Expected Behavior

When i change the temperature on Smartthings, it should change on the nest.

## Current Behavior

I change the temperature on smartthings but it reverts back withing seconds.

## Steps to Reproduce (for bugs)

1.open smartthings
2.go to things
3. open nest thermostat
4.set heat higher then before
5. look at recently and watch it change back to previous temperature

## Context

Please include a copy of your log under the IDE if possible

**Comment by gpsmith** [comment]
I’m also finding it’s not setting the temp, which turned out that I had messed up the best dev account and only set the temp to read but when I changed permission to write too it now works.
