### ISSUE TITLE
NST manager display shows 0 dc

### ISSUE THREAD

**Issue by loveall27** [tonesto7/nest-manager#529]
## Verify the following before opening an issue:

- [x ] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [ x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x ] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: One
* How many Protects? One
* How many Cameras?
* Using the Nest Presence Device?
* Using the Nest Weather Device?
* iOS or Android?: Android 
* Mobile App Version:
Smart thing version 2.13.0 build 218485
NST manager: 5.2.5

## Expected Behavior

In the Temperature display, it should show the same reading as in Nest

## Steps to Reproduce (for bugs)

In the NST manager, temperature display shows 0 even though on the Nest  it has been set to 21dc

1.
2.
![screenshot_20180102-152318](https://user-images.githubusercontent.com/16308585/34498814-4620806e-efd1-11e7-81a9-1874989b0284.png)

3.
4.

## Context

Please include a copy of your log under the IDE if possible

**Comment by imnotbob** [comment]
You should post IDE logs as a private message in the Smartthings community forum to:

WB70   @E_Sch and @tonesto7

**Comment by jharris45** [comment]
I have this same issue - was this ever resolved?
