### ISSUE TITLE
Testing issues with Nest Protect

### ISSUE THREAD

**Issue by maforshaw** [tonesto7/nest-manager#53]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 0
- How many Protects? 6
- Are you Using the Nest Presence Device? No
- iOS or Android?: iOS
- Mobile App Version: 2.1.0
## Steps to Reproduce (for bugs)

Edit a Nest Protect device and change the Testing State to "Smoke Alert". Refresh the device and the smoke icon changes to "Unknown". Looking at the source code for the device handler, the problem is it is looking for a state of "detected" when it should be looking for "emergency". The icon uses the "Nestsmoke" device, not the ST device.

In addition, the testing state only lasts for a few seconds and then becomes confused. Looking at the device current states in the IDE, it looks like a normal refresh is overwriting the test states but not all of them. I haven't worked out what in the code is doing that yet but it has something to do with "parent.refresh" in the refresh method.

**Comment by maforshaw** [comment]
I was able to fix the mixed states by moving "parent.refresh()" in the "refresh" method from the end of the "switch" block to just above it (but still inside the testMode block). It takes a few clicks of refresh to change the state but seems to work. I don't know if that was really the right thing to do though.

**Comment by desertblade** [comment]
Thanks for the defect and troubleshooting.  I am reworking it and it should be more reliable.  Still might take 1-2 refreshes, but much better than before.
