### ISSUE TITLE
NST Manager no longer setting Home/Away status

### ISSUE THREAD

**Issue by bendeitch** [tonesto7/nest-manager#530]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 4
* How many Cameras? 3
* Using the Nest Presence Device? No
* Using the Nest Weather Device? No
* iOS or Android?: Android
* Mobile App Version: Latest

I only use the Thermostat device and the mode automation. I haven't selected any of my other nest devices to be created.

## Expected Behavior
When using the mode automation the Nest Home/Away status should change as the SmartThings mode changes.

## Current Behavior
This automation has been working without problems up until the last couple of days. Now, the heating mode is changed to Eco (even though I don't have the "set heating to Eco" setting ticked in the automation) but the Nest Home/Away status is unchanged.

Weirdly, it seems as if the Nest behaviour in terms of sending notifications for camera events is correctly switching on and off as if the Home/Away status was being changed, it's just the status in the Mobile App and Nest Website are still being shown unchanged.

## Steps to Reproduce (for bugs)
1. Configure mode automation with Home->Home, and Away->Away, (set Eco = false)
2. Change SmartThings mode from Home->Away
3. Wait for Nest heating to change to Eco
4. Verify that Nest status is still Home

## Context

Please include a copy of your log under the IDE if possible
79cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:20:02 AM: debug Sync Nest Mode To SmartThings | scheduleAutomationEval: Skipping Schedule Change: (90sec) because (15sec) Left
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:20:02 AM: trace | Sync Nest Mode To SmartThings | setAway(false): | Thermostat: Nest Thermostat - Heating setting to HOME
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:20:00 AM: info ||| Sync Nest Mode To SmartThings | checkNestMode: The ST Mode (Home) has triggered Nest 'Home'
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:20:00 AM: trace | Sync Nest Mode To SmartThings | PRESENCE Event | Device: Nest Thermostat - Heating | Value: (Present) with a delay of 36ms
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:19:43 AM: trace | Sync Nest Mode To SmartThings | MODE Event | Device: Home | Value: (Home) with a delay of 24ms
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:19:03 AM: debug Sync Nest Mode To SmartThings | scheduleAutomationEval: Skipping Schedule Change: (90sec) because (16sec) Left
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:19:03 AM: trace | Sync Nest Mode To SmartThings | setAway(true): | Thermostat: Nest Thermostat - Heating setting to AWAY
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:19:00 AM: info ||| Sync Nest Mode To SmartThings | checkNestMode: The ST Mode (Away) has triggered Nest 'Away'
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:19:00 AM: trace | Sync Nest Mode To SmartThings | PRESENCE Event | Device: Nest Thermostat - Heating | Value: (Not present) with a delay of 42ms
5479cff1-bdbd-4220-9a36-fe96a1d6f5f4  8:18:46 AM: trace | Sync Nest Mode To SmartThings | MODE Event | Device: Home | Value: (Away) with a delay of 24ms

5829a012-7615-4f7d-82cd-005bd4766918  8:20:18 AM: debug Nest Location Home Watchdog | scheduleAutomationEval: Skipping Schedule Change: (39sec) because (1sec) Left
5829a012-7615-4f7d-82cd-005bd4766918  8:20:18 AM: trace | Nest Location Home Watchdog | NESTTHERMOSTATMODE Event | Device: Nest Thermostat - Heating | Value: (Heat) with a delay of 42ms
5829a012-7615-4f7d-82cd-005bd4766918  8:20:00 AM: debug Nest Location Home Watchdog | scheduleAutomationEval: Skipping Schedule Change: (36sec) because (19sec) Left
5829a012-7615-4f7d-82cd-005bd4766918  8:20:00 AM: trace | Nest Location Home Watchdog | PRESENCE Event | Device: Nest Thermostat - Heating | Value: (Present) with a delay of 33ms
5829a012-7615-4f7d-82cd-005bd4766918  8:19:44 AM: trace | Nest Location Home Watchdog | MODE Event | Device: Home | Value: (Home) with a delay of 32ms
5829a012-7615-4f7d-82cd-005bd4766918  8:19:00 AM: debug Nest Location Home Watchdog | scheduleAutomationEval: Skipping Schedule Change: (40sec) because (21sec) Left
5829a012-7615-4f7d-82cd-005bd4766918  8:19:00 AM: trace | Nest Location Home Watchdog | PRESENCE Event | Device: Nest Thermostat - Heating | Value: (Not present) with a delay of 50ms
5829a012-7615-4f7d-82cd-005bd4766918  8:18:46 AM: trace | Nest Location Home Watchdog | MODE Event | Device: Home | Value: (Away) with a delay of 26ms

71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:10 AM: info ||| NST Manager | API Device Data HAS Changed (POLL(ASYNC))
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:09 AM: info ||| NST Manager | Updating Structure Data (Last Updated: 59 seconds ago) | Updating Device Data (Last Updated: 59 seconds ago) (async)
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:05 AM: info ||| NST Manager | nestCmdResponse | Processed Queue: 0 | Obj: (structures{away:home}) SUCCESSFULLY!
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:04 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: knVTiLGyvCLyTbALXYSkXuk3icVe1CzMb8hd5yiSgL1ZXONn923vbw | ObjType: structures | ObjKey: away | ObjVal: home | QueueNum: 0 | Redirect: true]
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:04 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: knVTiLGyvCLyTbALXYSkXuk3icVe1CzMb8hd5yiSgL1ZXONn923vbw | ObjType: structures | ObjKey: away | ObjVal: home | QueueNum: 0 | Redirect: false]
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:04 AM: trace | NST Manager | workQueue │ Run Queue: 0 | (async)
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:00 AM: info ||| NST Manager | schedNextWorkQ │ queue: 0 │ schedTime: 4 │ recentSendCmd: 2 │ last seconds: 56 │ cmdDelay: 4 │ allowAsync: true
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:00 AM: info ||| NST Manager | Adding Cmd to Queue 0 (qsize: 1): knVTiLGyvCLyTbALXYSkXuk3icVe1CzMb8hd5yiSgL1ZXONn923vbw, structures, away, home, J7hJK6uYdTzri-eSsebxK-znnFuYJR_X
71be866c-0a68-4e8f-bdd3-3b350db542da  8:20:00 AM: debug NST Manager | setStructureAway - Setting Nest Location: (Nest Thermostat - Heating) J7hJK6uYdTzri-eSsebxK-znnFuYJR_X to (Home)
71be866c-0a68-4e8f-bdd3-3b350db542da  8:19:10 AM: info ||| NST Manager | API Device Data HAS Changed (POLL(ASYNC))
71be866c-0a68-4e8f-bdd3-3b350db542da  8:19:09 AM: info ||| NST Manager | Updating Structure Data (Last Updated: 40 seconds ago) | Updating Device Data (Last Updated: 40 seconds ago) (async)
71be866c-0a68-4e8f-bdd3-3b350db542da  8:19:05 AM: info ||| NST Manager | nestCmdResponse | Processed Queue: 0 | Obj: (structures{away:away}) SUCCESSFULLY!
71be866c-0a68-4e8f-bdd3-3b350db542da  8:19:04 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: knVTiLGyvCLyTbALXYSkXuk3icVe1CzMb8hd5yiSgL1ZXONn923vbw | ObjType: structures | ObjKey: away | ObjVal: away | QueueNum: 0 | Redirect: true]
71be866c-0a68-4e8f-bdd3-3b350db542da  8:19:04 AM: trace | NST Manager | Processing Queued Cmd: [ObjId: knVTiLGyvCLyTbALXYSkXuk3icVe1CzMb8hd5yiSgL1ZXONn923vbw | ObjType: structures | ObjKey: away | ObjVal: away | QueueNum: 0 | Redirect: false]
71be866c-0a68-4e8f-bdd3-3b350db542da  8:19:04 AM: trace | NST Manager | workQueue │ Run Queue: 0 | (async)

**Comment by imnotbob** [comment]
Smartthings has been having platform issues...see their status pages for details.

I suggest you go into nest manager, and hit "save";  this will reset the smart apps and dths.    There is nothing in your IDE logs that match what you describe - not uncommon when the platform is having problems.

**Comment by bendeitch** [comment]
I have tried adding and removing the thermostat device, the automation and saved multiple times. I've also removed the SmartApp and re-added it. Doesn't seem to make any difference. With the SmartThings platform status, there are no outages here in the UK. Also, the Eco and Cam notifications behaviour is still acting as if the mode is correctly being changed - it's just the the app and website are still showing the Nest status as "Home". I wonder if it's a change on Nest's side. Perhaps they've altered the logic/API relating to displaying/setting overall Home/Away status as part of their updates for the new Nest Secure?

**Comment by imnotbob** [comment]
I don't think Nest changed things.  I have myself seen a lot of weirdness (even today) with the continued ST platform issues.   I suggest you do another go into nest manager and hit save.  You might want to engage WB70 in the Smartthings forums to see if he can otherwise look at your environment for issues.

**Comment by bendeitch** [comment]
Seems like you were right :) the issue seems to have gone away for now. Thanks.
