### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by philip-thomas** [tonesto7/nest-manager#536]
Copied and pasted the new Nest Manager code in to the IDE environment over the previous version, upon saving the code before publishing received the error below. Update of the Nest automation code to the latest version went without a problem.

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script_app_metadata_141f5bd5_e604_4c7e_873b_65b16e205f39: 2188: unexpected token: * @ line 2188, column 1.
*/
^

1 error

Phil

**Comment by tonesto7** [comment]
sorry bout that seems to have been a code merge issue..  I've corrected it and you can try again
