### ISSUE TITLE
Nest Manager 5.3.2 Error pulling from github nor does it compile when loaded directly from code.

### ISSUE THREAD

**Issue by jgagnon5541** [tonesto7/nest-manager#537]
When I update from repo I get:
Error
500: Internal Server Error
URI
/ide/app/doRepoUpdates
Reference Id
4ff18a8c-b157-4382-957a-d60529040dac

If I try to load the smartapp manually I get a compile error:
startup failed: script_app_metadata_e7505da2_298e_4df0_8dac_a9bbf1baaaa7: 2188: unexpected token: * @ line 2188, column 1. */ ^ 1 error

**Comment by tonesto7** [comment]
sorry bout that seems to have been a code merge issue..  I've corrected it and you can try again
