### ISSUE TITLE
Nest protect light (feature request)

### ISSUE THREAD

**Issue by erlendaakre** [tonesto7/nest-manager#545]
It would be nice (if possible) to be able to turn on the nest protects pathlight from ST.
This could be useful for lighting the hallway during a power cut for example, without having to walk directly under it first.

**Comment by imnotbob** [comment]
Unfortunately Nest API does not provide this access/control 
See:
http://thingsthataresmart.wiki/index.php?title=NST_Manager

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Other_Feature_Requests
