### ISSUE TITLE
UI Issues on iPhone7 plus but not iPhone 6s

### ISSUE THREAD

**Issue by jordansmith74** [tonesto7/nest-manager#547]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* How many Cameras? 2
* Using the Nest Presence Device? No
* Using the Nest Weather Device? Yes
* iOS or Android?: iOS
* Mobile App Version: iOS 11.2.5 & Smartthings 2.14.0

## Expected Behavior

I set up the Smartthings app on my wife's iPhone 6s and the UI looks perfect. I look at it on my iPhone 7plus and I would expect similar looks.

## Current Behavior

When I click on any nest device I get a red message that says 'An Unexpected Error Occurred' and the UI is off.

## Steps to Reproduce (for bugs)

1. Go to any nest device on an iPhone 7plus. 
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible

![img_4623](https://user-images.githubusercontent.com/36131803/35789534-79e2e09a-0a02-11e8-8c7d-5e4698fb1f51.PNG)

**Comment by jordansmith74** [comment]
Turned on logging for all Nest devices and can't get any errors or valuable information to send over.

**Comment by imnotbob** [comment]
smartthings has said this error message was due to an update they did last week.  They state they have resolved the issue today.

**Comment by jordansmith74** [comment]
Yep it seems to be working just fine now. Thanks
