### ISSUE TITLE
No write permissions Code 400

### ISSUE THREAD

**Issue by aero77** [tonesto7/nest-manager#549]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?:  **1**
* How many Protects? 
* How many Cameras?
* Using the Nest Presence Device?  **Y**
* Using the Nest Weather Device?  **Y**
* iOS or Android?:  **Android**
* Mobile App Version:   **2.14.0**

## Expected Behavior

Change the temperature settings on the device.

## Steps to Reproduce (for bugs)

1. Adjust temperature up or down.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible

5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:04:15 PM: info ||| NST Manager | No Device or Structure poll - Devices Last Updated: 39 seconds ago | Structures Last Updated 39 seconds ago
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:36 PM: info ||| NST Manager | API Device Data HAS Changed (POLL(ASYNC))
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:36 PM: info ||| NST Manager | Updating Structure Data (Last Updated: 141 seconds ago) | Updating Device Data (Last Updated: 321 seconds ago) (async)
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:32 PM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): target_temperature_f) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:32 PM: error nullLogger Error - type: error | msg: null | logSrc: Manager
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:32 PM: debug NST Manager | sendMsg: Sent Push Message Message Sent: Nest Manager API CMD Failed: The (nestCmdResponse 0 (devices/thermostats{target_temperature_f:75})) CMD sent to the API has failed. Status Code: 400 ErrorMsg: No write permission(s) for field(s): target_temperature_f DT: Tue Feb 06 15:03:32 EST 2018
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:32 PM: warn || NST Manager | [nestCmdResponse] | Status: (400) | Error Message: [message:No write permission(s) for field(s): target_temperature_f, details:[fields:target_temperature_f], error:No write permission(s) for field(s): target_temperature_f, instance:c2cc8ab0-3c0f-40bc-8b1a-f6df4b677899, type:https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:31 PM: trace | NST Manager | Processing Queued Cmd: [ObjId: 7_GZVoQ8OPclNBgfszNI-a35vqKjXE8z | ObjType: devices/thermostats | ObjKey: target_temperature_f | ObjVal: 75 | QueueNum: 0 | Redirect: true]
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:31 PM: trace | NST Manager | Processing Queued Cmd: [ObjId: 7_GZVoQ8OPclNBgfszNI-a35vqKjXE8z | ObjType: devices/thermostats | ObjKey: target_temperature_f | ObjVal: 75 | QueueNum: 0 | Redirect: false]
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:31 PM: trace | NST Manager | workQueue │ Run Queue: 0 | (async)
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:27 PM: info ||| NST Manager | schedNextWorkQ │ queue: 0 │ schedTime: 4 │ recentSendCmd: 3 │ last seconds: 452 │ cmdDelay: 4 │ allowAsync: true
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:27 PM: info ||| NST Manager | Adding Cmd to Queue 0 (qsize: 1): 7_GZVoQ8OPclNBgfszNI-a35vqKjXE8z, devices/thermostats, target_temperature_f, 75, 7_GZVoQ8OPclNBgfszNI-a35vqKjXE8z
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:03:27 PM: debug NST Manager | setTargetTemp | Setting Thermostat (Nest Thermostat - Living Room - 7_GZVoQ8OPclNBgfszNI-a35vqKjXE8z) Target Temp to (75°F)
5bfad9ac-15ff-4665-b42d-67258e69fb4a  3:01:15 PM: info ||| NST Manager | Updating Structure Data (Last Updated: 180 seconds ago) | Updating Device Data (Last Updated: 180 seconds ago) (async)
5bfad9ac-15ff-4665-b42d-67258e69fb4a  2:58:15 PM: info ||| NST Manager | API Device Data HAS Changed (POLL(ASYNC))
5bfad9ac-15ff-4665-b42d-67258e69fb4a  2:58:15 PM: info ||| NST Manager | Updating Structure Data (Last Updated: 136 seconds ago) | Updating Device Data (Last Updated: 136 seconds ago) (async)
5bfad9ac-15ff-4665-b42d-67258e69fb4a  2:55:59 PM: info ||| NST Manager | Updating Structure Data (Last Updated: 224 seconds ago) | Updating Device Data (Last Updated: 43 seconds ago) (async)
5bfad9ac-15ff-4665-b42d-67258e69fb4a  2:55:55 PM: error | NST Manager | nestCmdResponse error - (Status: 400 - No write permission(s) for field(s): target_temperature_f) - [ErrorLink: https://developer.nest.com/documentation/cloud/error-messages#no-write-permission]
5bfad9ac-15ff-4665-b42d-67258e69fb4a  2:55:55 PM: error nullLogger Error - type: error | msg: null | logSrc: Manager

**Comment by imnotbob** [comment]
This suggests you do not have the permissions correct on the nest token you created.

Please check the instructions and ensure the permissions are correct.  You may also need to go into the nest mobile app and "grant" or allow, the new permissions to be used under "Works with Nest"

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Nest_Developer_Account

**Comment by aero77** [comment]
Thanks. I missed checking the correct radio buttons on the read write permissions. Works like a charm now. Thanks
