### ISSUE TITLE
Repo not in Sync with latest version

### ISSUE THREAD

**Issue by ENTHUZD** [tonesto7/nest-manager#550]
It appears that the connection to update my SmartApp and DeviceHandler with the latest from my Forked tonesto7/nest-manager is no longer working. No other changes have been made.

## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* How many Cameras?
* Using the Nest Presence Device?
* Using the Nest Weather Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible

**Comment by ENTHUZD** [comment]
It appears that the connection to update my SmartApp and DeviceHandler with the latest from my Forked tonesto7/nest-manager is no longer working. No other changes have been made.

**Comment by imnotbob** [comment]
It would be good to see IDE logs or some other error messages.
