### ISSUE TITLE
Can Window/Contact Open switch the thermostat mode to Off instead of Eco?

### ISSUE THREAD

**Issue by DesignFlaw06** [tonesto7/nest-manager#558]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 2
* How many Protects? 0
* How many Cameras? 0
* Using the Nest Presence Device? 0
* Using the Nest Weather Device? 0
* iOS or Android?: Android
* Mobile App Version: 2.14.0 Build 218570

## Expected Behavior
I use a Nest Thermostat for my garage heat.  I would like it to switch the thermostat to Off instead of Eco so I'm not heating outdoors when the garage door is open.  

## Current Behavior
The only option I have to is to switch the thermostat to Eco mode when a contact is open.  

## Context
Ideally, I'd like to leave my garage at 40 degrees unless I'm working in it.  The Heat mode with the Nest only allows a 50 degree minimum setpoint so I use Eco mode when I'm not working in the garage.  But I also don't want to run the heat if the garage door is opened.

**Comment by tonesto7** [comment]
I'm pretty sure that this is already (always has been)

**Comment by DesignFlaw06** [comment]
The only option I see under the Contact Automation is "Set ECO if Door/Window Contact open?".  How do I set it to go to Off instead of Eco then?
