### ISSUE TITLE
Automation shows "State Usage is Greater than 80%"

### ISSUE THREAD

**Issue by PeteBoyRocket** [tonesto7/nest-manager#569]
## Verify the following before opening an issue:

- [x ] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [ x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [ x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* How many Cameras? 2
* Using the Nest Presence Device? Yes
* Using the Nest Weather Device? Yes
* iOS or Android?: Android
* Mobile App Version: v2.15.1 build 218914

## Expected Behavior
Tapping the NST Manager automation should allow me to configure it.

## Current Behavior

Tapping the NST Manager automation shows this message:

![image](https://user-images.githubusercontent.com/1651763/38825921-1d83755e-41a6-11e8-93eb-614761f20aaf.png)

I'm unable to do anything with the automation at this point. Including uninstalling it.

Hacking this line https://github.com/tonesto7/nest-manager/blob/master/smartapps/tonesto7/nest-manager.src/nest-manager.groovy#L152

to `(stateSz > 180)` Lets me use it again. _seems_ to work ok. See this in the diagnostics page after doing that:
![image](https://user-images.githubusercontent.com/1651763/38826009-6a2217c6-41a6-11e8-8a54-2e4ab1786142.png)
And this:
![image](https://user-images.githubusercontent.com/1651763/38826018-730f894a-41a6-11e8-975f-a8d8529c55b6.png)

## Steps to Reproduce (for bugs)
1.Tap the NST Manager automation

## Context

Please include a copy of your log under the IDE if possible
https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/a6832cdd-c230-4b51-8bef-0e501da8c70a/diagHome?access_token=70991a52-67b1-4b7f-b859-b6ab33635612

**Comment by jacobwtyler** [comment]
same issue here

**Comment by tonesto7** [comment]
@PeteBoyRocket  @jacobwtyler 
I see the cause.  For some reason, your install kept building up commands into the queue until it filled up the entire state memory.  Are you able to open the smart app at all?

If you can then open it and press Done.  That should call the stateCleanup() function and clear out the queues. 

If that doesn't work but you can get into the SmartApp still than go into Application Preferences > Logging > Toggle Reset Application Data > Press Done all the way out to the main smart apps list.

**Comment by PeteBoyRocket** [comment]
I can open it, but I suspect thats because I still have the hacked `stateSz > 180` line.
I opened it and pressed Save in the top right until it took me back to the smart app screen.
Now when I open it it seems to think its doing a first install, asking me to selectg my location and devices. Stepping through this makes it 'Save', but it doesn't seem to configure anything. Every time I reopen it it repeats this.
Trying to uninstall the smart app at the moment, It doesn't seem to let me via the Android app, and the developer console says I can't delete it because it is installed by a user!
May have to contact SmartThings support...

**Comment by PeteBoyRocket** [comment]
Ok, removing all of the nest devices THEN uninstalling it is how to remove it! Obvious in hindsight.
Reinstall -> had to create my Nest Developer OAuth secret and client ID -> done.
During install logged in to Nest A-OK, selected devices etc and clicked save. Appears to save ok, but opening the Nest Manager takes me to the 'Select your devices' page of the installer, and none of the devices were added.

Next I'll try uninstalling it, then remove all the Nest Manager Smartapp and device handler code. Aka as clean as I can get it and start from scratch

**Comment by PeteBoyRocket** [comment]
Good news! whatever the issue was doing this seems to have fixed it!

- complete uninstall of devices and smartapp via the Android app
- remove the smartapp and device handlers from the developer console
- Follow initial install instructions

@jacobwtyler Can you try this? If this fixes your issue, I guess we can close this, unless @tonesto7 wants to do anything further with it.

**Comment by jacobwtyler** [comment]
@tonesto7 I don't have any options when I click on the SmartApp.  It only displays the message 

> ...Your Manager State Usage is Greater than 80% full...

 and the only thing I can click is the back button in the top left or a Save button in the top right.  (I'm on iOS).  I did completely remove all Nest devices from SmartThings and then removed the SmartApp via the IDE and then reinstalled NST Manager and added all my devices back successfully and I thought everything was fixed so I went into WebCoRE and set my pistons back up the way I had them.  Then I decided to click on the SmartApp again and the message was back.  I'm going to try removing everything again.  

![nest manager status error smartthings](https://user-images.githubusercontent.com/18349823/39678695-b47a47ca-5156-11e8-8454-ccc2b9180425.jpeg)

**Comment by jacobwtyler** [comment]
Removed all 12 cameras, 1 thermostat and 6 Protects again and uninstalled the SmartApp via IDE and created new OAuth and reinstalled.  Once again, everything installed fine and I get everything set up.  This time, I went right back into the SmartApp and it did allow me in.  I looked for the 

> Application Preferences > Logging > Toggle Reset Application Data > Press Done 

section that you referenced and found nothing of the sort.  A few seconds after looking around in the SmartApp, ST pushed a notification which just read "Info:  ".  This looked familiar and it happened last time as well I believe.  Anyhow, after that notification, I could no longer get into the SmartApp.  It just gives me the 80% full message again.  Any ideas?

**Comment by jacobwtyler** [comment]
Also can’t seem to install the NST Automations SmartApp although I’m not sure I was supposed to.

**Comment by jacobwtyler** [comment]
I got it to install if I didn’t add my 12 cameras and I was able to view the logging section. It was 78% without the cameras and I tried the reset application data. It it didn’t free up any space. As soon as I add the cameras back, it goes up to 84% and I had a quick chance to try the reset application data again but it did nothing again. Then it gives me an “info:” notification and I can no longer get into the SmartApp. Only the 80% message.

**Comment by imnotbob** [comment]
Do you have the weather device enabled?
How many locations do you have?
I have made some changes to reduce state, but I'm curious how many devices you have in total (cameras, thermostats, etc across all your locations)

**Comment by jacobwtyler** [comment]
@imnotbob, currently I do not have the weather device enabled but I did when this started. Total devices:
12 cameras
7 protects
1 thermostat
1 Presence Sensor
1 Weather Sensor

In order to get my manager state down to 78%, I’ve eliminated the weather sensor and all 12 cameras.

**Comment by imnotbob** [comment]
I created some changes to reduce state usage.   Once tony has a look at them he can share them out.

After that I would like to see you data in the web diagnostics (I don't need logging on)

**Comment by imnotbob** [comment]
Likely this should move to private messages in the forum

**Comment by jacobwtyler** [comment]
Your update got me down to 55% WITH the cameras added back. Thanks so much!
