### ISSUE TITLE
Nest Thermostat “cannot adjust temp from SmartThings mobile app”

### ISSUE THREAD

**Issue by cpmorris1001** [tonesto7/nest-manager#578]
The Nest Thermostat will no longer accept commands from the SmartThings mobile app.  I try and change the temperature with either the up or down arrows and the value on the screen does not change.
1) I received notification that an update was available
2) I delayed the update process for a long time, I’m not sure but I think functionality stopped prior to the update.
3)I’m very sure that functionality has not been there after the update
4) I noticed that clientId and clientSecrect were blank after my update.  I went to the Nest site and copied them and pasted.  I wanted to check these tokens but I’m such a neophyte I cant find them again.

I’ve been working this for weeks without success.  I’m to my witts end.  I’m ready to totally uninstall and try a fresh reinstall or buy an ecobee.  I have hope a little guidance can get me through this.

## Verify the following before opening an issue:

- [ ] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ [x]] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [ x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 0
* How many Cameras? 0
* Using the Nest Presence Device? 0
* Using the Nest Weather Device? 0
* iOS or Android?: iOS
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.Open SmartThings mobile app
2.Open Nest icon from SmartThings mobile app
3.Try to adjust temperature up or down with arrow keys.  The temp on the screen will not change.
![cc6b041e-6fec-4500-b6f6-1bad4161babf](https://user-images.githubusercontent.com/37513441/41973251-a9a3cd5a-79d1-11e8-9163-b75de97a7384.png)
![7dac58bc-6298-4320-b230-e8f339d8b8ec](https://user-images.githubusercontent.com/37513441/41973252-a9bb075e-79d1-11e8-987d-bb66b8b04fee.png)

4.

## Context
 I’m trying to change the temperature from my mobile app

Please include a copy of your log under the IDE if possible

**Comment by cpmorris1001** [comment]
It appears... but I’m not sure that the temps and modes are being modified by my Webcore piston

**Comment by cpmorris1001** [comment]
1) I found my way back to the Nest developers site and re-copied and pasted tokens
2) I’ve added a screen shot of the FW versions from the tiles
3) I made the statement that I thought my Webcore was making adjustments.  I’ve added a screen shot of why I think the temp is being adjusted
4)
![7c6623d3-bace-4ec2-8203-32480ab36aa7](https://user-images.githubusercontent.com/37513441/41974994-bc02631c-79d6-11e8-908a-127d8f5d6d3f.png)
![afab0935-4532-40de-b3f8-ee3f291892fb](https://user-images.githubusercontent.com/37513441/41974995-bc1dc468-79d6-11e8-9feb-65dc9f32c9ad.png)

**Comment by tonesto7** [comment]
Forgive cause it's still early for me but i am not seeing the issue

**Comment by cpmorris1001** [comment]
Thanks for looking at this.  Note all screen shots are from my iPad .  I’m running iOS 11.4
Please review the screen shot I just added:
1) You see the large blue box on the left with large 72° and the two white circles that form up and down blue arrows.  Touching the up and down arrows will not change the value of 72
2)You will notice the mode is in “cool”.  I cannot change the mode of the thermostat by touching by touching “auto”, “heat”, “off” or “eco”
3)On the right you see the blue circle with the white  72° And blue up and down arrows.  I cannot change the temp by touching the up or down arrows

Essentially I have no control of the thermostat through SmartThings.  I have tried to control the thermostat through my iPhone with no success.  Essentially the same issues.

I hope this this helps.
![4de9ebbf-957d-46ce-b156-067032dc47f6](https://user-images.githubusercontent.com/37513441/42008279-ded14f14-7a41-11e8-8329-841ab3d7ac3f.png)

**Comment by tonesto7** [comment]
Ah... Thanks for clarifying.  Let me take a look.  I'm sure a recent ST mobile app broke something, but I've been known to make mistakes ;)

**Comment by cpmorris1001** [comment]
Thanks for looking.  I’m a MechE in the data storage industry.  I find
99.999999% of problems are user error, so I’m sure I’ve buggered this up
somehow.

Would it help if I provided logs?

**Comment by cpmorris1001** [comment]
Do I need to paste the Authorization URL someplace?

**Comment by lifties** [comment]
I have the same issue.  I got everything working after creating my own Nest app and getting my secret and everything was chumning along fine for awhile. About 3 weeks ago I can't control the thermostat. I can still read the status, but pressing a button does nothing.

**Comment by lifties** [comment]
I should also note that Webcore no longer sees that I have a Thermostat so I can't add it.

**Comment by cpmorris1001** [comment]
So I’m getting ready to do a complete uninstall and reinstall.  I’ll modify my actions based on your response.    May I ask... if I uninstall and reinstall is there a particular procedure?

**Comment by cpmorris1001** [comment]
@lifties. I’ll check and see if my webcore is exhibiting the same symptoms.

**Comment by cpmorris1001** [comment]
Regarding Webcore.  It appears that I can use the webcore generic thermostat but not the Nest

**Comment by cpmorris1001** [comment]
Holy Crap!  I can’t even uninstall this thing!  I get “A unexpected error occurred” during the uninstall process.  Can I get some guidance how to get this off my machine?

**Comment by cpmorris1001** [comment]
@tonesto7  please give me some help here.  I would be happy just removing this.
![9491e9a9-a766-41cb-953e-f43b285e4221](https://user-images.githubusercontent.com/37513441/42124955-316056b4-7c2a-11e8-8695-61cf8177bf82.png)

**Comment by imnotbob** [comment]
In the IDE,  go to:
My Locations -> select your location -> List SmartApps

hit edit at the top
Scroll down to NST Manager
   Uninstall the Automations, watchdogs (one at a time)
   Then uninstall NST Manager
Scroll back up and hit done

Then go to "My Devices"
Scroll down to each Nest device you have (Camera, Protect, Thermostat, weather, presence)
- Select the device
- Scroll down to delete

Then go to "My SmartApps"
- select the paper with a pen in it
- scroll down and hit delete


Then go to "My device handlers"
Select Nest devices
Select "Device Type Settings"
Select delete

Note that Smartthings support can help you if you have problems uninstalling.

**Comment by lifties** [comment]
You can't delete NST Manager until there are no smartapps using the nest devices. 

For me I had to delete each Webcore piston that had a Nest devices. Then you can remove and reinstall NST Manager.

**Comment by cpmorris1001** [comment]
@imnotbob   Thanks!!!

@tonesto7 ... I still need some support.  I’m hoping because I donated, way back when, you can help me here a little bit.
1) I totally uninstalled with the help of imnotbob 
2) I reinstalled
3) During the set up when logging on the the nest account “always” my login fails the first time and “always” works the second time.  I think there might be a clue there?
4) In the configuration section where you instruct:
* Choose Structure
* Choose  Thermostats
* Choose Protects
* Choose Cameras
...
I never have these options

I truely enjoyed the program and would like to keep using it.  Do you think you can guide me through this?

**Comment by imnotbob** [comment]
It would be good to turn on live logging when you start the installation.

I suggest you uninstall, carefully follow the instructions in regards to installation, your nest token and nest account,  then before you begin in the mobile app to install, turn on your IDE and live logging to see what the messages are.

http://thingsthataresmart.wiki/index.php?title=NST_Manager

Note if you installed a lot earlier, there have been instruction changes for installation.

**Comment by lifties** [comment]
I deleted everything, Created a new Nest OAuth Client, reinstalled NST Manager and it still isn't working.  I can read the status, but cant control everything.

Here is my logs during the install, Thermostat and then NST Manager

dd0c99516-831a-43da-9988-f6c1c75e4bb9  7:02:45 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED: DeviceStatus Event: 'online'
d0c99516-831a-43da-9988-f6c1c75e4bb9  7:00:50 PM: debug Nest Thermostat - Downstairs (v5.3.5) | dayNum: 1 currentDay 1 | monthNum: 7 currentMonth 7 | yearNum: 2018 currentYear: 2018
d0c99516-831a-43da-9988-f6c1c75e4bb9  7:00:50 PM: trace || Nest Thermostat - Downstairs (v5.3.5) | updateOperatingHistory(Tue Jul 03 02:00:50 UTC 2018)...
d0c99516-831a-43da-9988-f6c1c75e4bb9  7:00:50 PM: trace || Nest Thermostat - Downstairs (v5.3.5) | initHistoryStore()...
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Comfort Dewpoint Maximum is (0.0) | Original Dewpoint: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Temperature Lock Minimum is (68.0) | Original Temp: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Temperature Lock Maximum is (72.0) | Original Temp: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Safety Temperature Minimum is (0F) | Original Temp: (nullF)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Comfort Humidity Maximum is (80%) | Original Humidity: (null%)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Safety Temperature Maximum is (0F) | Original Temp: (nullF)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Safety Temperature Exceeded is (false) | Current Temp: (nullF) | Min: (0.0F) | Max: (0.0F)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | nestType: (physical) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Firmware Version: (5.8-8) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | API Status is: (Good) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Temperature Unit: (F) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Device Debug Logging is: (Off) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Time to Target: (System is Idle) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | SunLight Correction Enabled: (true) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Online Status is: (online) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED: DeviceStatus Event: 'online'
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | whoSetEcoMode is (Not in Eco Mode) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | SunLight Correction Active: (false) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | NEST Hvac Mode is (Off) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | initialized...
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Device Type Version is: (5.3.5) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Hvac Previous Mode is () | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Hvac Mode is (Off) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Fan Mode: (Auto) | Original State: (Null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | Updating the device's 'isVirtual' data value to (false)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | ST | Nest Presence: Present | Original State: Present | State Variable: null
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:44 PM: debug Nest Thermostat - Downstairs (v5.3.5) | UPDATED | Temperature Lock is set to (false) | Original State: (null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:25 PM: debug repairHealthStatus([flag:true])
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:18 PM: debug repairHealthStatus(null)
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:18 PM: debug Setting virtual to FALSE
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:18 PM: debug initialized...
d0c99516-831a-43da-9988-f6c1c75e4bb9  6:59:13 PM: debug installed...




d547469d-1a0d-4401-a980-2d9394422908  7:05:36 PM: info ||| NST Manager (v5.3.7) | Updating Structure Data (Last Updated: 180 seconds ago) | Updating Device Data (Last Updated: 465 seconds ago) (async)
d547469d-1a0d-4401-a980-2d9394422908  7:02:36 PM: info ||| NST Manager (v5.3.7) | API MetaData Data HAS Changed (POLL(ASYNC))
d547469d-1a0d-4401-a980-2d9394422908  7:02:36 PM: info ||| NST Manager (v5.3.7) | API Device Data HAS Changed (POLL(ASYNC))
d547469d-1a0d-4401-a980-2d9394422908  7:02:36 PM: info ||| NST Manager (v5.3.7) | Updating Structure Data (Last Updated: 286 seconds ago) | Updating Device Data (Last Updated: 285 seconds ago) | Updating Meta Data(Last Updated: 100000 seconds ago) (async)
d547469d-1a0d-4401-a980-2d9394422908  7:01:28 PM: info ||| NST Manager (v5.3.7) | sendFirebaseData({"guid":"e20294af-8082-4cd6-93c9-ebcb4ace3efb","beta":false,"versions":{"apps":{"manager":"5.3.7","automation":"5.3.4","service":"Not Installed"},"devices":{"thermostat":"Not Installed","vthermostat":"Not Installed","protect":"Not Installed","camera":"Not Installed","presence":"Not Installed","weather":"Not Installed"}},"thermostats":1,"protects":0,"vthermostats":0,"cameras":0,"appErrorCnt":0,"devErrorCnt":0,"installDt":"Mon Jul 02 18:58:32 PDT 2018","updatedDt":"Mon Jul 02 18:58:42 PDT 2018","automations":{"nestMode":0,"remDiag":0,"disabled":0,"watchDog":1,"storage":1,"schMot":{"remSen":0,"humCtrl":0,"leakWat":0,"extTmp":0,"tSched":0,"conWat":0,"fanCirc":0,"fanCtrl":0}},"timeZone":"America/Los_Angeles","apiCmdCnt":0,"apiStrReqCnt":1,"apiDevReqCnt":1,"apiMetaReqCnt":0,"appNotifSentCnt":1,"apiRestStrEvtCnt":0,"appUseMetCnt":{"appNotifPrefLoadCnt":0,"autoGlobPrefLoadCnt":0,"devCustNameLoadCnt":0,"camZoneFltLoadCnt":0,"devLocLoadCnt":0,"nestLoginLoadCnt":0,"mainLoadCnt":7,"viewAutoSchedLoadCnt":0,"logPrefLoadCnt":0,"protTestLoadCnt":0,"authLoadCnt":1,"vRprtPrefLoadCnt":0,"prefLoadCnt":0,"autoLoadCnt":0,"helpLoadCnt":0,"chgLogLoadCnt":0,"viewAutoStatLoadCnt":0,"custWeathLoadCnt":0,"notifPrefLoadCnt":0,"diagLoadCnt":0,"pollPrefLoadCnt":0,"devCustLoadCnt":0,"infoLoadCnt":0},"devUseMetCnt":{"tstatVoiceRptCnt":0,"tstatManTmpChgCnt":0,"tstatProgTmpChgCnt":0,"tstatManModeChgCnt":0,"tstatProgModeChgCnt":0,"tstatManFanChgCnt":0,"tstatProgFanChgCnt":0,"tstatHtmlLoadCnt":0},"stateUsage":"16%","mobileClient":"android","datetime":"Mon Jul 02 19:01:28 PDT 2018","optOut":false}, installData/clients/e20294af-8082-4cd6-93c9-ebcb4ace3efb.json, null, heartbeat, false
d547469d-1a0d-4401-a980-2d9394422908  6:59:43 PM: info ||| NST Manager (v5.3.7) | No Device or Structure poll - Devices Last Updated: 112 seconds ago | Structures Last Updated 113 seconds ago
d547469d-1a0d-4401-a980-2d9394422908  6:59:39 PM: info ||| NST Manager (v5.3.7) | Installing watchDog
d547469d-1a0d-4401-a980-2d9394422908  6:59:36 PM: debug NST Manager (v5.3.7) | sendMsg: Sent Broadcast Message Sent: Info:
d547469d-1a0d-4401-a980-2d9394422908  6:59:36 PM: info ||| NST Manager (v5.3.7) | No Device or Structure poll - Devices Last Updated: 105 seconds ago | Structures Last Updated 106 seconds ago
d547469d-1a0d-4401-a980-2d9394422908  6:59:34 PM: info ||| Nest Manager (v5.3.7) | createSavedNest | Cameras(0): null
d547469d-1a0d-4401-a980-2d9394422908  6:59:34 PM: info ||| Nest Manager (v5.3.7) | createSavedNest | Protects(0): null
d547469d-1a0d-4401-a980-2d9394422908  6:59:34 PM: info ||| Nest Manager (v5.3.7) | createSavedNest | Thermostats(1): [uBVavAV6G6h8GXzW7i66NTOsMn55SFXt]
d547469d-1a0d-4401-a980-2d9394422908  6:59:13 PM: info ||| Nest Manager (v5.3.7) | POLL scheduled (36 2/3 * * * ?)
d547469d-1a0d-4401-a980-2d9394422908  6:59:13 PM: debug Nest Manager (v5.3.7) | Created Devices; Current Devices: (1) Thermostat(s), (0) Virtual Thermostat(s), (0) Protect(s), (0) Cameras(s), 0 Presence Device and 0 Weather Device
d547469d-1a0d-4401-a980-2d9394422908  6:59:13 PM: debug Nest Manager (v5.3.7) | Created: Nest Thermostat - Downstairs with (Id: uBVavAV6G6h8GXzW7i66NTOsMn55SFXt)
d547469d-1a0d-4401-a980-2d9394422908  6:59:13 PM: trace | Nest Manager (v5.3.7) | stateCleanup
d547469d-1a0d-4401-a980-2d9394422908  6:58:52 PM: info ||| Nest Manager (v5.3.7) | devicePage | Cameras(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:52 PM: info ||| Nest Manager (v5.3.7) | devicePage | Protects(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:52 PM: info ||| Nest Manager (v5.3.7) | devicePage | Thermostats(1): [uBVavAV6G6h8GXzW7i66NTOsMn55SFXt]
d547469d-1a0d-4401-a980-2d9394422908  6:58:52 PM: debug Nest Manager (v5.3.7) | Nest Manager Updated...with settings: [enRemDiagLogging:false, weatherDevice:false, optInSendExceptions:true, presDevice:false, liteAppMode:false, structures:DLCvces2iXL_SzgLTMly02uBZNBDw80T6ffDOxyYOFKOpz8WbgZXRQ, mobileClientType:android, optInAppAnalytics:true, thermostats:[uBVavAV6G6h8GXzW7i66NTOsMn55SFXt]]
d547469d-1a0d-4401-a980-2d9394422908  6:58:48 PM: info ||| Nest Manager (v5.3.7) | devicePage | Cameras(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:48 PM: info ||| Nest Manager (v5.3.7) | devicePage | Protects(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:48 PM: info ||| Nest Manager (v5.3.7) | devicePage | Thermostats(1): [uBVavAV6G6h8GXzW7i66NTOsMn55SFXt]
d547469d-1a0d-4401-a980-2d9394422908  6:58:45 PM: info ||| Nest Manager (v5.3.7) | devicePage | Cameras(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:45 PM: info ||| Nest Manager (v5.3.7) | devicePage | Protects(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:45 PM: info ||| Nest Manager (v5.3.7) | devicePage | Thermostats(0): []
d547469d-1a0d-4401-a980-2d9394422908  6:58:32 PM: debug Nest Manager (v5.3.7) | Nest Manager Updated...with settings: [optInSendExceptions:true, liteAppMode:false, mobileClientType:android, optInAppAnalytics:true]
d547469d-1a0d-4401-a980-2d9394422908  6:58:32 PM: debug Nest Manager (v5.3.7) | Installed with settings: [optInSendExceptions:true, liteAppMode:false, mobileClientType:android, optInAppAnalytics:true]
d547469d-1a0d-4401-a980-2d9394422908  6:57:47 PM: info ||| Nest Manager (v5.3.7) | Nest AuthToken Generated SUCCESSFULLY
d547469d-1a0d-4401-a980-2d9394422908  6:57:27 PM: warn || Nest Manager (v5.3.7) | Missing: structData null
d547469d-1a0d-4401-a980-2d9394422908  6:57:25 PM: info ||| Nest Manager (v5.3.7) | AuthToken not found: Directing to Login Page
d547469d-1a0d-4401-a980-2d9394422908  6:57:24 PM: info ||| Nest Manager (v5.3.7) | appData.json File HAS Changed

**Comment by cpmorris1001** [comment]
@imnotbob do you want me to use the community installer?  .or. Install manually?  Last time I used the community installer.
The install seems ok but when I go to link my nest developers the behavior is strange:
1) when i first try to enter the nest credentials, I get to the login of the  nest developers site I always get an error. “Oops we encountered an error.  Please try again”
2) Always on the second try the login works
3) I don’t get the list of questions per the instructions
![9b7aeb7a-5073-47a3-8d01-710a8ff196ef](https://user-images.githubusercontent.com/37513441/42195616-fb05c9d2-7e36-11e8-963c-d1a1f7e69522.png)
![976dce1d-c643-4b4f-a2db-6760788ee248](https://user-images.githubusercontent.com/37513441/42195617-fb2a8146-7e36-11e8-9461-5fca19610a9e.png)
![3633914e-603e-481d-a576-41b1169b75a8](https://user-images.githubusercontent.com/37513441/42195618-fb54d4dc-7e36-11e8-93fd-1d5a45bbcc2d.png)
![c5743788-9aeb-43bb-a7d4-5cfa95f97ec4](https://user-images.githubusercontent.com/37513441/42195619-fb66518a-7e36-11e8-9d99-2d6688388a63.jpeg)
![e473b8af-ec8d-45d1-b7c2-a501563b4185](https://user-images.githubusercontent.com/37513441/42195657-2aea0af0-7e37-11e8-8219-42c8595ce75c.png)

**Comment by imnotbob** [comment]
@lifties 

The logs you show seem to show us getting data from nest properly and the thermostat updates.

Is it not working for you?   if so would need to see more logs as there are no errors after you successfully logged in.

The logs do not show you attempting any commands to nest.   They also were stopped so I don't see the regular updates happening.

**Comment by imnotbob** [comment]
@cpmorris1001 

It would be good to turn on live logging when you start the installation.

I suggest you uninstall, carefully follow the instructions in regards to installation, your nest token and nest account, then before you begin in the mobile app to install, turn on your IDE and live logging to see what the messages are.

http://thingsthataresmart.wiki/index.php?title=NST_Manager

Note if you installed a lot earlier, there have been instruction changes for installation.

**Comment by lifties** [comment]
@imnotbob 

When I attempt to control my Nest thermostat with logging turned on, it doesn't create any log activities.  I get feedback sound and visual that I'm selecting an button (i.e. change mode), but it doesn't do anything and no logs messages are generated.

And a little backstory:  I created my own Works with Nest app and everything was working fine for a while.  Then I noticed that my Webcore pistons weren't operating correctly.  Webcore seemed to lose the Nest device ID and had a long string of numbers instead of the normal name.  Webcore didn't register that I had a Thermostat.  And that is still true with this latest install of NST Manager.  I even followed the instructions and created a new Nest OAclient for this latest attempt.

I'm stumped.

**Comment by imnotbob** [comment]
There should be some log messages if you attempt to make changes via the smartthings app.

Use the classic smartthings app (not the new one)

Follow the instructions carefully.  http://thingsthataresmart.wiki/index.php?title=NST_Manager

Do not skip any steps.   Ensure you are using the proper smartthings shard.

If you are unsure when starting if you have deleted everything for nest from smartthings, contact smartthings support to help on the uninstall portions.

It may be good to chat with smartthings support to ensure nothing is wonky with your account or the classic smartthings mobile app.

**Comment by cpmorris1001** [comment]
@imnotbob 
First and foremost thanks for trying to help me through this.  Before I reinstall I turned on the IDE logs and i thought you would find the results very interesting, it appears the NST manager is not seeing  the Nest tokens.  Would you still like me to uninstall and reinstall or do something else?

Also, last time I reinstalled I used the community installer.  Do you want me to do that again .or. would you like me to use the manual process described in wiki?
![bb5071e5-ab10-4f07-96de-5983353b46e2](https://user-images.githubusercontent.com/37513441/42277670-69d32bb0-7f55-11e8-9fc9-905483325b01.png)

**Comment by imnotbob** [comment]
The logs you posted above (couple days ago did not show this error).

You must use the primary nest account when authenticating with Nest (no family or add on account).

I suggest installing using the github integration method just to keep things out of the equation.   I have heard some folks say with the community installer they had to go back in and hit save, publish for me manually.

If you delete everything, clear our in the Nest mobile app and ST integration before restarting the install.

**Comment by cpmorris1001** [comment]
@imnotbob  there are two of us with the same issue, cpmorris1001 and @lifties .  These are the first logs that I, cpmorris1001 have posted logs

I need a little more description.  You said “If you delete everything, clear our in the Nest mobile app and ST integration before restarting the install.”  I don’t understand what your telling me can you give me a little more description?

Also, can I regenerate a new token at Nest Developers website? And should I?

Thanks

**Comment by imnotbob** [comment]
I would ensure in the IDE that everything for nest is removed.

Check that you created your token correctly in the nest site, and all field are properly filled in.

**Comment by imnotbob** [comment]
also, likely should start separate threads, as I don't think you are having the same issues.

**Comment by cpmorris1001** [comment]
@imnotbob ...I’m so close but I screwed up.  I picked the wrong location during installation.  I had three locations in NEST and I tapped the wrong damn one...  ACK!  Do I have to uninstall again and reinstall or can I just select a different location?  I’ve been trying to figure out how to just select a different location but I’ve been unsuccessful thus far.
![775ea671-a5d0-4875-bfcc-14b5f43d30fa](https://user-images.githubusercontent.com/37513441/42295044-b01c3b40-7fa3-11e8-8dc0-eab44fcc995a.jpeg)

**Comment by imnotbob** [comment]
If you remove the devices for the current location 

ie turn presence off, weather off, hit save/done  you way out

When you go back in, you should be able to select/change locations.

**Comment by cpmorris1001** [comment]
@imnotbob and @tonesto7 Thanks for the support.  I’m up and running again.  While I cant say exactly what went wrong I do have a theory.
1) During the NST MNGR set up process the login to the Nest Developers account always failed during the first attempt but always worked on the second attempt.  I was planning on uninstalling and reinstalling but decided to logon to the Nest Developers account via my Mac.  The behavior during the Mac login was different (it did not fail the first attempt) and the questions regarding NST MNGR were asked .
2) After I logged in with my Mac I went back through the set up procedure with the NST MNGR and everything worked as expected.  Unfortunately I picked the wrong location.  I tried the method suggested to select the correct location but the effort was unsuccessful, so I uninstalled and reinstalled for the last time (I hope).

My conclusions:  I expect that the interface with the Nest Developer account was corrupt and logging in with something other than IOS cleared the corruption.  After that the install went as expected.  I also expect if I had logged on via my Mac, originally, it might have cleared up the problem without the uninstall reinstall.

I will have one last post after this with a few suggestions

**Comment by cpmorris1001** [comment]
My last post... Having been through multiple uninstalls and reinstalls I wanted to provide a little bit of feedback and maybe a bit of an offer to help:
1) Your documentation is lacking.  The community installer is by far the best method but you need to add a few steps:
   A) After the installation process you need to enter the NST MNGR code and (publish for me)
   B) After you have published the NST MNGR you need to add the two Nest Tokens copied from the Nest Developers account 

2) You need to add a “formal” uninstall procedure in the Wiki

Finally I have to mention, there is an issue with the community installer, in that you don’t know if you successfully installed or not!  Ultimately you just hit the home key and close the window on the browser.

So my offer, if you would like me to rewrite the install instructions and also an uninstall procedure for the wiki page I’m certainly willing to give it a “go”.  Let me know, and thanks again for the help.

**Comment by cpmorris1001** [comment]
Issue closed
See comments above

**Comment by jermg77** [comment]
Hi, 

I'm having the same issue. I can read the status of the thermostat in ST, but not change anything. Forgive my layman's approach here, I only understand so much. Once upon a time I had NST manager working with no issues, then my ST hub lost its mind after a firmware update. Since moving to this new hub, I have had this issue. 

I see what appears to be an obvious issue to me in the Live Log:

0e70b06f-41bf-4ea3-8427-4bde45838f60  1:16:52 PM: warn || NST Manager (v5.3.9) | sendNestApiCmd no auth token

I have triple check my Nest Dev account tokens, and reset/relogged in via NST Manager setup. No changes. I'm sure its something simple, but I'm just not seeing it. 

Any help would be appreciated.

Thanks in advance!

-Jeremy

**Comment by lifties** [comment]
I did two things, of which I'm not 100% of the two fixed my issue.
1. Used the Community Installer. 
2. Using the Community Installer, forced me to publish the smartapps before adding the nest information. 

But I believe it is publishing the app and then adding the nest information that resolves the issue.

**Comment by justinleewall** [comment]
So I am new to this but having some issues.  I am having the same problem where I can see the nest thermostats but when I change the temp it doesn't change on the thermostat.  I can see in the log that the command was sent but nothing ever happens?  any ideas?

**Comment by jermg77** [comment]
Yup, this issue persists to this day. It all started when a Smartthings firmware update killed my V2 hub. Samsung ended up replacing the hub and I rebuilt my entire setup, but NST Manager has never fully worked since. It worked fine on the old hub. At this point I've pretty much forgotten about it and moved on with my life. I've tried all the suggestions that I could via scouring the web. 

I'm open to new ideas if anyone has them....

**Comment by cpmorris1001** [comment]
Guys... I did a complete uninstall and reinstalled.  It has worked
flawlessly ever since.

**Comment by cpmorris1001** [comment]
@jermg77 and @justinleewall ... It has been a while but as I remember it there were two things that were key...
1) do a complete uninstall of NST
2) You need to reissue a NEST token.  Using the token that had been issued on my “corrupt, but used to work” install did not work.    I think this was key to the fix
3) After you reissue the NEST token you can reinstall the NST manager.  Please check out my comment on July 7

Hey guys I hope this helps.

**Comment by jermg77** [comment]
> @jermg77 and @justinleewall ... It has been a while but as I remember it there were two things that were key...
> 
> 1. do a complete uninstall of NST
> 2. You need to reissue a NEST token.  Using the token that had been issued on my “corrupt, but used to work” install did not work.    I think this was key to the fix
> 3. After you reissue the NEST token you can reinstall the NST manager.  Please check out my comment on July 7
> 
> Hey guys I hope this helps.

So, finally getting to sit down to look at this again and I can't even fully uninstall NST from my SmartThings account. I removed the NST Smartapps from SmartThings on my phone, yet when I go to delete them in the IDE I get the error "This SmartApp can't be deleted at this time because it is installed by one or more users"

Not sure what else I can do about this, I'm open to suggestions.
