### ISSUE TITLE
No more events from thermostat

### ISSUE THREAD

**Issue by syielic** [tonesto7/nest-manager#596]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects?: 0
* How many Cameras?: 0
* Using the Nest Presence Device?: Yes
* Using the Nest Weather Device?: Yes
* iOS or Android?: Android
* Mobile App Version: 5.5.0

## Current Behavior

Everything worked fine until early this morning when Nest stopped polling events for ambient temperature and heating setpoints. 

Last event was 6 hours ago, the last line being "Nest Thermostat pause updates is false".
Whenever I adjust the temperature on thermostat is not being reflected on the app and vice versa.

I accessed my nest developer account and made sure the oauth details are the same (I made sure there is no space in the end); I saved and published the Nest SmartApp and DH; rebooted my Smartthings hub - all to no avail.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible
![firefox_screenshot_2018-09-07t12-42-36 998z](https://user-images.githubusercontent.com/43064979/45220441-08fe5100-b2a6-11e8-826f-f0bcad40df21.png)

**Comment by syielic** [comment]
Problem solved by logging out and back in. I am not sure what cause this issue as all my polling settings were left on default. NST started to report again after I logged back in.

Anyway, if someone else runs into a similar problem this is what I did: 
Automation > SmartApps > NST Manager > Application Preferences > Nest Login Preferences > Log Out and Reset Nest Token

**Comment by syielic** [comment]
Seems like I still have issues where the smartapp stops reporting for hours. I can now see quite often the event pauseUpdates true and false whenever I change the temperature within NST. I don't recall seeing this event days ago. Is this normal? Shouldn't be a "lastConnection" event every now and then?

![image](https://user-images.githubusercontent.com/43064979/45248987-54e5e000-b310-11e8-9bcb-99cd8b689dac.png)

In that gap where it stopped reporting, the ambient temperature changed but the change was not reflected in NST.

**Comment by citrusmoose** [comment]
I think I might be having the same problem.  My last connection from my thermostat and protect was about 07:00 AM EDT on Friday.  Also, none of the controls in ST make it back to thermostat.  The live log seems to indicate that it's queuing the request, but no errors are mentioned.  I check all the same boxes as @syielic (except I'm on iOS, have a protect, and no presence device).  I logged into my nest developer account, and I didn't see any issues there.  I also tried logging out and back in NST manager; no change at all.

**Comment by imnotbob** [comment]
There were issues with the ST platform from a Thursday update:
a) automations not running, etc - mostly this is fixed now by ST
b) they upgraded groovy versions, so programs are getting new behaviors due to groovy changes.

I have fixes queued, waiting for Tony to push out.

**Comment by citrusmoose** [comment]
Latest update fixed things for me.

**Comment by syielic** [comment]
Everything seems to work fine now after latest update.
