### ISSUE TITLE
Automation to put Nest in Eco doesn’t work

### ISSUE THREAD

**Issue by Strauf** [tonesto7/nest-manager#597]
## Verify the following before opening an issue:

- [x ] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x ] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x ] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x ] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 3
* How many Protects? 3
* How many Cameras? -
* Using the Nest Presence Device? -
* Using the Nest Weather Device? -
* iOS or Android?: iOS 
* Mobile App Version: 11.4.1

## Current Behavior

When I open the window the Nest should go in eco as it has done. It just stopped doing it as it did a while ago and I’m not willing to go thru the whole process of setting it up on the Nest developer site again.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

My AC is going even though the windows are open!!!!

![screen shot 2018-09-08 at 8 53 18 am](https://user-images.githubusercontent.com/24484448/45254350-c8094980-b344-11e8-83d3-7c682d842266.png)
![screen shot 2018-09-08 at 8 53 07 am](https://user-images.githubusercontent.com/24484448/45254351-c8094980-b344-11e8-987c-c011f8d6f5b4.png)
![screen shot 2018-09-08 at 8 52 45 am](https://user-images.githubusercontent.com/24484448/45254352-c8094980-b344-11e8-8447-1381977b72a9.png)
![screen shot 2018-09-08 at 8 52 31 am](https://user-images.githubusercontent.com/24484448/45254353-c8094980-b344-11e8-86be-ec842a1d8481.png)
![screen shot 2018-09-08 at 8 51 45 am](https://user-images.githubusercontent.com/24484448/45254354-c8094980-b344-11e8-90c5-099805a599e7.png)

Please include a copy of your log under the IDE if possible

**Comment by Strauf** [comment]
By the way, one Automation is still working with open and close sensor. 

I also deleted the automations that are not working and recreated them. No improvement. Also updated to the latest version version 5.5. No improvement. Last time it happened I did a reinstall including the part in the Nest development site. That also required me to update Action Tiles etc. Would really like to avoid that.

**Comment by imnotbob** [comment]
We may want to move this to private message in the ST community.

What is you ST community ID?

**Comment by Strauf** [comment]
I reinstalled everything this morning and it seems to be working again.
