### ISSUE TITLE
Missing support for Nest temperature sensor

### ISSUE THREAD

**Issue by mahoekst** [tonesto7/nest-manager#598]
I have a extra temp sensor connected to my Nest. It's the primary temperature sensor i use to control my furnace as well. In the Nest app you can select the primary sensor to use. This setting is not respected by the NST manager it seems.

So either it should be able to select which temp sensor to use or make it respect the default.

I use the 'it's to cold' automation to switch on/off an separate AC and use the Nest temp to switch it on or off, but I need it to use the other sensor, not the Nest one which is in the hallway.

**Comment by tonesto7** [comment]
Nest doesn't expose the temp sensors via the API at the moment.  As soon as they add support NST will add support

**Comment by mahoekst** [comment]
Ah thanks for the quick response. That's too bad. I also wished they would expose more information for the Nest Protects (like temp, humidity, presence etc). would make for some nice extra home automation signals.
