### ISSUE TITLE
Temperature setpoints are not adjusting

### ISSUE THREAD

**Issue by meckelangelo** [tonesto7/nest-manager#600]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* How many Cameras? 0
* Using the Nest Presence Device? No
* Using the Nest Weather Device? No
* iOS or Android?: Android
* Mobile App Version: 5.5.0

## Expected Behavior

NST Manager should control the heat and cool setpoints of the thermostat based on the internal logic. 

## Current Behavior

Since the last update, it has not been able to do so. In Live Logging, I have seen the following error message nearly every minute...
remSendoSetCool Exception: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'true' with class 'java.lang.Boolean' to class 'double' @line 7654 (setTstatAutoTemps)

At line 7654 in the code, I see this logic...
if(!reqHeat && reqCool) { reqHeat = (double) (curHeatSetpoint < (reqCool - diff)) ? curHeatSetpoint : (reqCool - diff) }

It appears to me that you are attempting to cast to a double and assign to reqHeat, which I assume is a boolean, based on the first part of the if statement. I will continue to investigate your code around that area, but I'm pretty sure something is broken with the assignment to reqHeat.

## Steps to Reproduce (for bugs)

Upgrade to latest version? I don't know if anyone else has this problem, but I have since I upgraded to 5.5.0.

1.
2.
3.
4.

## Context

My Nest will adjust modes correctly, but I am having to adjust setpoints manually. None of my temperature automations are working, basically.

Please include a copy of your log under the IDE if possible

**Comment by meckelangelo** [comment]
I fixed it locally for myself. On lines 7653 and 7654, you need to wrap the assignment in parenthesis. Here is what I have deployed for myself...

if(!reqCool && reqHeat) { reqCool = (double) ((curCoolSetpoint > (reqHeat + diff)) ? curCoolSetpoint : (reqHeat + diff)) }
if(!reqHeat && reqCool) { reqHeat = (double) ((curHeatSetpoint < (reqCool - diff)) ? curHeatSetpoint : (reqCool - diff)) }

**Comment by imnotbob** [comment]
thx, submitted to next release

**Comment by csteele2144** [comment]
I having the same issue, nst manager has essentially stopped working and my AC doesn't kick on anymore.  Any idea when the fix will be pushed?

**Comment by imnotbob** [comment]
The fix is pushed.

If you are sure you are updated, we should PM in the ST community to debug.

**Comment by meckelangelo** [comment]
@csteele2144: They released it on Saturday. Make sure you're on 5.5.1.

**Comment by csteele2144** [comment]
I updated this morning and just re-enabled the automation, it seems to be working now.
