### ISSUE TITLE
NST Manager not communicating with Nest

### ISSUE THREAD

**Issue by jefffaich** [tonesto7/nest-manager#626]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?: 2
* How many Protects? 0
* How many Cameras? 1
* Using the Nest Presence Device? 0
* Using the Nest Weather Device? No
* iOS or Android?: iOS
* Mobile App Version: Classic

## Expected Behavior
 

I setup NST Manager a few months back and everything has been working perfectly. So, no bugs to report or suggestions for a change. But, it seems NST Manager has lost it's ability to communicate with the Nests. 

## Current Behavior

I just noticed yesterday that the automation for set points seems to be working within the app, but it's not actually adjusting the set point on the Nest. When I looked at the live logging on the IDE, it seems all the correct commands are being fired, just not actually making it to the Nest. I did review all the setup with the Nest API, OAuth, newest versions of Device Handlers, etc. and everything seems correct (I haven't changed anything since it was all working). Has anything changed? Any issues with the API service? 

## Context

Please include a copy of your log under the IDE if possible

f4668ccf-60b8-4c82-902f-f490d95a145b  8:19:53 AM: trace | NST Manager (v5.5.8) | [GetTimeDiffSeconds] Results for 'getLastHeardFromNestSec': (56761 seconds)
f4668ccf-60b8-4c82-902f-f490d95a145b  8:19:53 AM: trace | NST Manager (v5.5.8) | [GetTimeDiffSeconds] Results for 'getLastHeardFromNestSec': (56761 seconds)
f4668ccf-60b8-4c82-902f-f490d95a145b  8:18:56 AM: warn || NST Manager (v5.5.8) | workQueue: busy processing command
f4668ccf-60b8-4c82-902f-f490d95a145b  8:18:56 AM: trace | NST Manager (v5.5.8) | workQueue │ Run Queue: 1 | (async)
f4668ccf-60b8-4c82-902f-f490d95a145b  8:18:56 AM: trace | NST Manager (v5.5.8) | [GetTimeDiffSeconds] Results for 'getLastCmdSentSeconds': (56700 seconds)
f4668ccf-60b8-4c82-902f-f490d95a145b  8:18:56 AM: trace | NST Manager (v5.5.8) | getQueueToWork queue: 1
f4668ccf-60b8-4c82-902f-f490d95a145b  8:18:56 AM: trace | NST Manager (v5.5.8) | workQueue
f4668ccf-60b8-4c82-902f-f490d95a145b  8:17:26 AM: warn || NST Manager (v5.5.8) | workQueue: busy processing command
f4668ccf-60b8-4c82-902f-f490d95a145b  8:17:26 AM: trace | NST Manager (v5.5.8) | workQueue │ Run Queue: 1 | (async)
f4668ccf-60b8-4c82-902f-f490d95a145b  8:17:26 AM: trace | NST Manager (v5.5.8) | [GetTimeDiffSeconds] Results for 'getLastCmdSentSeconds': (56610 seconds)
f4668ccf-60b8-4c82-902f-f490d95a145b  8:17:26 AM: trace | NST Manager (v5.5.8) | getQueueToWork queue: 1
f4668ccf-60b8-4c82-902f-f490d95a145b  8:17:26 AM: trace | NST Manager (v5.5.8) | workQueue

**Comment by imnotbob** [comment]
See:
https://community.smartthings.com/t/release-nst-manager-v5-0/83228/3656

**Comment by jefffaich** [comment]
Thanks. Looks like there was a platform issue, which is now resolved. Thx!
