### ISSUE TITLE
My Device Handler not showing true under OAuth

### ISSUE THREAD

**Issue by lanman1968** [tonesto7/nest-manager#650]
## Verify the following before opening an issue:

- [x] You followed the Nest Developer documentation here? [Nest Developer Account Creation](https://cdn.rawgit.com/tonesto7/nest-manager/master/Documents/html/Create_Dev_Account.html)
- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApps and *_ALL_* (5) Devices Handlers are using the latest code available.
- [x] You have reviewed the [NST Manager Wiki](http://thingsthataresmart.wiki/index.php?title=NST_Manager) for potential fixes.
- [x] That ALL SmartApps and Device Handlers have been _Published for You_ in the IDE.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* How many Cameras?
* Using the Nest Presence Device?
* Using the Nest Weather Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible

**Comment by tonesto7** [comment]
Device handlers do not require the Oauth setting

**Comment by lanman1968** [comment]
I can't figure out how to get nest installed in smart things. Isn't there updated instructions?  Seems like the video on you tube has an old version of the smart things app.
