### ISSUE TITLE
Mode not selecting properly

### ISSUE THREAD

**Issue by sjgoalie** [tonesto7/nest-manager#71]
I have 2 Nest Thermostats.  On one I'm able to use the app to set the mode (heat/cool/both/off) and it stays.  On the second, I press the buttons to select the desired mode (off, in this case) and in a second or 2 it changes to a random mode.  No matter what selection I make, it will revert to some random mode after a moment.   In this case I'm trying to set both units to "off"
## Verify the following before opening an issue:

- [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ X] The SmartApp and Device are using the latest version.
- [ X] You have reviewed the Readme for potential fixes.
- [ X] That the Device Types have be _Published for You_.
## About Your Setup:
- How many Thermostats?: 2
- How many Protects? 0
- Are you Using the Nest Presence Device? yes
- iOS or Android?:  Android
- Mobile App Version: 2.1.0
## Expected Behavior

Both units should maintain the selected state.
## Steps to Reproduce (for bugs)

On one I'm able to use the app to set the mode (heat/cool/both/off) and it stays.  On the second, I press the buttons to select the desired mode (off, in this case) and in a second or 2 it changes to a random mode.  No matter what selection I make, it will revert to some random mode after a moment.   In this case I'm trying to set both units to "off"

**Comment by tonesto7** [comment]
This is a concurrent command issue with the API.  This should be resolved in v2.0 that will be released soon

**Comment by tonesto7** [comment]
I've made a choice not to merge the fix into the current release because v2.0 should be out by weeks end.

**Comment by tonesto7** [comment]
This issue should be resolved in v2.0
