### ISSUE TITLE
Temperature set point not reporting

### ISSUE THREAD

**Issue by keltymd** [tonesto7/nest-manager#8]
It is not reporting my temp setpoint in the DH.  I am set to auto mode.

![20160316_024529000_ios](https://cloud.githubusercontent.com/assets/16531930/13800473/9c1f2866-eaf7-11e5-8b90-5ad3dcd96e62.png)

**Comment by tonesto7** [comment]
This particular issue was resolved on the last commit. However I did notice that the heat/cool tile buttons are not working for auto.  I have a patch coming in the morning.

**Comment by keltymd** [comment]
thank you for your work.  I have installed the new DH and it is now showing the setpoints. The Nest Manager is giving this error

![image](https://cloud.githubusercontent.com/assets/16531930/13811182/13ecd8a8-eb42-11e5-8f0b-b468a8486f44.png)

**Comment by tonesto7** [comment]
Closing
