### ISSUE TITLE
Nest API Info -> Nest Protect Info duplicates information

### ISSUE THREAD

**Issue by ahndee** [tonesto7/nest-manager#9]
All the information in the API Info for Nest Protects is duplicated:

The first Protect is OK
The second Protect shows two entries for each item (with the info for first and second device)
The third Protect shows three entries for each item
The nth Protect shows n entries for each item (showing the information for all previous devices as well)

**Comment by ahndee** [comment]
Found the issue:

In the `protInfoPage()` function, you have 

```
def devs = []
state.protects.each { prot ->
…
```

Those two lines should be switched (in order to start with an empty map for each protect inside the loop). While I have only one thermostat and thus cannot check, I would assume that the same change also needs to be done in the `tstatInfoPage()` function

**Comment by tonesto7** [comment]
thanks @ahndee... Nice catch... I'm not sure that i've noticed that before.  

I have corrected it and it will be in next release later today

**Comment by ahndee** [comment]
Works correctly after update.
